Update EKS cluster creation page for Rancher v2.5
rancher/docs pull request #2674
Opened 2020-09-04 22:19 UTC by catherineluse

This PR addresses the feedback from this other PR that I accidentally merged https://github.com/rancher/docs/pull/2661

It partly addresses this issue https://github.com/rancher/docs/issues/2639

2020-09-10 23:26 UTC, cloudnautique commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +- Private access should be enabled, and Rancher must share a subnet with the cluster and have network access to the cluster, which can be configured with a security group
@rmweir do we provide the user with the command to launch the agents on the Cluster without Rancher needing direct access to the API endpoint?  We do not require direct API access to the other types of clusters. 

What is the actual requirement for Rancher to automatically register the cluster? I wouldn't think it is a shared subnet, that would mean we need 1 Rancher management plane per EKS cluster.

2020-09-10 23:47 UTC, rmweir commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +- Private access should be enabled, and Rancher must share a subnet with the cluster and have network access to the cluster, which can be configured with a security group
@cloudnautique it's true until this is completed: https://github.com/rancher/rancher/issues/28356. Then it will have to be confirmed that it does indeed work.

2020-09-11 03:08 UTC, cloudnautique commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +- Private access should be enabled, and Rancher must share a subnet with the cluster and have network access to the cluster, which can be configured with a security group
@catherineluse when that PR is merged we should update that the user will need to run the Kubectl command against the EKS cluster manually.

Also, we should find the network requirements needed for connectivity in private mode. I would expect that Rancher in a peered VPC or something with direct connect should work.

2020-09-14 22:51 UTC, cloudnautique commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Standard: Rancher generated service role | If you choose this role, Rancher automatically adds a service role for use with the cluster.
Do we need to have a reference to what this is? It would make it easier for teams to explain it to the Security team.

2020-09-14 22:53 UTC, cloudnautique commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Custom: Choose from your existing service roles | If you choose this role, Rancher lets you choose from service roles that you're already created within AWS. For more information on creating a custom
Can we get a minimum IAM permissions policy for this? We have had to add these in other places for AWS and Azure.

2020-09-14 22:53 UTC, cloudnautique commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Optional: To encrypt secrets, select or enter a key created in [AWS Key Management Service (KMS)](https://docs.aws.amazon.com/kms/latest/developerguide/overview.html)
Should we call this out in the IAM policy permissions?

2020-09-14 22:55 UTC, cloudnautique commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Configure control plane logs to send to Amazon CloudWatch. You are charged the standard CloudWatch Logs data ingestion and storage costs for any logs sent to CloudWatch Logs from your clusters.
Will this change IAM Permissions required? Are these included in the Rancher default policy?

2020-09-14 22:56 UTC, cloudnautique requested changes
Few comments around IAM that need to be addressed.

2020-09-25 00:28 UTC, catherineluse commented
I'm going to merge this PR for now because Ricky is going to make a PR and I want it to be based on these changes. I will make sure Bill's feedback gets addressed in another PR.

2020-09-25 00:28 UTC, merged