Update docker install command for Rancher 2.5
rancher/docs pull request #2675
Opened 2020-09-05 01:49 UTC by catherineluse

This is a draft PR because I haven't checked/tested the links yet. The idea is that every link would go back to the same explanatory paragraph. The content changes are ready for review.

2020-09-07 19:32 UTC, cbron requested changes

2020-09-07 19:32 UTC, cbron commented on content/rancher/v2.x/en/upgrades/upgrades/single-node/_index.md
> +---
Is this whole file related, and should I review it ?

2020-09-07 19:32 UTC, cbron commented on content/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/_index.md
> +When the Rancher server is deployed in the Docker container, a local Kubernetes cluster is installed within the container, then Rancher is deployed on the cluster. Because privileged access is requir
```suggestion
When the Rancher server is deployed in the Docker container, a local Kubernetes cluster is installed within the container for Rancher to use. Because many features of Rancher run as deployments, and privileged mode is required to run containers within containers, you will need to install Rancher with the `--privileged` option.
```

Feel free to refactor the grammar, but the previous way suggested that it was possible to run rancher without privileged and some features just wouldn't run, but Rancher won't run at all without the privileged flag now.

2020-09-07 19:34 UTC, cbron commented
Oh and also we need to do the `addLocal` helm option changes, where auto goes away in favor of just true or false.

2020-09-09 18:34 UTC, catherineluse commented on content/rancher/v2.x/en/upgrades/upgrades/single-node/_index.md
> +---
This file was supposed to be deleted because it's now located at /rancher/v2.x/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/. I have added a commit to remove this duplicate.

2020-09-09 18:38 UTC, catherineluse commented
I have added a commit to change the default value for addLocal to true in the Helm chart config reference.

2020-09-11 23:07 UTC, cbron reviewed
This looks good, but we do need to add one more thing. Basically that if you turn addLocal off then most v2 features just won't work, including EKS provisioner. Example: https://github.com/rancher/rancher/issues/28764

2020-09-11 23:38 UTC, catherineluse commented
Added the note

> If you turn addLocal off, most Rancher v2.5 features won't work, including the EKS provisioner.

2020-09-11 23:50 UTC, cbron approved these changes
lgtm

2020-09-11 23:50 UTC, merged