Update monitoring docs
rancher/docs pull request #2724
Opened 2020-10-01 21:33 UTC by catherineluse

2020-10-02 20:10 UTC, catherineluse commented
should add this too https://github.com/rancher/docs/issues/2720

2020-10-05 23:43 UTC, aiyengar2 requested changes
@catherineluse the docs look awesome! I took a look at it and left some comments.

Since my comments cover any / all changes from https://github.com/rancher/docs/pull/2719, I'll be closing out my PR in favor of this one.

Please ping me when I should take a second look through it!

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +The default username and password for the Grafana instance will be `admin`/`prom-operator`. However, Grafana dashboards are served via the Rancher authentication proxy, so only users who are currentl
```suggestion
Rancher allows any users who are authenticated by Kubernetes and have access the Grafana service deployed by the Rancher Monitoring chart to access Grafana via the Rancher Dashboard UI. By default, all users who are able to access Grafana are given the [Viewer](https://grafana.com/docs/grafana/latest/permissions/organization_roles/#viewer-role) role, which allows them to view any of the default dashboards deployed by Rancher. 

However, users can choose to log in to Grafana as an [Admin](https://grafana.com/docs/grafana/latest/permissions/organization_roles/#admin-role) if necessary. The default Admin username and password for the Grafana instance will be `admin`/`prom-operator`, but alternative credentials can also be supplied on deploying / upgrading the chart.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +This CRD declaratively specifies how groups of Kubernetes services should be monitored. Any Services in your cluster that match the labels located within the ServiceMonitor selector field will be mon
```suggestion
This CRD declaratively specifies how groups of Kubernetes services should be monitored. Any Services in your cluster that match the labels located within the ServiceMonitor `selector` field will be monitored based on the `endpoints` specified on the ServiceMonitor. For more information on what fields can be specified, please look at the [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitor) provided by Prometheus Operator.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +This CRD declaratively specifies how group of pods should be monitored. Any Pods in your cluster that match the labels located within the PodMonitor selector field will be monitored based on the podM
```suggestion
This CRD declaratively specifies how group of pods should be monitored. Any Pods in your cluster that match the labels located within the PodMonitor `selector` field will be monitored based on the `podMetricsEndpoints` specified on the PodMonitor. For more information on what fields can be specified, please look at the [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmonitorspec) provided by Prometheus Operator.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +The Alertmanager needs to be a Secret that exists in the `cattle-monitoring` system namespace in order for that to be used.
```suggestion
The Alertmanager Config Secret needs to be a Secret that exists in the `cattle-monitoring` system namespace in order for that to be used. On deploying the Rancher Monitoring application, a default Secret is automatically created if an existing Secret is not specified as part of the `Chart Options`; however, the Secret created on installing the chart will never be modified / removed on an upgrade / uninstall.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +Customizing the alerts recorded by Prometheus and the configuration of notifiers that should notify users when alerts are triggered will primarily involve creating/modifying PrometheusRules and the A
```suggestion
Customizing the alerts recorded by Prometheus and the configuration of notifications based on those alerts will primarily involve creating/modifying PrometheusRules and the Alertmanager Config Secret.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +This CRD defines a desired set of Prometheus alerting and/or recording rules.
```suggestion
This CRD defines a group of Prometheus alerting and/or recording rules.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +Labels are concise values that identify the alert (e.g. cluster name or severity), while Annotations contain other important pieces of information that need to be displayed when notifying users about
```suggestion
To add a group of alerting / recording rules, you should create a PrometheusRule CR the defines a RuleGroup with your desired rules, each specifying:
- The name of the new alert / record
- A PromQL expression for the new alert / record (`expr`)
- Labels that should be attached to the alert / record that identify it (e.g. cluster name or severity)
- Annotations that encode any additional important pieces of information that need to be displayed on the notification for an alert (e.g. summary, description, message, runbook URL, etc.). This field is not required for recording rules.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +
can drop this section in favor of the modification recommended above since both are in PrometheusRules

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +There only needs to be one Alertmanager in the cluster, and when `rancher-monitor` is installed, a default Alertmanager config is created.
```suggestion
By default, Rancher Monitoring deploys a single Alertmanager onto a cluster that uses a default Alertmanager Config Secret. As part of the chart deployment options, you can opt to increase the number of replicas of the Alertmanager deployed onto your cluster that can all be managed using the same underlying Alertmanager Config Secret.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +> Normally, the Alertmanager config secret is configured as a resource that's not managed by Helm. For the `rancher-monitoring` chart, the default case will leave that secret behind. You should save
```suggestion
> By default, you can either choose to supply an existing Alertmanager Config Secret (i.e. any Secret in the `cattle-monitoring-system` namespace) or allow Rancher Monitoring to deploy a default Alertmanager Config Secret onto your cluster. By default, the Alertmanager Config Secret created by Rancher will never be modified / deleted on an upgrade / uninstall of the `rancher-monitoring` chart to prevent users from losing or overwriting their alerting configuration when executing operations on the chart.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +If using an Existing Secret, please add the label `alertmanager_config` to the Secret to enable modifying the secret using the Rancher Dashboard UI.
No longer true; see updated comment above.
```suggestion
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +In the Alertmanager documentation about routes, it is said that there must be one "configured top-level route, which must match all alerts (i.e. not have any configured matchers)." On this page, we r
Let's remove all of this since it's TBD depending on how this is implemented on the Rancher UI. We should track a task to update the documentation once those changes are in / we have a better idea of how this UI will actually be implemented.

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +If the scrape configuration you want cannot be specified via a ServiceMonitor or PodMonitor at the moment, you can provide an additionalScrapeConfigSecret on deploying or upgrading `rancher-monitorin
```suggestion
If the scrape configuration you want cannot be specified via a ServiceMonitor or PodMonitor at the moment, you can provide an `additionalScrapeConfigSecret` on deploying or upgrading `rancher-monitoring`.
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +```
let's drop this example till it's more clear how we expect users to interact with this.

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +```
```suggestion
To set up notifications via Slack, the following Alertmanager Config YAML should be placed into the `alertmanager.yaml` key of the Alertmanager Config Secret, where the `api_url` should be updated to use your Webhook URL from Slack:
```yaml
route:  
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - send_resolved: true
    text: '{{ template "slack.rancher.text" . }}'
    api_url: <user-provided slack webhook url here>
templates:
- /etc/alertmanager/config/*.tmpl
```
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +If you previously enabled monitoring in Rancher prior to v2.5, there is no upgrade path for the monitoring application. You will need to disable monitoring and re-enable monitoring in Rancher.
```suggestion
If you previously enabled Monitoring, Alerting, or Notifiers in Rancher prior to v2.5, there is no upgrade path for switching to the new monitoring / alerting solution. You will need to disable monitoring / alerting / notifiers in Cluster Manager before deploying the new monitoring solution via Cluster Explorer. 
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +The operator that manages Prometheus is still called the Prometheus operator, but it is now deployed as part of the `kube-prometheus-stack` Helm chart.
```suggestion
### Legacy Monitoring / Alerting via Cluster Manager

As of v2.2.0, Rancher's Cluster Manager allowed users to enable Monitoring & Alerting V1 (both powered by [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator)) independently within a cluster. For more information on how to configure Monitoring & Alerting V1, see the [Legacy docs](/rancher/v2.x/en/monitoring-alerting/legacy).

When Monitoring is enabled, Monitoring V1 deploys [Prometheus](https://prometheus.io/) and [Grafana](https://grafana.com/docs/grafana/latest/getting-started/what-is-grafana/) onto a cluster to monitor the state of processes of your cluster nodes, Kubernetes components, and software deployments and create custom dashboards to make it easy to visualize collected metrics. Monitoring V1 could be configured on both a cluster-level and on a project-level and would automatically scrape certain workloads deployed as Apps on the Rancher cluster.

When Alerts or Notifiers are enabled, Alerting V1 deploys [Prometheus Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) and a set of Rancher controllers onto a cluster that allows users to define alerts and configure alert-based notifications via Email, Slack, PagerDuty, etc. Users can choose to create different types of alerts depending on what needs to be monitored (e.g. System Services, Resources, CIS Scans, etc.); however, PromQL Expression-based alerts can only be created if Monitoring V1 is enabled.

### Monitoring / Alerting via Cluster Explorer in Rancher 2.5

As of v2.5.0, Rancher's Cluster Explorer now allows users to enable Monitoring & Alerting V2 (both powered by [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator)) together within a cluster. 

Unlike in Monitoring & Alerting V1, both features are packaged in a single Helm chart found [here](https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-monitoring). The behavior of this chart and configurable fields closely matches [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack), a Prometheus Community Helm chart, and any deviations from the upstream chart can be found in the [CHANGELOG.md](https://github.com/rancher/charts/blob/dev-v2.5/charts/rancher-monitoring/CHANGELOG.md) maintained with the chart.

If you currently use Monitoring or Alerting V1 and are interested in upgrading to Monitoring & Alerting V2 in Rancher 2.5, please see [Migrating to 2.5.x](/rancher/v2.x/en/monitoring-alerting/2.5.x/migrating/). For more information on how to configure Monitoring & Alerting V2, see the [2.5.x docs](/rancher/v2.x/en/monitoring-alerting/2.5.x).
```

2020-10-05 23:43 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/rbac/_index.md
>  The `rancher-monitoring` chart installs three `ClusterRoles`.
Can you just replace this entire file with the following contents?
```
This section describes the expectations for RBAC for Rancher Monitoring.

## Cluster Admins

By default, only those with the cluster-admin `ClusterRole` should be able to:

- Install the `rancher-monitoring` App onto a cluster and all other relevant configuration performed on the chart deploy
  - e.g. whether default dashboards are created, what exporters are deployed onto the cluster to collect metrics, etc.
- Create / modify / delete Prometheus deployments in the cluster via Prometheus CRs
- Create / modify / delete Alertmanager deployments in the cluster via Alertmanager CRs
- Persist new Grafana dashboards or datasources via creating ConfigMaps in the appropriate namespace
- Expose certain Prometheus metrics to the k8s Custom Metrics API for HPA via a Secret in the `cattle-monitoring-system` namespace

## Users with k8s ClusterRole-based Permissions

The `rancher-monitoring` chart installs the following three `ClusterRoles`. By default, they aggregate into the corresponding k8s `ClusterRoles`:

| ClusterRole | Aggregates To Default K8s ClusterRole  |
| ------------------------------| ---------------------------|
| `monitoring-admin` | `admin`|
| `monitoring-edit` | `edit` |
| `monitoring-view` | `view ` |

These `ClusterRoles` provide different levels of access to the Monitoring CRDs based on the actions that can be performed:

| CRDs (monitoring.coreos.com) | Admin | Edit | View |
| ------------------------------| ---------------------------| ---------------------------| ---------------------------|
| <ul><li>`prometheuses`</li><li>`alertmanagers`</li></ul>| Get, List, Watch | Get, List, Watch | Get, List, Watch |
| <ul><li>`servicemonitors`</li><li>`podmonitors`</li><li>`prometheusrules`</li></ul>| * | * | Get, List, Watch |

On a high level, the following permissions are assigned by default as a result.

### Users with k8s Admin / Edit Permissions

Only those with the the cluster-admin / admin / edit `ClusterRole` should be able to:

- Modify the scrape configuration of Prometheus deployments via ServiceMonitor and PodMonitor CRs
- Modify the alerting / recording rules of a Prometheus deployment via PrometheusRules CRs

### Users with k8s View Permissions

Only those with who have some k8s `ClusterRole` should be able to:

- View the configuration of Prometheuses that are deployed within the cluster
- View the configuraiton of Alertmanagers that are deployed within the cluster
- View the scrape configuration of Prometheus deployments via ServiceMonitor and PodMonitor CRs
- View the alerting / recording rules of a Prometheus deployment via PrometheusRules CRs

## Additional Monitoring Roles

Monitoring also creates six additional `Roles` that are not assigned to users by default but are created within the cluster. Admins should use these roles to provide more fine-grained access to users:

| Role | Purpose  |
| ------------------------------| ---------------------------|
monitoring-config-admin | Allow admins to assign roles to users to be able to view / modify Secrets and ConfigMaps within the cattle-monitoring-system namespace. Modifying Secrets / ConfigMaps in this namespace could allow users to alter the cluster's Alertmanager configuration, Prometheus Adapter configuration, additional Grafana datasources, TLS secrets, etc. |
monitoring-config-edit | Allow admins to assign roles to users to be able to view / modify Secrets and ConfigMaps within the cattle-monitoring-system namespace. Modifying Secrets / ConfigMaps in this namespace could allow users to alter the cluster's Alertmanager configuration, Prometheus Adapter configuration, additional Grafana datasources, TLS secrets, etc. |
monitoring-config-view | Allow admins to assign roles to users to be able to view Secrets and ConfigMaps within the cattle-monitoring-system namespace. Viewing Secrets / ConfigMaps in this namespace could allow users to observe the cluster's Alertmanager configuration, Prometheus Adapter configuration, additional Grafana datasources, TLS secrets, etc. |
monitoring-dashboard-admin | Allow admins to assign roles to users to be able to edit / view ConfigMaps within the cattle-dashboards namespace. ConfigMaps in this namespace will correspond to Grafana Dashboards that are persisted onto the cluster. |
monitoring-dashboard-edit | Allow admins to assign roles to users to be able to edit / view ConfigMaps within the cattle-dashboards namespace. ConfigMaps in this namespace will correspond to Grafana Dashboards that are persisted onto the cluster. |
monitoring-dashboard-view | Allow admins to assign roles to users to be able to view ConfigMaps within the cattle-dashboards namespace. ConfigMaps in this namespace will correspond to Grafana Dashboards that are persisted onto the cluster. |

## Users with Rancher ECM-based Permissions

The relationship between the default roles deployed by Rancher Enterprise Cluster Manager (i.e. cluster-owner, cluster-member, project-owner, project-member), the default k8s roles, and the roles deployed by the rancher-monitoring chart are detailed in the table below:

| ECM Role | k8s Role | Monitoring ClusterRole / Role | ClusterRoleBinding or RoleBinding?
| --------- | --------- | --------- | --------- |
cluster-owner | cluster-admin | N/A | ClusterRoleBinding
cluster-member | admin | monitoring-admin | ClusterRoleBinding
project-owner | edit | monitoring-edit | RoleBinding within Project namespace
project-member | view | monitoring-view | RoleBinding within Project namespace

### Differences in 2.5.x

Users with the project-member or project-owners roles assigned will not be given access to either Prometheus or Grafana in Rancher 2.5.x since we only create Grafana or Prometheus on a cluster-level.

In addition, while project owners will still be only able to add ServiceMonitors / PodMonitors that scrape resources within their project's namespace by default, PrometheusRules are not scoped to a single namespace / project. Therefore, any alert rules or recording rules created by project-owners within their project namespace will be applied across the entire cluster, although they will be unable to view / edit / delete any rules that were created outside the project's namespace.

### Assigning Additional Access

If cluster-admins would like to provide additional admin/edit access to users outside of the roles offered by the rancher-monitoring chart, the following table identifies the potential impact:

|CRDs (monitoring.coreos.com) | Can it cause impact outside of a namespace / project? | Impact
|----------------------------| ------| ----------------------------|
| `prometheuses`| Yes, this resource can scrape metrics from any targets across the entire cluster (unless the Operator itself is otherwise configured). | User will be able to define the configuration of new cluster-level Prometheus deployments that should be created in the cluster.
| `alertmanagers`| No | User will be able to define the configuration of new cluster-level Alertmanager deployments that should be created in the cluster. Note: if you just want to allow users to configure settings like Routes and Receivers, you should just provide access to the Alertmanager Config Secret instead.
| <ul><li>`servicemonitors`</li><li>`podmonitors`</li></ul>| No, not by default; this is configurable via `ignoreNamespaceSelectors` on the Prometheus CR. | User will be able to set up scrapes by Prometheus on endpoints exposed by Services / Pods within the namespace they are given this permission in.
| `prometheusrules`| Yes, PrometheusRules are cluster-scoped. | User will be able to define alert or recording rules on Prometheus based on any series collected across the entire cluster.

| k8s Resources | Namespace | Can it cause impact outside of a namespace / project? | Impact
|----------------------------| ------| ------| ----------------------------|
| <ul><li>`secrets`</li><li>`configmaps`</li></ul>| `cattle-monitori [...]

2020-10-05 23:45 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/rbac/_index.md
>  The `rancher-monitoring` chart installs three `ClusterRoles`.
updated the above description based on @cbron 's comment in https://github.com/rancher/docs/pull/2719#discussion_r499929212

2020-10-07 22:59 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +Prometheus collects metrics from the cluster components, which you can view in graphs and charts.
updated

2020-10-07 23:01 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +This page describes how to enable monitoring for a cluster using Rancher's new monitoring application, which was introduced in Rancher v2.5. For the legacy docs about monitoring, refer to [this secti
updated

2020-10-07 23:39 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +- [Changes to Role-based Access Control](#changes-to-role-based-access-control)
updated

2020-10-07 23:42 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +- [Prometheus Adapter](#prometheus-adapter)
updated

2020-10-07 23:46 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +- [Enable Monitoring](#enable-monitoring)
Updated

2020-10-08 16:50 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +- [Resource Requirements](#resource-requirements)
updated

2020-10-08 16:53 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +- [Configuration Reference](#configuration-reference)
updated

2020-10-08 16:58 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +  - [Viewing Active Alerts in Alertmanager](#viewing-active-alerts-in-alertmanager)
updated

2020-10-08 16:59 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +For more information about role-based access control in `rancher-monitoring`, refer to [this page.](./rbac)
updated

2020-10-08 17:13 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +When `rancher-monitoring` is installed, some alerts, targets, and Grafana dashboards will be set up by default.
updated

2020-10-08 17:22 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +**Result:** The monitoring app is deployed in the `cattle-monitoring-system` namespace.
did you mean the rancher/charts repo?

I've added:

> 
> ### Enabling Monitoring with the Helm CLI
> 
> Helm CLI users can install the Rancher Monitoring chart using the following  commands:
> 
> ```
> helm install rancher-monitoring-crd rancher/stable
> helm install rancher-monitoring rancher/stable
> ```
> 
> However, it is advised to use the Cluster Explorer UI for most use cases.

2020-10-08 17:34 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +The default values are in the `values.yaml` in the `rancher-monitoring` Helm chart.
updated with this link https://github.com/rancher/charts/tree/master/charts/prometheus/v9.1.0

2020-10-08 17:36 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +There is a [known issue](https://github.com/rancher/rancher/issues/28787#issuecomment-693611821) that K3s clusters require more default memory. If you are enabling monitoring on a K3s cluster, we rec
updated

2020-10-08 17:37 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +The default username and password for the Grafana instance will be `admin`/`prom-operator`. However, Grafana dashboards are served via the Rancher authentication proxy, so only users who are currentl
updated

2020-10-08 17:38 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +This CRD declaratively specifies how groups of Kubernetes services should be monitored. Any Services in your cluster that match the labels located within the ServiceMonitor selector field will be mon
updated

2020-10-08 17:39 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +This CRD declaratively specifies how group of pods should be monitored. Any Pods in your cluster that match the labels located within the PodMonitor selector field will be monitored based on the podM
updated

2020-10-08 17:39 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +Customizing the alerts recorded by Prometheus and the configuration of notifiers that should notify users when alerts are triggered will primarily involve creating/modifying PrometheusRules and the A
updated

2020-10-08 17:40 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +The Alertmanager needs to be a Secret that exists in the `cattle-monitoring` system namespace in order for that to be used.
updated

2020-10-08 17:41 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +This CRD defines a desired set of Prometheus alerting and/or recording rules.
updated

2020-10-08 17:41 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +Labels are concise values that identify the alert (e.g. cluster name or severity), while Annotations contain other important pieces of information that need to be displayed when notifying users about
updated

2020-10-08 17:42 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +
deleted Recording Rules section

2020-10-08 17:43 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +There only needs to be one Alertmanager in the cluster, and when `rancher-monitor` is installed, a default Alertmanager config is created.
updated

2020-10-08 17:43 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +> Normally, the Alertmanager config secret is configured as a resource that's not managed by Helm. For the `rancher-monitoring` chart, the default case will leave that secret behind. You should save
updated

2020-10-08 17:44 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +If using an Existing Secret, please add the label `alertmanager_config` to the Secret to enable modifying the secret using the Rancher Dashboard UI.
deleted

2020-10-08 17:45 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +In the Alertmanager documentation about routes, it is said that there must be one "configured top-level route, which must match all alerts (i.e. not have any configured matchers)." On this page, we r
deleted

2020-10-08 17:45 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +If the scrape configuration you want cannot be specified via a ServiceMonitor or PodMonitor at the moment, you can provide an additionalScrapeConfigSecret on deploying or upgrading `rancher-monitorin
updated

2020-10-08 17:46 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +```
updated

2020-10-08 17:47 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +```
deleted

2020-10-08 17:48 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +If you previously enabled monitoring in Rancher prior to v2.5, there is no upgrade path for the monitoring application. You will need to disable monitoring and re-enable monitoring in Rancher.
updated

2020-10-08 17:49 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +The operator that manages Prometheus is still called the Prometheus operator, but it is now deployed as part of the `kube-prometheus-stack` Helm chart.
updated

2020-10-08 17:53 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/rbac/_index.md
>  The `rancher-monitoring` chart installs three `ClusterRoles`.
I used this content, but replaced ECM with Cluster Manager because Denise said we aren't using the phrase Enterprise Cluster Manager anymore.

2020-10-08 19:53 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +**Result:** The monitoring app is deployed in the `cattle-monitoring-system` namespace.
Based on the conversation with @cbron offline, this comment should be dropped entirely since Helm CLI is not a generally supported path by Rancher to install the charts.

@catherineluse can you drop the changes you just added? Sorry about the confusion.

2020-10-08 19:55 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +The default values are in the `values.yaml` in the `rancher-monitoring` Helm chart.
The link should be https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml, that's the wrong chart

2020-10-09 21:44 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/_index.md
> +The default values are in the `values.yaml` in the `rancher-monitoring` Helm chart.
thanks, I have updated the link

2020-10-09 22:10 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +- [About Prometheus Configuration](#about-prometheus-configuration)
```suggestion
- [Configuring Prometheus](#configuring-prometheus)
```

2020-10-09 22:10 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +# About Prometheus Configuration
```suggestion
# Configuring Prometheus
```

2020-10-09 22:17 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +  - [Recording Rules](#recording-rules)
section no longer exists
```suggestion
```

2020-10-09 22:30 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +If you want to enable Istio in the cluster, you might need to use an additional scrape configuration to ensure you can view traffic, metrics and graphs for resources deployed in other namespaces than
@catherineluse let's just leave something that says that "an example of where this might be used is istio" and link to the istio docs

2020-10-09 22:33 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +For information on configuring custom Prometheus metrics and alerting rules, refer to the upstream documentation for the [Prometheus operator.](https://github.com/prometheus-operator/prometheus-opera
updated

2020-10-09 22:33 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +- [About Prometheus Configuration](#about-prometheus-configuration)
updated

2020-10-09 22:33 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +# About Prometheus Configuration
updated

2020-10-09 22:34 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +By default, a set of these resources is created within your cluster as part of deploying this chart to set up a basic Monitoring/Alerting stack. We use the ones generated by [kube-prometheus.](https:
updated

2020-10-09 22:34 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +For more information about how ServiceMonitors work, refer to the [Prometheus documentation.](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/running-
updated

2020-10-09 22:36 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +The Alertmanager Config Secret needs to be a Secret that exists in the `cattle-monitoring` system namespace in order for that to be used. On deploying the Rancher Monitoring application, a default Se
Dropped the section

2020-10-09 22:36 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +  - [Recording Rules](#recording-rules)
deleted

2020-10-09 22:37 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +- A PromQL expression for the new alert / record (`expr`)
deleted

2020-10-09 22:38 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +For more information on what fields can be specified, please look at the [spec.](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusrulespec)
updated

2020-10-09 22:41 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +For more information, refer to the [official Prometheus documentation about configuring routes.](https://www.prometheus.io/docs/alerting/latest/configuration/#route)
added:

> The notification integrations are configured with the `receiver`, which is documented [here.](https://prometheus.io/docs/alerting/latest/configuration/#receiver)

2020-10-09 22:50 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/configuration/_index.md
> +If you want to enable Istio in the cluster, you might need to use an additional scrape configuration to ensure you can view traffic, metrics and graphs for resources deployed in other namespaces than
simplified the section like this:

> # Additional Scrape Configurations
> 
> If the scrape configuration you want cannot be specified via a ServiceMonitor or PodMonitor at the moment, you can provide an `additionalScrapeConfigSecret` on deploying or upgrading `rancher-monitoring`.
> 
> A [scrape_config section](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) specifies a set of targets and parameters describing how to scrape them. In the general case, one scrape configuration specifies a single job.
> 
> An example of where this might be used is with Istio. For more information, see [this section.](https://rancher.com/docs/rancher/v2.x/en/istio/setup/enable-istio-in-cluster/#selectors-scrape-configs)

2020-10-09 23:03 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +Monitoring V1 could be configured on both a cluster-level and on a project-level and would automatically scrape certain workloads deployed as Apps on the Rancher cluster.
Ok. In this section I'm also avoiding "legacy" and "cluster manager" because in a meeting today it was determined that it will just confuse people and we should say Rancher v2.4 instead.

2020-10-09 23:56 UTC, aiyengar2 commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +Monitoring V1 could be configured on both a cluster-level and on a project-level and would automatically scrape certain workloads deployed as Apps on the Rancher cluster.
yup, sounds good to me!

2020-10-09 23:57 UTC, aiyengar2 approved these changes
LGTM; once we make the last two changes in the comments feel free to merge

2020-10-10 00:00 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +Monitoring V1 could be configured on both a cluster-level and on a project-level and would automatically scrape certain workloads deployed as Apps on the Rancher cluster.
Added:

> Monitoring V2 can only be configured on the cluster level. Project-level monitoring and alerting is no longer supported.

2020-10-10 00:05 UTC, catherineluse commented on content/rancher/v2.x/en/monitoring-alerting/migrating/_index.md
> +Project owners and members no longer get access to Grafana or Prometheus by default. If view-only users had access to Grafana, they would be able to see data from any namespace. For Kiali, any user c
deleted the sentence about Kiali

2020-10-10 00:06 UTC, merged

2020-10-10 00:06 UTC, catherineluse commented
Related issue about making sure Istio RBAC section is right https://github.com/rancher/docs/issues/2766