Reword istio overview page, make legacy docs more obvious...
rancher/docs pull request #2733
Opened 2020-10-04 20:49 UTC by brendarearden

Format resources table, Change additional scrape config
information to match current monitoring default

2020-10-05 20:33 UTC, catherineluse requested changes
@brendarearden can you please replace the placeholder URLs?

2020-10-05 23:23 UTC, cbron commented on content/rancher/v2.x/en/istio/rbac/_index.md
> + `istio-edit`| edit | Project Owner, Project Member |
I believe this is incorrect, although it looks like they get same permissions. 
project-member would be edit: https://github.com/rancher/charts/blob/dev-v2.5-source/packages/rancher-istio/charts/templates/edit-role.yaml#L6
project-owner would be admin: https://github.com/rancher/charts/blob/dev-v2.5-source/packages/rancher-istio/charts/templates/admin-role.yaml#L6

Let me know if you found different. But the two roles do have the same permissions.

2020-10-06 00:01 UTC, brendarearden commented on content/rancher/v2.x/en/istio/rbac/_index.md
> + `istio-edit`| edit | Project Owner, Project Member |
They do get the same permissions, so that is why I listed the roles that way, but you are right that it is confusing. I went ahead and updated istio-admin to be project owner, and then istio-edit to be project member

2020-10-06 00:02 UTC, catherineluse approved these changes
LGTM

2020-10-06 00:02 UTC, merged