Add taints and tolerations section to logging
rancher/docs pull request #2774
Opened 2020-10-13 20:44 UTC by nickgerace

Add taints and tolerations section to logging. Include example YAML, and
provide both the overall backdrop, and the Rancher-specific use cases.

2020-10-13 20:46 UTC, nickgerace commented
Removed @catherineluse for the time being to let folks check out the PR 😁

2020-10-13 22:44 UTC, paynejacob requested changes

2020-10-13 22:44 UTC, paynejacob commented on content/rancher/v2.x/en/logging/_index.md
> +You can do the same with Rancher's existing taints, or with your own custom ones.
This is a good overview of the taint's and tolerations but I would expand on it to cover how to pass tolerations to the fluentbit, fluentd, and operator containers. It is also probably worth mentioning why we don't schedule to windows nodes.

2020-10-14 16:12 UTC, nickgerace commented on content/rancher/v2.x/en/logging/_index.md
> +You can do the same with Rancher's existing taints, or with your own custom ones.
I agree. Will do.

2020-10-14 20:49 UTC, paynejacob requested changes

2020-10-14 20:49 UTC, paynejacob commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +Not all parts of the logging stack are compatible with Windows Kubernetes nodes.
no parts of the logging stack...

2020-10-14 21:32 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +Not all parts of the logging stack are compatible with Windows Kubernetes nodes.
Fixed. I did not want to make an assumption in case an image or two offered experimental Windows support, etc. However, I changed the wording.

2020-10-14 21:33 UTC, paynejacob approved these changes

2020-10-14 22:03 UTC, merged

2020-10-14 22:08 UTC, nickgerace commented
Spoke with Catherine and merged accordingly.