[WIP] Add K3s Hardening Guide and Self Assessment
rancher/docs pull request #2882
Opened 2020-12-02 21:31 UTC by briandowns

Add K3s Hardening Guide and Self Assessment which are split into 2 separate files. The Hardening Guide provides information on what K3s fails and how to remediate the failures.  The Self Assessment is an exhaustive list of CIS 1.5 controls to run and verify that your K3s installation complies with.

The Self Assessment is currently incomplete as it needs to be fleshed out with the commands necessary to make the determination of pass or fail in the "audit" section.

2020-12-03 18:18 UTC, brandond requested changes
Added a couple minor corrections. Might also want to run it through a spell check - I caught a couple but probably missed a few.

2020-12-03 18:18 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Check etcd's data directory to see if it's owned by `etcd` and set to the correct permissions. Run `stat -c %U:%G /var/lib/rancher/k3s/server/db/etcd` to check the etcd data-dir owner and group, a
`ls` would show both owner and permissions, vs having to use two `stat` commands. Also, can we say what the correct permissions are?
```suggestion
2. Check etcd's data directory to see if it's owned by `etcd` and set to the correct permissions. Run `ls -la /var/lib/rancher/k3s/server/db/etcd` and verify the owner, group, and permissions.
```

2020-12-03 18:18 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +The runtime requirements to comply with the CIS Benchmark are centered around pod security (PSP's)and network policies. These are outlined in this section. K3s doesn't apply any default PSP's or netw
PSPs are plural, not possessive or a contraction, so it doesn't need an apostrophe.
```suggestion
The runtime requirements to comply with the CIS Benchmark are centered around pod security (PSPs) and network policies. These are outlined in this section. K3s doesn't apply any default PSPs or network policies, however K3s ships with a controller that is required to enforce any network policies provided by the user. By default, K3s runs with the "NodeRestriction" admission controller. To enable PSPs, add the following to the K3s start command: `--kube-apiserver-arg="enable-admission-plugins=NodeRestriction,PodSecurityPolicy,ServiceAccount"`. This will have the effect of maintaining the "NodeRestriction" plugin as well as enabling the "PodSecurityPolicy".
```

2020-12-03 18:18 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Ensure that the `--encryption-provider-config` argument is set as appropriate.
Do we want to talk about the `--secrets-encryption` option? That will configure the encryption provider for the user.
https://rancher.com/docs/k3s/latest/en/advanced/#secrets-encryption-config-experimental

2020-12-03 18:18 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +This can be remeditated by passing a valid configuration to the `k3s` outlined above.
```suggestion
This can be remediated by passing a valid configuration to `k3s` as outlined above.
```

2020-12-03 18:18 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +An example command to be run that would providle the additional configuration and settings necessary to comply with CIS 1.5 can be referenced below. This code snippet is what would then be viewed on
K3s hide its command-line flags at startup using setproctitle so we should not recommend checking `ps -ef` to see the flags on the running command. The best way is probably to check the annotation on the node:
```
kubectl get nodes -o 'template={{range .items}}{{.metadata.name}}: {{index .metadata.annotations "k3s.io/node-args"}}{{"\n"}}{{end}}'
```

2020-12-04 21:59 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +An example command to be run that would providle the additional configuration and settings necessary to comply with CIS 1.5 can be referenced below. This code snippet is what would then be viewed on
Crap. I forgot about the `setproctitle` call. That `kubectl` w/`jq` command though seems promising. gonna play with that a bit more. Thanks.

2020-12-08 00:20 UTC, brandond approved these changes

2020-12-11 17:31 UTC, Oats87 approved these changes

2020-12-11 17:31 UTC, Oats87 commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
Are these annotations necessary for this PSP, given we know that they can cause problems on non-AppArmor enabled hosts.

2020-12-14 19:15 UTC, brandond requested changes

2020-12-14 19:15 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
I am +1 on taking these out and having them align with the PSPs that we are using for RKE2

2020-12-14 19:15 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +> **Note:** Operators must manage network policies as normal for additional namespaces that are created.
What do we mean by 'as normal'? Are we trying to say that, if they use the PSP above, they need to provide additional PSPs for all other namespaces?

2020-12-14 19:15 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Here's an example of a compliant network policy.
Can we provide some information on what this PSP does?

2020-12-14 19:15 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +The following are controls that K3s currently does not pass, by default. Each gap will be explained and whether it can be passed through manual operator intervention or if it will be addressed in a f
```suggestion
The following are controls that K3s currently does not pass by default. Each gap will be explained, along with a note clarifying whether it can be passed through manual operator intervention, or if it will be addressed in a future release of K3s.
```

2020-12-14 19:15 UTC, brandond commented on content/k3s/latest/en/security/self_assessment/_index.md
> +### CIS Kubernetes Benchmark v1.5 - K3s v1.17, v1.18, & v1.19
Are we allowed to redistribute this? If so, are there any copyright or attribution guidelines we need to follow?

2020-12-14 19:17 UTC, brandond requested changes

2020-12-14 19:17 UTC, brandond commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +The first section of the CIS Benchmark (1.1), concerns itself primarily with pod manifest permissions and ownership. K3s doesn't utilize these for the core components since everything is packaged int
This scans a bit weird to me, how about:

```suggestion
1. K3s will not modify the host operating system. Any host-level modifications will need to be done manually.
2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate options to your command-line flags or configuration file.

The first section (1.1) of the CIS Benchmark concerns itself primarily with pod manifest permissions and ownership. K3s doesn't utilize these for the core components since everything is packaged into a single binary.
```

2020-12-14 19:18 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
Yeah, I'll remove. This was made prior to the revert in RKE2.

2020-12-14 19:20 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +### CIS Kubernetes Benchmark v1.5 - K3s v1.17, v1.18, & v1.19
We checked it out when we did RKE2. Seemed legit.

2020-12-14 19:23 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Here's an example of a compliant network policy.
The comments in there are meant to serve that sine the accompanying doc (self assessment) has further detail.

2020-12-14 20:44 UTC, brandond approved these changes

2020-12-14 23:39 UTC, rancher-max reviewed
LGTM after removing the annotations in the example PSP in the hardening guide.

2020-12-21 17:17 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate opti
What command line flags are you referring to here? Possible this is a hold-over from rke2 docs and it doesnt apply to k3s?

2020-12-21 17:18 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
Still need to do this?

2020-12-21 17:20 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +### PodSecurityPolicies
This section is inaccurate because k3s does not support the profile flag.

2020-12-21 17:34 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate opti
The CLI flags in question here are in reference to the additional flags that can be passed to the control plane components. There's an example at the bottom for reference.

2020-12-21 17:38 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate opti
Which flags specifically lets k3s configure PSPs or network policies?

I dont think k3s configures either of thsese.

2020-12-21 17:52 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate opti
None directly. I'll reword it. It was in reference to this bit specifically which would enable their use. `--kube-apiserver-arg="enable-admission-plugins=NodeRestriction,PodSecurityPolicy,ServiceAccount"` Admittedly, not great wording.

2020-12-21 18:45 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
No. Removed in commit `6d47b76`.

2020-12-21 18:58 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +### PodSecurityPolicies
Updated.

2021-01-15 18:01 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +1. K3s will not modify the host operating system. Any host-level modifications will need to be done manually.
wording nit: Do you think it is accurate to say that we dont modify the host operating system? I guess it depends on definition of "host operating system," because we do lay down a bunch of binaries on the path, setup a systemd unit, etc.

If you were reading this as an operator, would that confuse you?

If so, then maybe we just say something more specific like "K3s will not modify host kernel parameters"?

I know rke2 has the same wording, so if we change it here, can you change it there too?

To be clear: I don't know the answer here, so I'm more just asking your opinion and will go with what you think works.

2021-01-15 18:08 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +1. K3s will not modify the host operating system. Any host-level modifications will need to be done manually.
From a Linux perspective, when I hear "operating system", I think kernel and not userland or fielsystem. But that's just me and I don't know if there's any consensus around that. Happy to get additional feedback here from others as well.

2021-01-15 18:09 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +1. K3s will not modify the host operating system. Any host-level modifications will need to be done manually.
yeah, ask @Oats87 about the woriding explicitly. go with what he says

2021-01-15 18:16 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +When PSPs are enabled, a policy can be applied to mitigate the necessary controls described in section 5.2 of the CIS Benchmark.
can we say satisfy instead of mitigate here?

2021-01-15 18:35 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +CIS requires that all namespaces have a network policy applied that reasonably limits traffic into namespaces and pods.
```suggestion
> NOTE: K3s's deploys kube-router for network policy enforcement. Support for this in K3s is currently experimental.

CIS requires that all namespaces have a network policy applied that reasonably limits traffic into namespaces and pods.
```

I'm not sure that the above note will render correctly or if it follows existing patterns for "notes" in our docs. Can you make sure of that before you add it in?

2021-01-15 18:59 UTC, cjellick commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Ensure that the admission control plugin `NamespaceLifecycle` is set.
This is enabled by default in kubernetes. are we doing something to disable it? Does setting our own (to enable PSP) cause the defaults to be turned off?

2021-01-15 19:22 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +CIS requires that all namespaces have a network policy applied that reasonably limits traffic into namespaces and pods.
This appears to be convention in this repo throughout the Rancher v2.x markdown files.

2021-01-21 00:31 UTC, rancher-max approved these changes
Went through these documents in a real setup and they are both correct and easy to follow.
LGTM

2021-02-24 20:34 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate opti
Spelling

```suggestion
2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate options (enabling of admission plugins) to your command-line flags or configuration file as well as manually applying appropriate policies. Further detail in the sections below.
```

2021-02-24 20:36 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +There are two areas of of host-level requirements: kernel parameters and etcd process/directory configuration. These are outlined in this section.
Duplicate word

```suggestion
There are two areas of host-level requirements: kernel parameters and etcd process/directory configuration. These are outlined in this section.
```

2021-02-24 20:37 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Before the above PSP to be effective, we need to create a couple ClusterRoles and ClusterRole. We also need to include a "system unrestricted policy" which is needed for system level pods that requir
Nit - hyphen usage

```suggestion
Before the above PSP to be effective, we need to create a couple ClusterRoles and ClusterRole. We also need to include a "system unrestricted policy" which is needed for system-level pods that require additional privileges.
```

2021-02-24 20:39 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +> NOTE: K3s's deploys kube-router for network policy enforcement. Support for this in K3s is currently experimental.
Possible mistake with the utilization of an apostrophie

```suggestion
> NOTE: K3s deploys kube-router for network policy enforcement. Support for this in K3s is currently experimental.
```

2021-02-24 20:43 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +This can be remeditated by passing this argument as a value to the `enable-admission-plugins=` and pass that to  `--kube-apiserver-arg=` argument to `k3s server`. An example can be found below.
Spelling

```suggestion
This can be remediated by passing this argument as a value to the `enable-admission-plugins=` and pass that to  `--kube-apiserver-arg=` argument to `k3s server`. An example can be found below.
```

2021-02-24 20:43 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +This can be remeditated by passing this argument as a value to the `enable-admission-plugins=` and pass that to  `--kube-apiserver-arg=` argument to `k3s server`. An example can be found below.
This is also seen throughout the document. Search for remediated and fix throughout please. Probably was a copy and paste situation :)

2021-02-24 20:46 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Logging is an important detective control for all systems, to detect potential unauthorised access.
Spelling

```suggestion
Logging is an important detective control for all systems, to detect potential unauthorized access.
```

2021-02-24 20:47 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +For `default` service accounts in the built-in namespaces (`kube-system`, `kube-public`, `kube-node-lease`, and `default`), K3s does not automatically do this. You can manually update this field on t
Spelling

```suggestion
For `default` service accounts in the built-in namespaces (`kube-system`, `kube-public`, `kube-node-lease`, and `default`), K3s does not automatically do this. You can manually update this field on these service accounts to pass the control.
```

2021-02-24 20:49 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +# CIS Hardening Guide
Remove lines 5 and 6 here. Due to the way this renders with hugo, we will see the title twice, as pictured below.

![image](https://user-images.githubusercontent.com/45179589/109063980-0f1b5e80-76a7-11eb-96ab-eb187a875af1.png)

2021-02-24 20:54 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Create a file called `/etc/sysctl.d/90-kubelet.conf` and add the snippet below. Then run `sysctl -p /etc/sysctl.d/90-kubelet.conf` to
Just want to double-check this sentence ends with "...to" was this expected? I suppose because you indicate what is being done in the bash code block below.

2021-02-24 20:58 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +The first section (1.1) of the CIS Benchmark concerns itself primarily with pod manifest permissions and ownership. K3s doesn't utilize these for the core components since everything is packaged into
Here and one or more times in the doc we mention the CIS Benchmark -- perhaps this is too nit picky, but should we be linking to it? When I read these mentions of sections of the CIS Benchmark, as a reader I don't necessarily know what that is or what is being referred to. I notice it mentioned in PodSecurityPolicies section as well (section 5.2)

2021-02-24 21:00 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +This can be remeditated by passing this argument as a value to the `enable-admission-plugins=` and pass that to  `--kube-apiserver-arg=` argument to `k3s server`. An example can be found below.
Nit: I see many sentences in the Known Issues section stating "An example can be found below." Maybe it's just me, but I expect generally to see an example right below. I believe you are referring to examples outlined in the Control Plane Execution and Argument section. If so -- do you think we should refer to that section?

I'm calling this a nit, but as I read the document it's not very apparent to me to where I need to scroll down to to see my example.

2021-02-24 21:03 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +```bash
Nit: When rendered in the browser the comments are far to the right causing a need for horizontal scrolling... This isn't really fair to ask but maybe we can make the comments closer to the left? If not no worries. It just took me a while to figure out that the issue was the bad CSS on the rancher.com website and so I had to hunt for my tiny horizontal scroll bar to see these comments.

![image](https://user-images.githubusercontent.com/45179589/109065614-180d2f80-76a9-11eb-8e55-6b3efe53f586.png)

![image](https://user-images.githubusercontent.com/45179589/109065647-20656a80-76a9-11eb-93cb-cf8463261140.png)

2021-02-24 21:06 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +If you have followed this guide, your K3s cluster will be configured to comply with the CIS Kubernetes Benchmark. You can review the [CIS Benchmark Self-Assessment Guide](../self_assessment/_index.md
Bad link

```suggestion
If you have followed this guide, your K3s cluster will be configured to comply with the CIS Kubernetes Benchmark. You can review the [CIS Benchmark Self-Assessment Guide](../self_assessment/) to understand the expectations of each of the benchmarks and how you can do the same on your cluster.
```

2021-02-24 21:15 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +This document is a companion to the K3s security hardening guide. The hardening guide provides prescriptive guidance for hardening a production installation of K3s, and this benchmark guide is meant
Nit - utilize a hyphen

```suggestion
This document is a companion to the K3s security hardening guide. The hardening guide provides prescriptive guidance for hardening a production installation of K3s, and this benchmark guide is meant to help you evaluate the level of security of the hardened cluster against each control in the CIS Kubernetes benchmark. It is to be used by K3s operators, security teams, auditors, and decision-makers.
```

2021-02-24 21:18 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +The apiserver, by default, does not authenticate itself to the kubelet's HTTPS endpoints. The requests from the apiserver are treated anonymously. You should set up certificate- based kubelet authent
Remove extra space

```suggestion
The apiserver, by default, does not authenticate itself to the kubelet's HTTPS endpoints. The requests from the apiserver are treated anonymously. You should set up certificate-based kubelet authentication to ensure that the apiserver authenticates itself to kubelets when submitting requests.
```

2021-02-24 21:20 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +If you bind the apiserver to an insecure address, basically anyone who could connect to it over the insecure port, would have unauthenticated and unencrypted access to your master node. The apiserver
Spelling 

```suggestion
If you bind the apiserver to an insecure address, basically anyone who could connect to it over the insecure port, would have unauthenticated and unencrypted access to your master node. The apiserver doesn't do any authentication checking for insecure binds and traffic to the Insecure API port is not encrypted, allowing attackers to potentially read sensitive data in transit.
```

2021-02-24 21:21 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +etcd is a highly-available key value store used by Kubernetes deployments for persistent storage of all of its REST API objects. These objects are sensitive in nature and should be protected by clien
Utilize a hyphen

```suggestion
etcd is a highly-available key-value store used by Kubernetes deployments for persistent storage of all of its REST API objects. These objects are sensitive in nature and should be protected by client authentication. This requires the API server to identify itself to the etcd server using a client certificate and key.
```

2021-02-24 21:22 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +etcd is a highly-available key value store used by Kubernetes deployments for persistent storage of all of its REST API objects. These objects are sensitive in nature and should be protected by clien
I see one or more instances of this as well ("key value" should be "key-value")

2021-02-24 21:23 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +TLS ciphers have had a number of known vulnerabilities and weaknesses, which can reduce the protection provided by them. By default Kubernetes supports a number of TLS ciphersuites including some tha
Uncertain - should "ciphersuites" be "cipher suites" ?

```suggestion
TLS ciphers have had a number of known vulnerabilities and weaknesses, which can reduce the protection provided by them. By default Kubernetes supports a number of TLS cipher suites including some that have security concerns, weakening the protection provided.
```

2021-02-24 21:25 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +`RotateKubeletServerCertificate` causes the kubelet to both request a serving certificate after bootstrapping its client credentials and rotate the certificate as its existing credentials expire. Thi
Remove erroneous "the"

```suggestion
`RotateKubeletServerCertificate` causes the kubelet to both request a serving certificate after bootstrapping its client credentials and rotate the certificate as its existing credentials expire. This automated periodic rotation ensures that there are no downtimes due to expired certificates and thus addressing availability in the CIA security triad.
```

2021-02-24 21:25 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +By default, K3s implements it's own logic for certificate generation and rotation.
remove apostrophe 

```suggestion
By default, K3s implements its own logic for certificate generation and rotation.
```

2021-02-24 21:27 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Logging is an important detective control for all systems, to detect potential unauthorised access.
Spelling

```suggestion
Logging is an important detective control for all systems, to detect potential unauthorized access.
```

2021-02-24 21:27 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Verify that the `--audit-policy-file` is set. Review the contents of the file specified and ensure that it contains avalid audit policy.
Add space

```suggestion
Verify that the `--audit-policy-file` is set. Review the contents of the file specified and ensure that it contains a valid audit policy.
```

2021-02-24 21:28 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +By derfault, K3s creates `kubelet.kubeconfig` with `644` permissions. No manual remediation needed.
Spelling

```suggestion
By default, K3s creates `kubelet.kubeconfig` with `644` permissions. No manual remediation needed.
```

2021-02-24 21:30 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +`RotateKubeletServerCertificate` causes the kubelet to both request a serving certificate after bootstrapping its client credentials and rotate the certificate as its existing credentials expire. Thi
There are a few other areas where we have "the there"

2021-02-24 21:30 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +**Note:**This feature also require the `RotateKubeletClientCertificate` feature gate to be enabled (which is the default since Kubernetes v1.7)
Spelling

```suggestion
**Note:**This feature also requires the `RotateKubeletClientCertificate` feature gate to be enabled (which is the default since Kubernetes v1.7)
```

2021-02-24 21:31 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +By default, K3s implements it's own logic for certificate generation and rotation.
There are at least a couple other places that also have this issue.

2021-02-24 21:32 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Configuration of the parameter is dependent on your use case. Please see the CIS Kubernetes Benchmark for suggestions on configuring this for your usecase.
Add hyphen

```suggestion
Configuration of the parameter is dependent on your use case. Please see the CIS Kubernetes Benchmark for suggestions on configuring this for your use-case.
```

2021-02-24 21:32 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +An operator should apply a PodSecurityPolicy that sets the `Rule` value to `MustRunAsNonRoot`. An example of this can be found in the [Hardening Guide](../hardening_guilde/_index.md).
Fix link

```suggestion
An operator should apply a PodSecurityPolicy that sets the `Rule` value to `MustRunAsNonRoot`. An example of this can be found in the [Hardening Guide](../hardening_guilde/).
```

2021-02-24 21:33 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +An operator should apply a PodSecurityPolicy that sets the `hostPID` value to false explicitly for the PSP it creates. An example of this can be found in the [Hardening Guide](../hardening_guide/_ind
Fix link

```suggestion
An operator should apply a PodSecurityPolicy that sets the `hostPID` value to false explicitly for the PSP it creates. An example of this can be found in the [Hardening Guide](../hardening_guide/).
```

2021-02-24 21:34 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Containers may run as any Linux user. Containers which run as the root user, whilst constrained by Container Runtime security features still have a escalated likelihood of container breakout.
Fix a/an usage

```suggestion
Containers may run as any Linux user. Containers which run as the root user, whilst constrained by Container Runtime security features still have an escalated likelihood of container breakout.
```

2021-02-24 21:35 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +In many cases applications running in containers do not require any capabilities to operate, so from the perspective of the principal of least privilege use of capabilities should be minimized.
Spelling

```suggestion
In many cases applications running in containers do not require any capabilities to operate, so from the perspective of the principle of least privilege use of capabilities should be minimized.
```

2021-02-24 21:36 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Kubernetes supports secrets as first-class objects, but care needs to be taken to ensure that access to secrets is carefully limited. Using an external secrets provider can ease the management of acc
Spelling

```suggestion
Kubernetes supports secrets as first-class objects, but care needs to be taken to ensure that access to secrets is carefully limited. Using an external secrets provider can ease the management of access to secrets, especially where secrets are used across both Kubernetes and non-Kubernetes environments.
```

2021-02-24 21:36 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +If you have followed this guide, your K3s cluster will be configured to comply with the CIS Kubernetes Benchmark. You can review the [CIS Benchmark Self-Assessment Guide](../self_assessment/_index.md
Updated.

2021-02-24 21:37 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +The v1.5.1 guide skips 5.6 and goes from 5.5 to 5.7. We are including it here merely for explanation.
Nit: What guide? If we reference the official/upstream CIS guide should we link to it? I don't know what this guide is as a common user IMO.

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Create a file called `/etc/sysctl.d/90-kubelet.conf` and add the snippet below. Then run `sysctl -p /etc/sysctl.d/90-kubelet.conf` to
Updated.

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +# CIS Hardening Guide
Updated.

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +For `default` service accounts in the built-in namespaces (`kube-system`, `kube-public`, `kube-node-lease`, and `default`), K3s does not automatically do this. You can manually update this field on t
Updated.

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Logging is an important detective control for all systems, to detect potential unauthorised access.
Likely from the PDF and the PDF was written by a Brit. :)

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +> NOTE: K3s's deploys kube-router for network policy enforcement. Support for this in K3s is currently experimental.
Updated.

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +Before the above PSP to be effective, we need to create a couple ClusterRoles and ClusterRole. We also need to include a "system unrestricted policy" which is needed for system level pods that requir
Updated.

2021-02-24 21:37 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +A security context defines the operating system security settings (uid, gid, capabilities, SELinux role, etc..) applied to a container. When designing your containers and pods, make sure that you con
Hyphen usage

```suggestion
A security context defines the operating system security settings (uid, gid, capabilities, SELinux role, etc..) applied to a container. When designing your containers and pods, make sure that you configure the security context for your pods, containers, and volumes. A security context is a property defined in the deployment yaml. It controls the security parameters that will be assigned to the pod/container/volume. There are two levels of security context: pod level security context, and container-level security context.
```

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +There are two areas of of host-level requirements: kernel parameters and etcd process/directory configuration. These are outlined in this section.
Updated.

2021-02-24 21:37 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +2. Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having K3s configure these by adding the appropriate opti
Updated.

2021-02-24 21:38 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +The only entries there should be system managed resources such as the kubernetes service.
Hyphen usage

```suggestion
The only entries there should be system-managed resources such as the kubernetes service.
```

2021-02-24 21:38 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +This can be remeditated by passing this argument as a value to the `enable-admission-plugins=` and pass that to  `--kube-apiserver-arg=` argument to `k3s server`. An example can be found below.
Updated.

2021-02-24 21:39 UTC, davidnuzik requested changes
I've finished reviewing spelling, etc checks throughout both guides. My apologies for the nits throughout -- please take them with a grain of salt.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +This document is a companion to the K3s security hardening guide. The hardening guide provides prescriptive guidance for hardening a production installation of K3s, and this benchmark guide is meant
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +The apiserver, by default, does not authenticate itself to the kubelet's HTTPS endpoints. The requests from the apiserver are treated anonymously. You should set up certificate- based kubelet authent
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +etcd is a highly-available key value store used by Kubernetes deployments for persistent storage of all of its REST API objects. These objects are sensitive in nature and should be protected by clien
Updated all.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +TLS ciphers have had a number of known vulnerabilities and weaknesses, which can reduce the protection provided by them. By default Kubernetes supports a number of TLS ciphersuites including some tha
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +`RotateKubeletServerCertificate` causes the kubelet to both request a serving certificate after bootstrapping its client credentials and rotate the certificate as its existing credentials expire. Thi
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +By default, K3s implements it's own logic for certificate generation and rotation.
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Logging is an important detective control for all systems, to detect potential unauthorised access.
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Verify that the `--audit-policy-file` is set. Review the contents of the file specified and ensure that it contains avalid audit policy.
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +By derfault, K3s creates `kubelet.kubeconfig` with `644` permissions. No manual remediation needed.
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +**Note:**This feature also require the `RotateKubeletClientCertificate` feature gate to be enabled (which is the default since Kubernetes v1.7)
Updated.

2021-02-24 21:50 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Configuration of the parameter is dependent on your use case. Please see the CIS Kubernetes Benchmark for suggestions on configuring this for your usecase.
Updated.

2021-02-24 21:51 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +An operator should apply a PodSecurityPolicy that sets the `Rule` value to `MustRunAsNonRoot`. An example of this can be found in the [Hardening Guide](../hardening_guilde/_index.md).
Updated.

2021-02-24 21:51 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Containers may run as any Linux user. Containers which run as the root user, whilst constrained by Container Runtime security features still have a escalated likelihood of container breakout.
Updated.

2021-02-24 21:51 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +In many cases applications running in containers do not require any capabilities to operate, so from the perspective of the principal of least privilege use of capabilities should be minimized.
Updated.

2021-02-24 21:51 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +Kubernetes supports secrets as first-class objects, but care needs to be taken to ensure that access to secrets is carefully limited. Using an external secrets provider can ease the management of acc
Updated.

2021-02-24 21:51 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +A security context defines the operating system security settings (uid, gid, capabilities, SELinux role, etc..) applied to a container. When designing your containers and pods, make sure that you con
Updated.

2021-02-24 21:51 UTC, briandowns commented on content/k3s/latest/en/security/self_assessment/_index.md
> +The only entries there should be system managed resources such as the kubernetes service.
Updated.

2021-02-24 21:56 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +The first section (1.1) of the CIS Benchmark concerns itself primarily with pod manifest permissions and ownership. K3s doesn't utilize these for the core components since everything is packaged into
You need to sign up with a valid email and fill out a form requesting the Benchmark. It's not something you can link to.

2021-02-24 22:01 UTC, briandowns commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +```bash
I brought the comments in as far as possible to keep them in a column and lined up.

2021-02-26 16:20 UTC, davidnuzik commented on content/k3s/latest/en/security/hardening_guide/_index.md
> +The first section (1.1) of the CIS Benchmark concerns itself primarily with pod manifest permissions and ownership. K3s doesn't utilize these for the core components since everything is packaged into
Copy that. thanks! Resovling this.

2021-02-26 16:28 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +TLS ciphers have had a number of known vulnerabilities and weaknesses, which can reduce the protection provided by them. By default Kubernetes supports a number of TLS ciphersuites including some tha
I still see one match at https://github.com/rancher/docs/pull/2882/files#diff-bfe898ebe76c182dc5b76cf3cc88d6d8014de491209af72c97cd16b06dfdd3acR1956 but not a big deal.

2021-02-26 16:30 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +`RotateKubeletServerCertificate` causes the kubelet to both request a serving certificate after bootstrapping its client credentials and rotate the certificate as its existing credentials expire. Thi
I still see several "the there" entires like https://github.com/rancher/docs/pull/2882/files#diff-bfe898ebe76c182dc5b76cf3cc88d6d8014de491209af72c97cd16b06dfdd3acR1924 and https://github.com/rancher/docs/pull/2882/files#diff-bfe898ebe76c182dc5b76cf3cc88d6d8014de491209af72c97cd16b06dfdd3acR1941

2021-02-26 16:31 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +By default, K3s implements it's own logic for certificate generation and rotation.
I still see https://github.com/rancher/docs/pull/2882/files#diff-bfe898ebe76c182dc5b76cf3cc88d6d8014de491209af72c97cd16b06dfdd3acR1934 and https://github.com/rancher/docs/pull/2882/files#diff-bfe898ebe76c182dc5b76cf3cc88d6d8014de491209af72c97cd16b06dfdd3acR1949

2021-02-26 16:33 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +**Result:** Does not pass. See the [Hardening Guide](../hardening_guide/_index.md) for details.
Throughout, just replace _index.md with null. I see nine entries with this and this won't work with Hugo.

2021-02-26 17:51 UTC, davidnuzik commented on content/k3s/latest/en/security/self_assessment/_index.md
> +An operator should apply a PodSecurityPolicy that sets the `Rule` value to `MustRunAsNonRoot`. An example of this can be found in the [Hardening Guide](../hardening_guilde/).
Spelling fix

```suggestion
An operator should apply a PodSecurityPolicy that sets the `Rule` value to `MustRunAsNonRoot`. An example of this can be found in the [Hardening Guide](../hardening_guide/).
```

2021-02-26 19:51 UTC, davidnuzik requested changes

2021-02-26 19:51 UTC, davidnuzik commented on content/k3s/latest/en/security/_index.md
> +This section describes methodology and means of security a K3s cluster. It's broken into 2 sections.
```suggestion
This section describes the methodology and means of securing a K3s cluster. It's broken into 2 sections.
```

2021-02-26 19:51 UTC, davidnuzik commented on content/k3s/latest/en/security/_index.md
> +* [Hardening Guide](../hardening_guide/)
```suggestion
* [Hardening Guide](./hardening_guide/)
```

2021-02-26 19:51 UTC, davidnuzik commented on content/k3s/latest/en/security/_index.md
> +* [CIS Benchmark Self-Assessment Guide](../self_assessment/)
```suggestion
* [CIS Benchmark Self-Assessment Guide](./self_assessment/)
```

2021-02-26 20:13 UTC, davidnuzik approved these changes

2021-02-26 20:14 UTC, davidnuzik commented
Let's get this merged! :)

2021-02-26 20:22 UTC, merged