Include description for security groups and private API
rancher/docs pull request #2914
Opened 2020-12-14 23:31 UTC by thedadams

The advanced user can use security groups to enable private-only API access, but still allow Rancher to communicate with the cluster. A note about this configuration is added with a link to the AWS documentation.

Related issue:
https://github.com/rancher/rancher/issues/30403

2020-12-14 23:43 UTC, catherineluse requested changes

2020-12-14 23:43 UTC, catherineluse commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Additionally, if Rancher shares a subnet with the EKS cluster, then security groups can be used to enable Rancher to communicate with the cluster's API endpoint. In this case, the import command can
I noticed that the new paragraph refers to the import command, but we didn't mention what the import command is.

I think we should explain the command, and also use the word 'registered' because we changed the name of the cluster type from imported to registered.

> If you enable private and disable public API endpoint access when creating a cluster, then there is an extra step you must take in order for Rancher to connect to the cluster successfully. In this case, a pop-up will be displayed with a command that you will run on the cluster to register it with Rancher. Once the cluster is provisioned, you can run the displayed command anywhere you can connect to the cluster's Kubernetes API.
>
> [...]
>
> Additionally, if Rancher shares a subnet with the EKS cluster, then security groups can be used to enable Rancher to communicate with the cluster's API endpoint. In this case, the command to register the cluster is not needed, and Rancher will be able to communicate with your cluster. For more information on configuring security groups, refer to the [security groups documentation](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html).

2020-12-15 20:46 UTC, rmweir requested changes

2020-12-15 20:46 UTC, rmweir commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Additionally, if Rancher shares a subnet with the EKS cluster, then security groups can be used to enable Rancher to communicate with the cluster's API endpoint. In this case, the command to register
I think fitting this into the above paragraph may be a good call. My concern is because of how it is worded a reader would read that step must be done and stop there to perform the step instead of noticing this paragraph. If someone disagree with this, disregard.

2020-12-17 01:11 UTC, rmweir approved these changes
LGTM

2020-12-17 04:17 UTC, merged