Cis v2 scheduling and alerting docs
rancher/docs pull request #2927
Opened 2020-12-17 01:18 UTC by prachidamle

2020-12-17 15:23 UTC, sowmyav27 requested changes

2020-12-17 15:23 UTC, sowmyav27 commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +Support for alerting for the cluster scan results is now also available in Rancher v2.5.4.
Should it be "from" Rancher v 2.5.4  instead ?

2020-12-17 15:23 UTC, sowmyav27 commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
>  - For RKE Kubernetes clusters, the RKE permissive profile is the default.
Currently RKE Permissive 1.6 is the default.

2020-12-17 15:23 UTC, sowmyav27 commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
>  - For cluster types other than RKE, EKS and GKE, the Generic CIS 1.5 profile will be used by default.
For RKE 2 clusters, I believe RKE2 permissive will be the default. @prachidamle Could you confirm. ?

2020-12-17 15:23 UTC, sowmyav27 commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +Since Rancher v2.5.4, it is possible to run a ClusterScan on a schedule and also specify if you should receive alerts when the scan completes.
"From" Rancher v2.5.4

2020-12-17 19:14 UTC, prachidamle commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
>  - For cluster types other than RKE, EKS and GKE, the Generic CIS 1.5 profile will be used by default.
yes that's right

2020-12-20 00:36 UTC, catherineluse commented
I have made some edits for organization and put information about 2.5.0 and 2.5.4 in separate tabs. I'll put it in staging so it's a little easier to see the result.

2020-12-20 00:36 UTC, merged

2020-12-20 00:40 UTC, catherineluse commented
@prachidamle @sowmyav27 do you have an example alertmanager config? I think it might help to see the alert route configuration in context.

> While configuring the routes for `rancher-cis-benchmark` alerts, you can specify the matching using the key-value pair `job: rancher-cis-scan`.

2020-12-21 17:38 UTC, sowmyav27 commented
@catherineluse A route configured - (A receiver using "Slack" has been configured)
```
spec:
  receiver: test-cis
  group_by:
#    - string
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  match:
    job: rancher-cis-scan
#    key: string
  match_re:
    {}
#    key: string
```

2020-12-21 20:36 UTC, catherineluse commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +{{% tab "Profiles in v2.5.0" %}}
updated to "Profiles in v2.5.0-v2.5.3"

2020-12-21 20:43 UTC, catherineluse commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +- [About the Generated Report](#about-the-generated-report)
updated to:

> From Rancher v2.5.4, the scan uses the CIS Benchmark v1.6. In Rancher v2.5.0-2.5.3, the CIS Benchmark v1.5 is used.

2020-12-21 20:53 UTC, catherineluse commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +The `rancher-cis-benchmark` supports the CIS 1.6 Benchmark version.
I have moved it up. (I think it's ok to repeat it because I expect readers will skip around the doc.)

2020-12-21 20:54 UTC, catherineluse commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +{{% tab "v2.5.0" %}}
updated to v2.5.0-v2.5.3

2020-12-21 20:54 UTC, catherineluse commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +{{% tab "Profiles in v2.5.0" %}}
updated

2020-12-21 20:56 UTC, catherineluse commented on content/rancher/v2.x/en/cis-scans/v2.5/_index.md
> +1. Enter a valid [cron schedule expression](https://en.wikipedia.org/wiki/Cron#CRON_expression) in the field **Schedule.**
updated

2020-12-21 21:01 UTC, catherineluse commented
@sowmyav27 I have made the updates here https://github.com/rancher/docs/commit/ccceb987d49e651bce1760caf5d838e2c4dde7f1

2020-12-21 21:18 UTC, prachidamle commented
LGTM