[Rancher2] Provide Windows Server version context for Rancher
rancher/docs pull request #2997
Opened 2021-02-01 18:41 UTC by nickgerace

Relevant issue: https://github.com/rancher/docs/issues/2991

2021-02-01 18:43 UTC, paynejacob approved these changes

2021-02-04 23:22 UTC, aiyengar2 requested changes
LGTM

2021-02-04 23:22 UTC, aiyengar2 commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +- Nodes with Windows Server core version 1903+ should use Docker EE-basic 19.03.
```suggestion
- Nodes with Windows Server Core version 1903+ should use Basic Docker EE 19.03.
```

We should follow the official naming scheme in the docs

2021-02-04 23:22 UTC, aiyengar2 commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +The [Kubernetes docs for Windows nodes](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support) provide a compatability matrix for whi
```suggestion
The [Kubernetes docs for Windows nodes](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support) provide a compatibility matrix that can be used to assess which versions of Windows Server are supported based on your Kubernetes cluster version.
```

2021-02-04 23:22 UTC, aiyengar2 commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +> - [Windows Server servicing channels: LTSC and SAC](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19)
```suggestion
> - [Release Information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
> - [Servicing Channels: LTSC and SAC](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19)
```

Windows Server is redundant

2021-02-04 23:22 UTC, aiyengar2 commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +If you are using Azure VMs for your nodes, you can use [Azure files](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) as a [storage class]({{<baseurl>}}/rancher/v2.x/en/cluster-admi
```suggestion
If you are using Azure VMs for your nodes, you can use [Azure files](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) as a [storage class]({{<baseurl>}}/rancher/v2.x/en/cluster-admin/volumes-and-storage/#adding-storage-classes) that is available on your cluster. For details, refer to [this section.]({{<baseurl>}}/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/azure-storageclass)
```

either `the storage class for the cluster` or `a storage class that is available on your cluster`

2021-02-04 23:37 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +- Nodes with Windows Server core version 1903+ should use Docker EE-basic 19.03.
Great observation. I mainly tried to keep things similar, but it's good to re-evaluate.

2021-02-04 23:37 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +The [Kubernetes docs for Windows nodes](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support) provide a compatability matrix for whi
Perfect. The liberal arts student in me is unhappy with myself right now. This is awesome :)

2021-02-04 23:38 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +> - [Windows Server servicing channels: LTSC and SAC](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19)
This was a copy/paste from another place. Totally agree.

2021-02-04 23:38 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +If you are using Azure VMs for your nodes, you can use [Azure files](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) as a [storage class]({{<baseurl>}}/rancher/v2.x/en/cluster-admi
Your change looks good!

2021-02-05 21:56 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +If you are using Azure VMs for your nodes, you can use [Azure files](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) as a [storage class]({{<baseurl>}}/rancher/v2.x/en/cluster-admi
There was an upstream change that I rebased to that changed this a little. Fixed regardless.

2021-02-05 21:57 UTC, nickgerace commented
Fixed @aiyengar2's nits.

2021-02-09 00:07 UTC, aiyengar2 approved these changes
LGTM

2021-02-09 19:45 UTC, cbron approved these changes

2021-02-09 19:53 UTC, merged