Add EKS launch template docs
rancher/docs pull request #3019
Opened 2021-02-10 16:40 UTC by thedadams

Issue:
https://github.com/rancher/docs/issues/2989

2021-02-10 21:53 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +A launch template ID and version can be provided in order to easily configure the EC2 instances in a node group. If a launch template is provided, the settings below must be provided in the launch te
nit: Perhaps we can end the paragraph with `[...] will not be configurable in Rancher.` and then create a quote box...

> Note:
>
> If a launch template ID and version is provided, then only the template version can be updated.
> Using a new template ID would require creating a new managed node group.

2021-02-10 21:54 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you specify a launch template that does not contain a custom AMI, then Amazon will use the [EKS-optimized AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) for the Kube
`You can configure whether the AMI has GPU enabled.` does this mean we need to ensure the VM has a GPU? What does GPU enabled mean? Perhaps, there's more context here I'm missing.

2021-02-10 21:56 UTC, nickgerace commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Spot instances are now [supported by EKS](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html#managed-node-group-capacity-types-spot). If a launch template is specified, Amazon
nit: `Note that any selection you made in the instance type dropdown will be ignored in this situation and you must specify at least one instance type to the "Spot Instance Types" section. Also note that a launch template used with EKS cannot specify spot instances.`

I think these might be better suited for a "Note:" quote box, like https://github.com/rancher/docs/pull/3019/files#r574103955.

2021-02-11 19:52 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +A launch template ID and version can be provided in order to easily configure the EC2 instances in a node group. If a launch template is provided, the settings below must be provided in the launch te
This is a restriction by EKS, so I don't think it deserves that type of notoriety. I could be convinced otherwise.

2021-02-11 19:54 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you specify a launch template that does not contain a custom AMI, then Amazon will use the [EKS-optimized AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) for the Kube
I will reword for clarity.

2021-02-11 19:54 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +Spot instances are now [supported by EKS](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html#managed-node-group-capacity-types-spot). If a launch template is specified, Amazon
I think this one is worth the notoriety.

2021-02-11 20:42 UTC, nickgerace approved these changes

2021-02-11 23:38 UTC, rmweir requested changes

2021-02-11 23:38 UTC, rmweir commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +| Desired ASG Size | The desired number of instances. This setting won't take effect until the [Cluster Autoscaler](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html) is instal
This is true for maximum and minimum, but desired sets the amount of instances with or without autoscaler.
```suggestion
| Desired ASG Size | The desired number of instances. |
```

2021-02-12 01:51 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +A launch template ID and version can be provided in order to easily configure the EC2 instances in a node group. If a launch template is provided, the settings below must be provided in the launch te
I understand what you're saying here, but that isn't quite what I was trying to convey. I will update this to make it more clear.

2021-02-12 01:52 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you specify a launch template that does not contain a custom AMI, then Amazon will use the [EKS-optimized AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) for the Kube
Will update.

2021-02-12 01:53 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you do not specify a launch template, then you will be able to configure the above options in the Rancher UI and all of them can be updated after creation. In order to take advantage of all of the
I'm not sure what else would happen. The only thing I saw when testing is what I stated.

2021-02-12 01:54 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +>Any selection you made in the instance type dropdown will be ignored in this situation and you must specify at least one instance type to the "Spot Instance Types" section. Furthermore, a launch tem
A user can specify that they want to use spot instances in a launch template. However, EKS will not accept launch templates that request spot instances.

2021-02-12 01:54 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +The folowing settings are also configurable. All of these except for the name are editable after the node group is created.
Will update.

2021-02-12 01:55 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +| Desired ASG Size | The desired number of instances. This setting won't take effect until the [Cluster Autoscaler](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html) is instal
Ok, thanks. Will update.

2021-02-12 13:57 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +>Any selection you made in the instance type dropdown will be ignored in this situation and you must specify at least one instance type to the "Spot Instance Types" section. Furthermore, a launch tem
Updated for clarity.

2021-02-17 01:33 UTC, rmweir commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you do not specify a launch template, then you will be able to configure the above options in the Rancher UI and all of them can be updated after creation. In order to take advantage of all of the
Will rancher created launch templates be tagged a certain way? If so,  can you specify the tag(s)?

2021-02-17 16:20 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you do not specify a launch template, then you will be able to configure the above options in the Rancher UI and all of them can be updated after creation. In order to take advantage of all of the
Yes, updated.

2021-02-18 20:40 UTC, rmweir requested changes

2021-02-18 20:40 UTC, rmweir commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you do not specify a launch template, then you will be able to configure the above options in the Rancher UI and all of them can be updated after creation. In order to take advantage of all of the
```suggestion
If you do not specify a launch template, then you will be able to configure the above options in the Rancher UI and all of them can be updated after creation. In order to take advantage of all of these options, Rancher will create and manage a launch template for you. Each cluster in Rancher will have one Rancher-managed launch template and each managed node group that does not have a specified launch template will have one version of the managed launch template. The name of this launch template will have the prefix "rancher-managed-lt-" followed by the display name of the cluster. In addition, the Rancher-managed launch template will be tagged with the key "rancher-managed-template" and value "do-not-modify-or-delete" to help identify it as Rancher-managed. It is important that this launch template and its versions not be modified, deleted, or used with any other clusters or managed node groups. Doing so could result in your node groups being "degraded" and needing to be destroyed and recreated.
```

2021-02-18 22:06 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you do not specify a launch template, then you will be able to configure the above options in the Rancher UI and all of them can be updated after creation. In order to take advantage of all of the
Updated.

2021-02-19 23:08 UTC, cbron requested changes

2021-02-19 23:08 UTC, cbron commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you specify a custom AMI, whether in a launch template or in Rancher, then the image must be [configured properly](https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/) and
```suggestion
If you specify a custom AMI, whether in a launch template or in Rancher, then the image must be [configured properly](https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/) and you must provide user data to [bootstrap the node](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-custom-ami). This is considered an advanced use case and understanding the requirements is imperative.
```
lol, I think that word means something else.

2021-02-19 23:08 UTC, cbron commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +| Instance Resource Tags | Tag each EC2 instance in the node group (optional) |
Would be helpful to have a required column that defines optional/required.

2021-02-19 23:08 UTC, cbron commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +
For this whole section you should add little sub-headings, can just be bold text.

2021-02-22 16:41 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +If you specify a custom AMI, whether in a launch template or in Rancher, then the image must be [configured properly](https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/) and
🤦🏻 I need to get spell check working in vim.

2021-02-22 16:52 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +| Instance Resource Tags | Tag each EC2 instance in the node group (optional) |
Added a new column.

2021-02-22 16:52 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +
Reorganized and added little sub-headings.

2021-02-22 16:57 UTC, cbron commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +
Custom AMI is missing one

2021-02-22 16:57 UTC, cbron approved these changes
Missing one header and then lgtm

2021-02-22 17:01 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +
Good catch. Added.

2021-02-22 19:26 UTC, cbron commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +
Would this paragraph on line 225 move there ?

2021-02-22 20:13 UTC, thedadams commented on content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md
> +
Yes.

2021-02-24 19:30 UTC, rmweir approved these changes
LGTM

2021-02-24 22:28 UTC, catherineluse commented
I think we need another tab that preserves the docs for people using v2.5.0-v2.5.5.

Can you please add another tab so that it's like this:

```
{{% tabs %}}
{{% tab "v2.5.6+" %}}

# your new version of this page

{{% /tab %}}
{{% tab "v2.5.0-v2.5.5" %}}

# What was previously in the v2.5.+ tab

{{% /tab %}}
{{% tab "Before v2.5" %}}
...
{{% /tab %}}
{{% /tabs %}}
```

2021-02-24 22:41 UTC, catherineluse requested changes
Should have another tab for v2.5.0-v2.5.5, see comment

2021-02-25 17:06 UTC, catherineluse approved these changes

2021-02-25 17:07 UTC, merged