K3s Etcd S3 Integration
rancher/docs pull request #3043
Opened 2021-02-18 16:45 UTC by briandowns

Adds documentation for the Etcd S3 integration for K3s.

2021-02-24 17:36 UTC, brandond requested changes
LGTM. Minor suggestion to the wording, and etcd is always styled as all-lowercase.

2021-02-24 17:36 UTC, brandond commented on content/k3s/latest/en/backup-restore/_index.md
> +To perform an Etcd snapshot and save it to S3:
```suggestion
To perform an on-demand etcd snapshot and save it to S3:
```

2021-02-24 17:36 UTC, brandond commented on content/k3s/latest/en/backup-restore/_index.md
> +To perform an Etcd snapshot restore from S3:
```suggestion
To perform an etcd snapshot restore from S3:
```

2021-02-24 17:36 UTC, brandond commented on content/k3s/latest/en/backup-restore/_index.md
> +If the appropriate S3 arguments are supplied to `k3s server`, automated snapshots will be stored in S3.
```suggestion
K3s supports writing etcd snapshots to and restoring etcd snapshots from systems with S3-compatible APIs. S3 support is available for both on-demand and scheduled snapshots.
```

2021-03-02 16:51 UTC, briandowns commented
Thanks for the review @brandond . Updates completed.

2021-03-02 20:14 UTC, brandond requested changes

2021-03-02 20:14 UTC, brandond commented on content/k3s/latest/en/backup-restore/_index.md
> +To perform an on-demand etcd snapshot restore from S3:
It seems obvious, but we should probably call out that the K3s service needs to be manually stopped first before restoring, unlike the `etcd-snapshot` command which requires that it be running?

2021-03-02 20:37 UTC, brandond approved these changes

2021-03-03 19:51 UTC, dweomer approved these changes

2021-03-04 00:48 UTC, merged