Add installation method for rke2
rancher/docs pull request #3062
Opened 2021-02-24 20:48 UTC by galal-hussein

https://github.com/rancher/docs/issues/3056

2021-02-24 23:24 UTC, davidnuzik requested changes
Various changes requested mostly relating to some minor spelling/grammar checks. I have reviewed the content and it seems fine but I don't see that we reference the tutorial in rancher/v2.x/en/installation/install-rancher-on-k8s/ as indicated in the linked GitHub issue. I think this also needs to be done.

This should get reviewed by QA for technical review and I will assign someone.

2021-02-24 23:24 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +Currently RKE2 deploys nginx-ingress as a deployment and thats can impact the rancher deployment where you can not use all servers to proxy reqeust to rancher pods, to rectify that you should drop th
```suggestion
Currently, RKE2 deploys nginx-ingress as a deployment, and that can impact the rancher deployment where you can not use all servers to proxy request to rancher pods, to rectify that you should drop the following file to /var/lib/rancher/rke2/server/manifests on any of the server nodes
```

2021-02-24 23:24 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +After that you need to run installer command and enable and start rke2:
```suggestion
After that you need to run the install command and enable and start rke2:
```

2021-02-24 23:24 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha/_index.md
> +When Kubernetes gets set up in a later step, the RKE2 tool will deploy a Nginx Ingress controller. This controller will listen on ports 80 and 443 of the worker nodes, answering traffic destined for
Grammar fix

```suggestion
When Kubernetes gets set up in a later step, the RKE2 tool will deploy an Nginx Ingress controller. This controller will listen on ports 80 and 443 of the worker nodes, answering traffic destined for specific hostnames.
```

2021-02-24 23:24 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +> **Single-node Installation Tip:**
Nit: Should we mention single-node install tip here? This is an HA guide.

2021-02-24 23:24 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha/_index.md
> +You will also need to set up a load balancer to direct traffic to the Rancher replica on both nodes. That will prevent an outage of any single node from taking down communications to the Rancher mana
both nodes? HA should be 3 minimum for quorum, no? Or I suppose we direct traffic to two of three for HA purposes doesn't necessarily mean we have 2 nodes total? I may just be misunderstanding.

2021-02-24 23:28 UTC, cjellick commented
I think we need to sanity check RKE2 vs RKE Government. What do we say elsewhere in the rancher docs?

2021-02-24 23:30 UTC, cjellick commented
THis page `https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/` should have a line in the prereqs section for rke gov that is very similar to the k3s one:
```
For the tutorial to install a K3s Kubernetes cluster, refer to this page. For help setting up the infrastructure for a high-availability K3s cluster, refer to this page.
```

2021-02-24 23:30 UTC, catherineluse commented
We refer to RKE2 elsewhere in the Rancher docs in the context of explaining how RancherD works. We didn't mention Rancher Federal.

2021-02-25 16:10 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/install-rancher-on-k8s/_index.md
> +- **In Rancher v2.4.x,** Rancher needs to be installed on a K3s Kubernetes cluster or an RKE Kubernetes cluster or on an RKE2 Kubernetes cluster.
We don't support installing rancher 2.4.x on RKE2.

2021-02-25 16:12 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/install-rancher-on-k8s/_index.md
> +For the tutorial to install a RKE2 Kubernetes cluster, refer to [this page.]({{<baseurl>}}/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2) For help setting up the infrastructure for a h
Grammar fix

```suggestion
For the tutorial to install an RKE2 Kubernetes cluster, refer to [this page.]({{<baseurl>}}/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2) For help setting up the infrastructure for a high-availability RKE2 cluster, refer to [this page.]({{<baseurl>}}/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha)
```

2021-02-25 16:14 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +### 4. Configure nginx to be a daemonset
Fix number for this step, it's number 5 (Sorry missed this last review)

```suggestion
### 5. Configure nginx to be a daemonset
```

2021-02-25 16:16 UTC, davidnuzik requested changes
Left a couple more comments for small changes.

2021-02-26 05:02 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +For systems without direct internet access, refer to the air gap installation instructions.
I think we should remove this sentence because we haven't documented an air gapped RKE2 installation.

> For systems without direct internet access, refer to the air gap installation instructions.

2021-02-26 05:03 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +These instructions assume you have set up three nodes, a load balancer, a DNS record, and an external MySQL database as described in [this section.]({{<baseurl>}}/rancher/v2.x/en/installation/resourc
Should link to the new RKE2 infrastructure page 

> ({{<baseurl>}}/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha)

2021-02-26 05:04 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +Note that in order for rke2 to work correctly with the load balancer you need to set up two listeners one for the supervisor port on 9345 and one for kubernetes API port 6443.
> Note that in order for RKE2 to work correctly with the load balancer, you need to set up two listeners: one for the supervisor on port 9345, and one for the Kubernetes API on port 6443.

2021-02-26 05:08 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +1. On the first node, you should set up the configuration file with your own pre-shared secret as the token, set the token argument on startup.
1. On the first node, you should set up the configuration file with your own pre-shared secret as the token. Set the token argument on startup.

2021-02-26 05:10 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +1. To join the rest of the nodes you need to configure them with the same shared token or the one generated automatically, here is an example of the configuration:
1. To join the rest of the nodes, you need to configure each additional node with the same shared token or the one generated automatically. Here is an example of the configuration file:

2021-02-26 05:24 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +kubectl --kubeconfig ~/.kube/config/krke23s.yaml get pods --all-namespaces
should this be ~/.kube/config/rke2.yaml?

2021-02-26 05:25 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +For more information about the `kubeconfig` file, refer to the [K3S documentation]({{<baseurl>}}/k3s/latest/en/cluster-access/) or the [official Kubernetes documentation](https://kubernetes.io/docs/c
change link to 

```
[RKE2 documentation](https://docs.rke2.io/cluster_access/)
```

2021-02-26 05:28 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +Currently, RKE2 deploys nginx-ingress as a deployment, and that can impact the rancher deployment where you can not use all servers to proxy request to rancher pods, to rectify that you should drop t
> Currently, RKE2 deploys `nginx-ingress` as a deployment, and that can impact the Rancher deployment so that you cannot use all servers to proxy requests to the Rancher pods. 
>
> To rectify that, place the following file in `/var/lib/rancher/rke2/server/manifests` on any of the server nodes:

2021-02-26 05:29 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha/_index.md
> +For more information about each installation option, refer to [this page.]({{<baseurl>}}/rancher/v2.x/en/installation)
delete

2021-02-26 05:32 UTC, catherineluse requested changes
Left a few comments

2021-02-26 06:56 UTC, ShylajaDevadiga approved these changes
LGTM

2021-03-01 15:20 UTC, davidnuzik approved these changes

2021-03-01 23:07 UTC, catherineluse approved these changes
lgtm

2021-03-02 19:01 UTC, catherineluse commented on content/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-RKE2/_index.md
> +---
_Tested on Rancher v2.5.6+_

2021-03-02 19:02 UTC, catherineluse commented
I realized this is associated with Rancher v2.5.6. Can you please rebase on the v2.5.6 branch?

2021-03-04 00:16 UTC, merged