Add cattle-logging ns recreation troubleshooting
rancher/docs pull request #3064
Opened 2021-02-25 01:05 UTC by nickgerace

Relevant issue: https://github.com/rancher/docs/issues/3055

Thanks to @atsai1220 for the fix (https://github.com/rancher/rancher/issues/29742#issuecomment-779400693).

2021-02-25 05:08 UTC, atsai1220 commented
May want to also mention related CRDs like `projectloggings.management.cattle.io`.

This comment mentioned removing `projectloggings.management.cattle.io` resolved for them. https://github.com/rancher/rancher/issues/29742#issuecomment-780126884

```
❯ kubectl get crds | grep loggings.management
clusterloggings.management.cattle.io
projectloggings.management.cattle.io
```

2021-02-25 16:00 UTC, paynejacob requested changes

2021-02-25 16:00 UTC, paynejacob commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +These resources are located in cluster ID namespaces (the cluster ID is the namespace name), and their existence causes Rancher to create the `cattle-logging` namespace if it does not exist.
This description of the cluster id namespace is confusing, are there external docs we can link to?

2021-02-25 16:32 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +These resources are located in cluster ID namespaces (the cluster ID is the namespace name), and their existence causes Rancher to create the `cattle-logging` namespace if it does not exist.
I do not believe there are, but I will re-word this regardless. I agree that it's unclear.

2021-02-25 16:32 UTC, nickgerace commented
> May want to also mention related CRDs like `projectloggings.management.cattle.io`.
> 
> This comment mentioned removing `projectloggings.management.cattle.io` resolved for them. [rancher/rancher#29742 (comment)](https://github.com/rancher/rancher/issues/29742#issuecomment-780126884)
> 
> ```
> ❯ kubectl get crds | grep loggings.management
> clusterloggings.management.cattle.io
> projectloggings.management.cattle.io
> ```

@atsai1220 good idea. Will include this as well.

2021-02-25 23:27 UTC, paynejacob approved these changes

2021-02-25 23:58 UTC, brendarearden approved these changes
LGTM

2021-02-26 15:41 UTC, cbron commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +The existence of these custom resources causes Rancher to create the `cattle-logging` namespace if it does not exist.
```suggestion
The existence of these custom resources causes Rancher to create the `cattle-logging` namespace in the downstream cluster if it does not exist.
```
This is how I understand the problem, you can correct me.

2021-02-26 15:44 UTC, cbron commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +With the cluster namespace, we can now delete the CRs that cause `cattle-logging` to be continually recreated.
We have `cluster-id` above and `cluster-namespace` below, use `cluster-id` below to avoid confusion.

2021-02-26 15:48 UTC, cbron commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +To find the name of each cluster's namespace, we need to find their respective "cluster IDs", which can be found in the Cluster Manager UI or Cluster Explorer UI (Dashboard).
```suggestion
The cluster namespace matches the cluster ID. 
```
Then push the two bullets below into sentence above: 
> In your web browser, navigate to your cluster(s) in the UI and copy the `<cluster-id>` portion from one of the URLs below:

2021-02-26 17:32 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +If your cluster running Logging v2 formerly ran Rancher v2.4 (and below) with logging enabled, you may encounter an issue where the `cattle-logging` namespace is continually being recreated.
Good call. Will probably change `it's` for `its` thought ;)

2021-02-26 17:32 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +The solution is to delete all `clusterloggings.management.cattle.io` and all `projectloggings.management.cattle.io` custom resources in each cluster's namespace.
Good call

2021-02-26 17:33 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +The existence of these custom resources causes Rancher to create the `cattle-logging` namespace if it does not exist.
Yes. Will add

2021-02-26 17:33 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +With the cluster namespace, we can now delete the CRs that cause `cattle-logging` to be continually recreated.
Agreed

2021-02-26 17:34 UTC, nickgerace commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +To find the name of each cluster's namespace, we need to find their respective "cluster IDs", which can be found in the Cluster Manager UI or Cluster Explorer UI (Dashboard).
This one might look the most different given the changes above, but if it still looks the same, I'll make this change

2021-03-03 20:51 UTC, cbron requested changes

2021-03-03 20:51 UTC, cbron commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +The `cattle-logging` namespace was the namespace used for Logging v1.
Don't say v1, say Cluster Manager

2021-03-03 20:51 UTC, cbron commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +The `cattle-logging` namespace was the namespace used for Logging v1.
Actually I think this line just needs to be deleted.

2021-03-03 20:51 UTC, cbron commented on content/rancher/v2.x/en/logging/v2.5/_index.md
> +Now that we have the `<cluster-id>` namespace, we can delete the CRs that cause `cattle-logging` to be continually recreated.
Maybe add a warning: ensure this logging is no longer being used first.

2021-03-03 22:51 UTC, cbron approved these changes

2021-03-03 22:52 UTC, cbron commented
This is not required for 2.5.6 launch. It can be de-prioritized from merging. Ideally it goes in sometime this week.

2021-04-05 20:44 UTC, catherineluse approved these changes

2021-04-05 20:44 UTC, merged