Update Rancher requirements to include RKE2 installs
rancher/docs pull request #3166
Opened 2021-04-07 15:39 UTC by catherineluse

https://github.com/rancher/docs/issues/3157

2021-04-07 15:46 UTC, davidnuzik requested changes

2021-04-07 15:46 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/requirements/_index.md
> +For details on which OS versions were tested with RKE2, refer to the [RKE documentation.](https://docs.rke2.io/install/requirements/#operating-systems)
I prefer linking to the OS Support matrix page.

2021-04-07 15:46 UTC, davidnuzik commented on content/rancher/v2.x/en/installation/requirements/_index.md
> +  - [RKE2](#rke2)
Should we call it RKE Government? I suppose not as the documentation here is not primarily intended for the public sector. Just thought I should raise this.

2021-04-07 15:48 UTC, davidnuzik commented
This PR is just for requirements section, so we already have a page to explain the installation process?

2021-04-07 16:26 UTC, catherineluse commented on content/rancher/v2.x/en/installation/requirements/_index.md
> +  - [RKE2](#rke2)
I think it's up to product management to decide. If it's RKE Government, I'll change it throughout, because we also mention RKE2 in the context of explaining what RancherD is.

2021-04-07 16:27 UTC, catherineluse commented
Yes, on [this page](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/ we list RKE2 as an option for preparing for the Helm chart install:

> 
> For help setting up a Kubernetes cluster, we provide these tutorials:
> 
>     RKE: For the tutorial to install an RKE Kubernetes cluster, refer to this page. For help setting up the infrastructure for a high-availability RKE cluster, refer to this page.
>     K3s: For the tutorial to install a K3s Kubernetes cluster, refer to this page. For help setting up the infrastructure for a high-availability K3s cluster, refer to this page.
>     RKE2: For the tutorial to install an RKE2 Kubernetes cluster, refer to this page. For help setting up the infrastructure for a high-availability RKE2 cluster, refer to this page.
>     Amazon EKS: To install Rancher on Amazon EKS, including how to install an ingress so that the Rancher server can be accessed, refer to this page.
> 

And it links to the RKE2 setup page here: https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-rke2-ha/

2021-04-07 16:32 UTC, catherineluse commented
The doc about setting up the RKE2 cluster for a Rancher install does specify how to do the ingress:

https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-rke2/#5-configure-nginx-to-be-a-daemonset

I can update the prerequisites/requirements page to link to that section as something you need to know for RKE2 installs.

2021-04-07 20:45 UTC, catherineluse commented on content/rancher/v2.x/en/installation/requirements/_index.md
> +For details on which OS versions were tested with RKE2, refer to the [RKE documentation.](https://docs.rke2.io/install/requirements/#operating-systems)
Ok, will do.

2021-04-08 15:52 UTC, rancher-max commented
@catherineluse Can we also mention that when doing this on an HA cluster, rke2-ingress-nginx should be deployed as a daemonset? This wording will probably need to be tweaked, but something like:

> When creating your rke2 cluster, you should deploy rke2-ingress-nginx as a daemonset to ensure your load balancer can successfully route traffic to all nodes. This can be done by placing the following file at `/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml` prior to starting the rke2 cluster:
> ```yaml
> apiVersion: helm.cattle.io/v1
> kind: HelmChartConfig
> metadata:
>   name: rke2-ingress-nginx
>   namespace: kube-system
> spec:
>   valuesContent: |-
>     controller:
>       kind: DaemonSet
>       daemonset:
>         useHostPort: true
> ```

This comes from https://github.com/rancher/rke2/issues/493 which technically now has more steps but will be fixed and validated in the next few days, so we want to just leave the documentation on this bit simple. cc @davidnuzik @ShylajaDevadiga

2021-04-12 19:15 UTC, ekristen commented
@rancher-max @catherineluse please also note that the documentation current suggests that you can provide a repository/tag but because of how the helm chart is written it will never work if `system_default_registry` is set, which it appears to be by default.

2021-04-23 22:05 UTC, catherineluse commented
@ekristen can you please raise a separate issue in rancher/docs about clarifying that?

2021-04-23 23:02 UTC, catherineluse commented
I've replaced the ingress config example in the RKE2 tutorial to match Max's example, because as Max explained, the existing example used an image that is not needed anymore.

2021-04-23 23:05 UTC, davidnuzik approved these changes

2021-04-23 23:21 UTC, merged