Update K3s security documentation.
rancher/docs pull request #3213
Opened 2021-04-22 23:27 UTC by briandowns

Update security page to indicate that CIS 1.5 and 1.6 are covered by
this section.

Add network policy to Hardening Guide that shows how to allow for DNS
traffic.

2021-04-22 23:34 UTC, MonzElmasry approved these changes

2021-04-23 00:13 UTC, Oats87 approved these changes

2021-04-23 00:29 UTC, brandond approved these changes

2021-04-23 16:11 UTC, dweomer approved these changes

2021-04-27 20:00 UTC, brandond approved these changes

2021-05-03 22:51 UTC, davidnuzik approved these changes
@catherineluse could this be merged in?

2021-05-04 18:53 UTC, davidnuzik requested changes
@briandowns actually Catherine pointed out that we should update https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5 near the bottom of that page - we should link to the k3s ones there. Could you make that small change at your next availability? After that I or Catherine can review then we can get this merged in.
If we get at least 1 LGTM after your change I requested here, we can just merge in.

2021-05-05 00:01 UTC, cjellick approved these changes

2021-05-05 00:02 UTC, cjellick commented
@catherineluse who merges docs prs? devs or you?
can this get merged?

2021-05-05 17:50 UTC, merged