Loggingv2
rancher/docs pull request #3225
Opened 2021-04-28 05:55 UTC by btat

https://github.com/rancher/docs/issues/3141
https://github.com/rancher/docs/issues/3222
https://github.com/rancher/docs/issues/3220
https://github.com/rancher/docs/issues/3221
https://github.com/rancher/docs/issues/3224

2021-04-28 18:32 UTC, catherineluse requested changes
Looks good. I had a few questions

2021-04-28 18:32 UTC, catherineluse commented on content/rancher/v2.5/en/logging/_index.md
> +Note that this is only affects Linux nodes.
this is only affects > This only affects 

also make sure you have two carriage returns after each paragraph throughout. Otherwise the website theme will add the next paragraph to the previous one

2021-04-28 18:32 UTC, catherineluse commented on content/rancher/v2.5/en/logging/_index.md
> +The following table summarizes the supported logging sources for each node type and the path to the logs:
Do we need an example of how to use the `additionalLoggingSources` configuration option?

2021-04-28 18:53 UTC, nickgerace commented on content/rancher/v2.5/en/logging/_index.md
> +The following table summarizes the supported logging sources for each node type and the path to the logs:
Hmmmm, the UI should do this automatically, but you would need to do it manually for the CLI.
```
# Example for an RKE cluster with CLI installation
--set additionalLoggingSources.rke.enabled=true
```

2021-04-28 18:53 UTC, nickgerace commented on content/rancher/v2.5/en/logging/_index.md
> +The following table summarizes the supported logging sources for each node type and the path to the logs:
A bit conflicted as a result

2021-04-28 18:58 UTC, nickgerace commented on content/rancher/v2.5/en/logging/_index.md
> +By default, Windows node logging will be enabled if the logging application is installed on a Windows cluster.
Only in the Cluster Explorer UI (unless that's implied?)

2021-04-28 18:58 UTC, nickgerace commented on content/rancher/v2.5/en/logging/_index.md
> +> **Note on syslog** As of Rancher v2.5.4, `syslog` is a supported output. However, this example still provides an overview on using unsupported plugins.
Did we delete the old unsupported output doc?

2021-04-28 18:58 UTC, nickgerace commented on content/rancher/v2.5/en/logging/_index.md
> +Moreover, the logging stack pods have a `nodeSelector` added to ensure that they *only* run on Linux nodes.
This should be changed to indicate that _most_ logging stack pods run on Linux only. Now, _some_ do run on Windows.

2021-04-28 18:58 UTC, nickgerace commented on content/rancher/v2.5/en/logging/_index.md
> +| GKE | ✓ | |
I'm a bit concerned about accidentally implying that Windows nodes only collect logs from RKE clusters. They can collect logs from _all_ clusters (since the "root" logger runs on every cluster). However, they only collect extra logs from RKE.

2021-04-29 19:27 UTC, catherineluse commented on content/rancher/v2.5/en/logging/_index.md
> +The following table summarizes the supported logging sources for each node type and the path to the logs:
Ah, ok. Since Denise indicated we shouldn't document CLI install steps because only the UI method is supported, I'd say we should leave it out. So I think what Billy had is fine.

2021-04-29 19:28 UTC, catherineluse commented on content/rancher/v2.5/en/logging/_index.md
> +> **Note on syslog** As of Rancher v2.5.4, `syslog` is a supported output. However, this example still provides an overview on using unsupported plugins.
Instead of deleting it, we usually create tabs for the whole section, with the newest version being the default tab and the 2.5.4 note preserved on the other one.

2021-04-30 22:54 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +Clusters with Windows workers support exporting logs from Linux nodes, but Windows node logs are currently unable to be exported.
Added sentence to mention this and links to the taints/tolerations section.

2021-04-30 22:56 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +| GKE | ✓ | |
Updated the wording

2021-04-30 22:56 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +To enable hosted Kubernetes providers as additional logging sources, go to **Cluster Exploere > Logging > Chart Options** and select the **Enable enhanced cloud provider logging** option.
Fixed

2021-04-30 22:58 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +When enabled, Rancher collects all node and control plane logs the provider has made available, which may vary between providers.
I think this is the feature from the meeting that we said we didn't want to put too much emphasis on so I didn't put it as a recommendation.

2021-04-30 22:59 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +Note that this is only affects Linux nodes.
Fixed

2021-04-30 23:01 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +By default, Windows node logging will be enabled if the logging application is installed on a Windows cluster.
Made it explicit UI is used

2021-04-30 23:01 UTC, btat commented on content/rancher/v2.5/en/logging/_index.md
> +Moreover, the logging stack pods have a `nodeSelector` added to ensure that they *only* run on Linux nodes.
Updated

2021-05-04 00:49 UTC, merged