Add SELinux docs
rancher/docs pull request #3237
Opened 2021-05-03 22:17 UTC by catherineluse

2021-05-04 00:13 UTC, cmurphy requested changes

2021-05-04 00:13 UTC, cmurphy commented on content/rancher/v2.5/en/security/selinux/_index.md
> +This RPM only contains policies for the [rancher-logging application,](https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-logging) but this is where additional policies for more Rancher f
>  but this is where additional policies for more Rancher feature applications will be added in the future.

This was a note aimed toward developers and support, I don't think it needs to be included here.

2021-05-04 00:13 UTC, cmurphy commented on content/rancher/v2.5/en/security/selinux/_index.md
> +If you are testing out an unreleased change, you can use the testing channel:
Do not include this section, this is for support

2021-05-04 00:13 UTC, cmurphy commented on content/rancher/v2.5/en/security/selinux/_index.md
> +# source /etc/os-release
This is not needed

2021-05-04 00:13 UTC, cmurphy commented on content/rancher/v2.5/en/security/selinux/_index.md
> +helm install logging rancher/rancher-logging --set global.seLinux.enabled=true
They would normally be doing this through Rancher, so instead of a `helm install` they should just be advised to change global.seLinux.enabled to true in the values.yaml when installing the chart.

2021-05-04 00:13 UTC, cmurphy commented on content/rancher/v2.5/en/security/selinux/_index.md
> +We provide two RPMs (Red Hat package managers) that enable Rancher products to function properly on SELinux-enforcing hosts: `rancher-selinux` and `rke2-selinux`.
```suggestion
We provide two RPMs (Red Hat packages) that enable Rancher products to function properly on SELinux-enforcing hosts: `rancher-selinux` and `rke2-selinux`.
```

RPM does stand for Red Hat Package Manager but an RPM is a package, not the package manager. It might be better not to expand the acronym at all.

2021-05-04 00:13 UTC, cmurphy commented on content/rancher/v2.5/en/security/selinux/_index.md
> +For CentOS 8, use this URL for the `baseurl`: https://rpm.rancher.io/rancher/production/centos/8/noarch
You could imitate the RKE2 docs and include the full `cat << EOF >` expression for both CentOS 7 and 8, rather than having them substitute the url, e.g.:

---

In order to use the RPM repository, on a CentOS 7 or RHEL 7 system, run the following bash snippet:

```
# cat << EOF > /etc/yum.repos.d/rancher.repo 
[rancher] 
name=Rancher 
baseurl=https://rpm.rancher.io/rancher/production/centos/7/noarch
enabled=1 
gpgcheck=1 
gpgkey=https://rpm.rancher.io/public.key 
EOF
```

In order to use the RPM repository, on a CentOS 8 or RHEL 8 system, run the following bash snippet:

```
# cat << EOF > /etc/yum.repos.d/rancher.repo 
[rancher] 
name=Rancher 
baseurl=https://rpm.rancher.io/rancher/production/centos/8/noarch
enabled=1 
gpgcheck=1 
gpgkey=https://rpm.rancher.io/public.key 
EOF
```

2021-05-04 14:29 UTC, catherineluse commented on content/rancher/v2.5/en/security/selinux/_index.md
> +This RPM only contains policies for the [rancher-logging application,](https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-logging) but this is where additional policies for more Rancher f
updated

2021-05-04 14:29 UTC, catherineluse commented on content/rancher/v2.5/en/security/selinux/_index.md
> +If you are testing out an unreleased change, you can use the testing channel:
removed

2021-05-04 14:30 UTC, catherineluse commented on content/rancher/v2.5/en/security/selinux/_index.md
> +# source /etc/os-release
removed

2021-05-04 14:35 UTC, catherineluse commented on content/rancher/v2.5/en/security/selinux/_index.md
> +helm install logging rancher/rancher-logging --set global.seLinux.enabled=true
updated

2021-05-04 14:37 UTC, catherineluse commented on content/rancher/v2.5/en/security/selinux/_index.md
> +For CentOS 8, use this URL for the `baseurl`: https://rpm.rancher.io/rancher/production/centos/8/noarch
updated

2021-05-04 20:37 UTC, cmurphy approved these changes

2021-05-04 21:18 UTC, merged

2021-05-05 19:06 UTC, capta1nk1rk commented on content/rancher/v2.5/en/security/selinux/_index.md
> +
May want to add how to verify the status of SELinux on your host with either getenforce or sestatus here as a quick verification check.

2021-05-05 21:46 UTC, bgulla commented on content/rancher/v2.5/en/security/selinux/_index.md
> +
+1