Add doc about lazy pulling and eStargz
rancher/docs pull request #3322
Opened 2021-06-08 07:29 UTC by ktock

Should be merged after https://github.com/k3s-io/k3s/pull/2936.

This PR adds doc that talks about the lazy pulling feature of k3s (https://github.com/k3s-io/k3s/pull/2936) and the why/how of using it.

2021-09-15 22:19 UTC, dweomer commented on content/k3s/latest/en/advanced/_index.md
> +With this configuration, you can perform lazy pulling for eStagz-formatted images.
```suggestion
With this configuration, you can perform lazy pulling for eStargz-formatted images.
```

2021-09-15 22:21 UTC, dweomer approved these changes
LGTM (minus one typo: https://github.com/rancher/docs/pull/3322/files#r709614444)

2021-09-15 22:26 UTC, brandond requested changes
Suggested some grammar fixes.

2021-09-15 22:26 UTC, brandond commented on content/k3s/latest/en/advanced/_index.md
> +Throughout the container lifecycle, pulling images is known as one of the time-consuming steps in the container lifecycle.
```suggestion
Pulling images is known as one of the time-consuming steps in the container lifecycle.
```

2021-09-15 22:26 UTC, brandond commented on content/k3s/latest/en/advanced/_index.md
> +Especially for large images, this technique can shorten the container startup latency.
```suggestion
To address this issue, k3s experimentally supports *lazy pulling* of image contents.
This allows k3s to start a container before the entire image has been pulled.
Instead, the necessary chunks of contents (e.g. individual files) are fetched on-demand. 
Especially for large images, this technique can shorten the container startup latency.
```

2021-09-15 22:26 UTC, brandond commented on content/k3s/latest/en/advanced/_index.md
> +For enabling lazy pulling, the target image needs to be formatted as [*eStargz*](https://github.com/containerd/stargz-snapshotter/blob/v0.6.4/docs/stargz-estargz.md).
```suggestion
To enable lazy pulling, the target image needs to be formatted as [*eStargz*](https://github.com/containerd/stargz-snapshotter/blob/v0.6.4/docs/stargz-estargz.md).
```

2021-09-15 22:26 UTC, brandond commented on content/k3s/latest/en/advanced/_index.md
> +eStargz is developed based on [stargz format proposed by Google CRFS project](https://github.com/google/crfs) but comes with practical features including content verification and performance optimiza
```suggestion
eStargz is developed based on the [stargz format proposed by Google CRFS project](https://github.com/google/crfs) but comes with practical features including content verification and performance optimization.
```

2021-09-16 01:07 UTC, ktock commented
@brandond Thank you for the suggestion. Fixed them.

2021-09-16 01:07 UTC, ktock commented on content/k3s/latest/en/advanced/_index.md
> +With this configuration, you can perform lazy pulling for eStagz-formatted images.
Thank you for the review. Fixed.

2021-09-16 01:48 UTC, brandond approved these changes

2021-09-17 18:46 UTC, brandond commented
@catherineluse can you merge?

2021-09-17 18:51 UTC, merged