Initial AKS provisioning docs
rancher/docs pull request #3342
Opened 2021-06-16 16:15 UTC by catherineluse

When contributing to docs, please don't update the content in the v2.x folder.
It's better to update the versioned docs, for example, the v2.5 or v2.6 docs.

This content in v2.x was separated into versioned documentation during the v2.5.8
release. The content relevant to Rancher versions before v2.5 went into the v2.0-v2.4
folder, while the content related to Rancher v2.5 went into the v2.5 folder.

We are trying to get the 2.x content to be removed from Google search results. The only
reason we haven't deleted it is because Google search results would lead to 404
errors if we deleted it.

2021-06-17 18:36 UTC, btat commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +The Azure interface allows users to specify whether a Primary Node Pool relies on either `system` (normally used for control planes) and `user` (what is most typically needed for Rancher).
```suggestion
The Azure interface allows users to specify whether a Primary Node Pool relies on either `system` (normally used for control planes) or `user` (what is most typically needed for Rancher).
```

2021-06-17 18:38 UTC, btat commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +System node pools that always require running nodes, so they cannot be scaled below one node. At least one system node pool is required.
```suggestion
System node pools always require running nodes, so they cannot be scaled below one node. At least one system node pool is required.
```

2021-06-17 18:47 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/aks/_index.md
> +The GKE provisioner can synchronize the state of a GKE cluster between Rancher and the provider. For an in-depth technical explanation of how this works, see [Syncing.]({{<baseurl>}}/rancher/v2.6/en/
```suggestion
The AKS provisioner can synchronize the state of an AKS cluster between Rancher and the provider. For an in-depth technical explanation of how this works, see [Syncing.]({{<baseurl>}}/rancher/v2.6/en/cluster-admin/editing-clusters/syncing)
```

2021-06-28 22:48 UTC, cmurphy requested changes

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- Support for node pools
Node pools existed before, the difference now is that we can add more than one.

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- For networking, a new field was added in the UI: Support Private Kubernetes Service
I don't see this, is this supposed to refer to "Enable Private Cluster" mentioned on line 10? This is also just awkward phrasing for this list.

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- Windows support was removed
Windows was never supported in v1, so it was not removed.

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +Create an SSH connection to the cluster nodes using these configuration options.
> Create an SSH connection

Most of the options below are not about SSH

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +Typically, AKS worker nodes do not get public IPs, regardless of whether the cluster is private, with some exceptions. In a private cluster, the control plane does not have a public endpoint.
> with some exceptions

I'm not aware of what the exceptions are, maybe add a link to the documentation explaining them?

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- Rancher needs to be running on the same [NAT](https://docs.microsoft.com/en-us/azure/virtual-network/nat-overview) as the AKS nodes.
Rancher management of AKS private clusters should work the same as it does for EKS https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/#private-only-api-endpoints

In short, it's possible for Rancher to connect to an AKS cluster when it is not running in the same VNet, you just need to run a manual registration step on the cluster.

2021-06-28 22:48 UTC, cmurphy commented on content/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/aks/_index.md
> +RBAC is required for AKS clusters that are registered or imported into Rancher.
I'm not sure why this is mentioned here, is it meant to replace the step about configuring "Member Roles" in the old version? Those are different things, "Member Roles" will always be available for Rancher clusters.

2021-06-29 07:17 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- For networking, a new field was added in the UI: Support Private Kubernetes Service
It was from the UI ticket:

> Need Networking section, which can adopt HTTP App Routing along with section for Security with a new field: Support Private Kubernetes Service Support.

I assumed it wasn't in the UI yet but would be added later. I guess it's probably redundant with line 10 so I've just deleted the line.

2021-06-29 07:18 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- Windows support was removed
removed bullet item

2021-06-29 07:21 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +Create an SSH connection to the cluster nodes using these configuration options.
I don't remember why I wrote that. Deleted

2021-06-29 07:32 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +Typically, AKS worker nodes do not get public IPs, regardless of whether the cluster is private, with some exceptions. In a private cluster, the control plane does not have a public endpoint.
I got it from the UI ticket -

> Private Cluster: Typically, AKS worker nodes do not get public IPs, regardless of whether it's a private cluster or not (there are exceptions). With a private cluster, the control plane does not have a public endpoint and Rancher agent would have to be deployed from a node in the same vnet to be able to connect with the apiserver. [3]
> [3] https://docs.microsoft.com/en-us/azure/aks/private-clusters#options-for-connecting-to-the-private-cluster

That link explains that you can enable a public FQDN for the cluster. Would enabling that FQDN provide another valid option for Rancher to connect to the API server of the private cluster? Or would mentioning that just complicate matters?

For now I've just changed it to simply:

> Typically, AKS worker nodes do not get public IPs, regardless of whether the cluster is private.

2021-06-29 07:43 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- Rancher needs to be running on the same [NAT](https://docs.microsoft.com/en-us/azure/virtual-network/nat-overview) as the AKS nodes.
For the EKS clusters, it references UI options for enabling/disabling the private cluster endpoint:

> If you enable private and disable public API endpoint access

Are there going to be the same options in the AKS cluster provisioning UI for enabling private access and disabling public access?

2021-06-29 07:46 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +- Rancher needs to be running on the same [NAT](https://docs.microsoft.com/en-us/azure/virtual-network/nat-overview) as the AKS nodes.
I've changed the section to:

> 
> Typically, AKS worker nodes do not get public IPs, regardless of whether the cluster is private. In a private cluster, the control plane does not have a public endpoint.
> 
> Rancher can connect to a private AKS cluster in one of two ways.
> 
> The first way to ensure that Rancher is running on the same [NAT](https://docs.microsoft.com/en-us/azure/virtual-network/nat-overview) as the AKS nodes.
> 
> The second way is to run a command on the cluster to register it with Rancher. Once the cluster is provisioned, you can run the displayed command anywhere you can connect to the cluster’s Kubernetes API. This command is displayed in a pop-up when you provision an AKS cluster with a private API endpoint enabled.
>

2021-06-29 07:59 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/aks/_index.md
> +RBAC is required for AKS clusters that are registered or imported into Rancher.
It's from the UI ticket -

> RBAC shouldn't require a UI since we need to have it enabled. That said, upon registering or importing a cluster without RBAC (i.e, RBA is disabled in the object coming into Rancher), we need to warn that it won't work without RBAC enabled -- this should be in the docs too. Registration likely will need a minor change for options & upgrades to exclude RBAC.

I interpreted that to mean that RBAC has to be enabled on the AKS side so that Rancher can manage RBAC for the cluster.

I've rephrased it like this:

> When provisioning an AKS cluster in the Rancher UI, RBAC cannot be disabled. If role-based access control is disabled for the cluster in AKS, the cluster cannot be registered or imported into Rancher.
> 
> Rancher can configure member roles for AKS clusters in the same way as any other cluster. For more information, see the section on [role-based access control.]({{<baseurl>}}/rancher/v2.6/en/admin-settings/rbac)

2021-06-29 11:56 UTC, mjura approved these changes
Few comments left besides this LGTM

2021-06-29 11:56 UTC, mjura commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +> The configuration information in this section assumes you have already set up a service principal for Rancher. For step-by-step instructions for how to set up the service principal, see [this secti
I think here is unneeded character `>`

2021-06-29 11:56 UTC, mjura commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +### Container Monitoring
New line before this header

2021-06-29 11:56 UTC, mjura commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +### Mode
New line below

2021-07-02 05:32 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +> The configuration information in this section assumes you have already set up a service principal for Rancher. For step-by-step instructions for how to set up the service principal, see [this secti
The `>` should be ok - it makes it appear like a blue-background note in the docs.

2021-07-02 05:44 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +### Container Monitoring
added new line

2021-07-02 05:45 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/_index.md
> +### Mode
added line

2021-07-02 21:45 UTC, cmurphy approved these changes

2021-07-09 06:12 UTC, merged