Add Keycloak (OIDC) page
rancher/docs pull request #3358
Opened 2021-06-24 15:53 UTC by btat

Closes #3256

2021-06-24 16:59 UTC, catherineluse commented
The renamed file breaks a link on this page https://rancher.com/docs/rancher/v2.5/en/admin-settings/authentication/

2021-06-24 17:13 UTC, btat commented
> 
> 
> The renamed file breaks a link on this page https://rancher.com/docs/rancher/v2.5/en/admin-settings/authentication/

The links on that page were updated on the v2.6 version.

2021-06-25 01:35 UTC, catherineluse requested changes

2021-06-25 01:35 UTC, catherineluse commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +1. Complete the **Configure a Keycloak OIDC account** form.
A tech writer from ADP taught me that it's a best practice to separate reference material from instructions. I think it's the cleanest way to do it because when config options are separated from instructions, we have more space to explain them, and it prevents the instructions from getting unwieldy. Can you please create a separate Configuration section for the table with the explanations of each configuration field? Then in step 3, just say that if you need help refer to the table.

2021-06-25 01:35 UTC, catherineluse commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +When you fill the **Configure a Keycloak OIDC account** form and click on **Enable**, your are not redirected to your IdP.
you are not redirected

2021-06-25 01:35 UTC, catherineluse commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +### Changes to Keycloak
"Changes to Keycloak" kind of makes it sound like it's about changes in Rancher v2.6. The headings could be something like "1. Reconfigure Keycloak" and "2. Reconfigure Rancher"

2021-06-25 21:29 UTC, btat commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +1. Complete the **Configure a Keycloak OIDC account** form.
Updated in https://github.com/rancher/docs/pull/3358/commits/2da106151e2d673f5aebcdf6f4f8df797085fb4e. Moved the table into a separate Configuration Reference section and pointed to it in this step. Same change made on the 2.6 SAML version and the 2.5 SAML version.

2021-06-25 21:31 UTC, btat commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +When you fill the **Configure a Keycloak OIDC account** form and click on **Enable**, your are not redirected to your IdP.
Updated. Same change made on the 2.6 SAML version and the 2.5 SAML version as well.

2021-06-25 21:31 UTC, btat commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +### Changes to Keycloak
Updated. Same change made on the 2.6 SAML version and the 2.5 SAML version as well.

2021-06-25 21:58 UTC, catherineluse commented
LGTM

2021-07-23 00:48 UTC, brendarearden commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +    `Add to ID token` | `ON`
Can we change the setting value to `Add to ID token: off`,  `Add to access token: off`. This way we aren't adding additional information to tokens that we don't need to.  

Can we also add two additional mappers:

`Name:Client Audience; Mapper Type: Audience; Included Client Audience: <name of your client>; Add to access token: on`

and 

`Name:Full Group Path; Mapper Type: Group Membership; Token Claim Name: full_group_path; Full group path: on; Add to userinfo: on`

2021-07-23 21:03 UTC, btat commented on content/rancher/v2.6/en/admin-settings/authentication/keycloak-oidc/_index.md
> +    `Add to ID token` | `ON`
Mapper fields updated and additional mappers added.

2021-07-28 22:20 UTC, izaac commented
Can we add the specific built-ins here? 

`Add other "Builtin Protocol Mappers" as needed.`

2021-07-28 22:58 UTC, btat commented
> 
> 
> Can we add the specific built-ins here?
> 
> `Add other "Builtin Protocol Mappers" as needed.`

I don't recall any of the built-in mappers as being required, so it may be less confusing to just drop this line?

2021-08-04 22:17 UTC, merged