Document Rancher image vulnerability scanning
rancher/docs pull request #3364
Opened 2021-06-26 17:13 UTC by catherineluse

2021-06-28 21:58 UTC, rmweir requested changes
I may have missed it but if not already included, we should state that the publish CVE's reflect the latest development version of 2.6 and 2.6 charts.

2021-06-28 21:58 UTC, rmweir commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +The CVE scan includes all images shipped with Rancher releases, which are listed in the `images.txt` file included with every release. This list includes all core Rancher components and features.
Could mentioned here that the image-sources.txt also includes that images along with an annotation indicating what rancher feature uses the image.

2021-06-28 21:58 UTC, rmweir commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +The CVE scan report lists any image containing a CVE that is ranked by our scanning tool with a rating of `high` or above.
High is always seen fully capitalized so can change for consistency. To clarify, only one rating is above high, critical, so you could just say HIGH and CRITICAL.
```suggestion
The CVE scan report lists any image containing a CVE that is ranked by our scanning tool with a rating of `HIGH` or above.
```

2021-06-28 21:58 UTC, rmweir commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +The report is provided in CSV format with each Rancher release. It is also available on a publicly accessible web page. This web page is updated weekly.
It's daily now. Should also include that the CSV info included on release is from the day of release and is likely to become outdated as new CVE's for an image version are detected.
```suggestion
The report is provided in CSV format with each Rancher release. It is also available on a publicly accessible web page. This web page is updated daily.
```

2021-06-28 21:58 UTC, rmweir commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +  - For Rancher images, the status in the Rancher pipeline is used
There is other info as well but it is subject to change so I think this covers ones that are likely to stay.

2021-06-28 21:58 UTC, rmweir commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +As new CVEs are reported, or new images with high-level CVEs are brought into the pipeline, the Rancher team is automatically alerted and triages each vulnerability.
```suggestion
As new CVEs are reported, or new images with high or critical severity CVEs are brought into the pipeline, the Rancher team is automatically alerted and triages each vulnerability.
```

2021-06-28 21:58 UTC, rmweir commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +- **Vulnerabilities that can be fixed:** These results include vulnerabilities in Rancher projects or upstream packages that need to be updated, and that are within our ability to fix. They are addre
@cbron do we want to state our process like this? I feel like this may be interpreted as some sort of guarantee when in reality is just loosely the process we are following internally atm.

2021-06-29 07:11 UTC, catherineluse commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +The CVE scan includes all images shipped with Rancher releases, which are listed in the `images.txt` file included with every release. This list includes all core Rancher components and features.
changed to:

> The CVE scan includes all images shipped with Rancher releases, which are listed in the `rancher-images.txt` file included with every release. This list includes all core Rancher components and features.
> 
> The `rancher-images-sources.txt` file also includes the images, along with an annotation indicating what Rancher feature uses the image.

2021-07-01 22:07 UTC, cbron requested changes

2021-07-01 22:07 UTC, cbron commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +- Pipelines were deprecated as of Rancher v2.5 and should no longer be used. We recommend handling Git-based deployment pipelines with  [Fleet.]({{<baseurl>}}/rancher/v2.6/en/deploy-across-clusters/f
Pipelines needs note that it is getting critical CVE's fixes only

2021-07-02 05:23 UTC, catherineluse commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +- **Vulnerabilities that can be fixed:** These results include vulnerabilities in Rancher projects or upstream packages that need to be updated, and that are within our ability to fix. They are addre
condensed per Caleb's note https://rancher.slack.com/archives/C01DK1CKSUB/p1625176711048200

2021-07-02 05:24 UTC, catherineluse commented on content/rancher/v2.6/en/security/cve-scans/_index.md
> +- Pipelines were deprecated as of Rancher v2.5 and should no longer be used. We recommend handling Git-based deployment pipelines with  [Fleet.]({{<baseurl>}}/rancher/v2.6/en/deploy-across-clusters/f
updated

2021-07-02 05:30 UTC, catherineluse commented
I believe the only thing remaining is to add the URL to the place where the scan report will be published.

2021-07-09 06:51 UTC, catherineluse commented
Closing this issue, opening a separate issue to track the last piece - adding the scan report URL.

2021-07-09 06:51 UTC, merged