Respond to feedback on cluster template docs
rancher/docs pull request #3485
Opened 2021-09-02 00:40 UTC by catherineluse

This PR is a follow up to the feedback on this other PR: https://github.com/rancher/docs/pull/3482/files
https://github.com/rancher/docs/issues/3258

2021-09-02 04:21 UTC, slickwarren requested changes

2021-09-02 04:21 UTC, slickwarren commented on content/rancher/v2.6/en/admin-settings/cluster-templates/_index.md
> +
one more prerequisite: fleet repos must follow a separate guideline: http://fleet.rancher.io/gitrepo-structure/. For rke2 cluster templates, that means adding a fleet.yaml file to their repo.

2021-09-02 04:21 UTC, slickwarren commented on content/rancher/v2.6/en/admin-settings/cluster-templates/_index.md
> +**Result:** After Rancher provisions the new cluster, it is managed by Fleet. You can configure any options through the UI if the cluster template has options for the user to choose from.
`You can configure any options through the UI if the cluster template has options for the user to choose from.` This is not possible for fleet, afaik. This is why the values.yaml must all be configured in the repo, as the user can't manipulate them when installed with fleet in rancher.

2021-09-02 04:21 UTC, slickwarren commented on content/rancher/v2.6/en/admin-settings/cluster-templates/_index.md
> +An admin with access to the `local` cluster can also remove a cluster deployed via cluster templates through the **Apps & Marketplace > Installed Apps** page. This user can also update any clusters u
I think this part belongs in the section below; this is another way to uninstall cluster templates.

2021-09-09 02:09 UTC, catherineluse commented on content/rancher/v2.6/en/admin-settings/cluster-templates/_index.md
> +
updated

2021-09-09 02:10 UTC, catherineluse commented on content/rancher/v2.6/en/admin-settings/cluster-templates/_index.md
> +**Result:** After Rancher provisions the new cluster, it is managed by Fleet. You can configure any options through the UI if the cluster template has options for the user to choose from.
updated

2021-09-09 02:14 UTC, catherineluse commented on content/rancher/v2.6/en/admin-settings/cluster-templates/_index.md
> +An admin with access to the `local` cluster can also remove a cluster deployed via cluster templates through the **Apps & Marketplace > Installed Apps** page. This user can also update any clusters u
updated

2021-09-09 17:17 UTC, slickwarren approved these changes

2021-09-09 21:37 UTC, merged