Documented ECR plugin in RKE
rancher/docs pull request #3486
Opened 2021-09-02 16:42 UTC by jtravee

Closes #3401

2021-09-02 17:31 UTC, btat commented on content/rke/latest/en/config-options/private-registries/_index.md
> +There are two ways in which to provide ECR credentials to set up your ECR private registry: using an instance profile or adding a configuration snippet, which are hard-coded credentials in environmen
```suggestion
There are two ways in which to provide ECR credentials to set up your ECR private registry: using an instance profile or adding a configuration snippet, which are hard-coded credentials in environment variables for the `kubelet` and credentials under the `credentialPlugin`. 
```

2021-09-02 19:26 UTC, btat requested changes

2021-09-02 19:26 UTC, btat commented on content/rke/latest/en/config-options/private-registries/_index.md
> +  - **Instance Profile**: An instance profile is the preferred and more secure approach to provide ECR credentials (when running in EC2, etc.). The instance profile will be autodetected and use these
Should include link/info on configuring an instance profile with ECR permissions

The Go AWS SDK bit seems like an implementation detail, do we usually include such things? @catherineluse

2021-09-02 19:46 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/editing-clusters/rke-config-reference/_index.md
> +To learn how to set up an **ECR private registry** and for more information on the private registry for components applied during the provisioning of the cluster, see the [RKE documentation on privat
The link goes to a page about all the private registries you can set up in rke, not just ECR registries. so maybe it can say something like

> For more information on setting up a private registry for components applied during the provisioning of the cluster, see the [RKE documentation on private registries]({{<baseurl>}}/rke/latest/en/config-options/private-registries/).
> 
> Rancher 2.6 introduced the ability to configure ECR registries for RKE clusters.

2021-09-02 19:48 UTC, catherineluse commented on content/rke/latest/en/config-options/private-registries/_index.md
> +  - **Instance Profile**: An instance profile is the preferred and more secure approach to provide ECR credentials (when running in EC2, etc.). The instance profile will be autodetected and use these
I agree with linking to the upstream AWS docs about instance profiles/ECR permissions. I also agree with removing the parenthetical about the Go AWS SDK.

2021-09-07 05:05 UTC, ibrokethecloud approved these changes

2021-09-07 20:46 UTC, btat approved these changes

2021-09-07 20:50 UTC, merged