k3s version v1.21.4+k3s1 (3e250fdb) go version go1.16.6 does not crea…
rancher/docs pull request #3514
Opened 2021-09-14 04:33 UTC by ProjectInitiative

…te /server/db/snapshots, instead it is now located at /var/lib/rancher/k3s/server/db

2021-09-14 04:35 UTC, ProjectInitiative commented
Created on wrong branch

2021-09-14 04:40 UTC, ProjectInitiative commented
After re-reading the contributing guidelines, unclear where to request changes to none versioned rancher docs (i.e. k3s)

2021-09-14 16:07 UTC, btat commented
Hi @ProjectInitiative, the info mentioned in the guidelines are not applicable to K3s and RKE, which do not have versioned documentation. What you have now is good as it is.

I will update the PR template so it's more clear.

2021-09-14 16:08 UTC, ProjectInitiative commented
> Hi @ProjectInitiative, the info mentioned in the guidelines are not applicable to K3s and RKE, which do not have versioned documentation. What you have now is good as it is.
> 
> I will update the PR template so it's more clear.

I appreciate the information! Thank you for the update.

2021-09-17 18:58 UTC, brandond commented
Yeah, this should have been documented as `$DATADIR/server/db/FOO`, as the /var/lib/rancher/k3s prefix can be changed by setting the --data-dir flag. Maybe just call that out as well?

2021-11-04 16:37 UTC, brandond requested changes

2021-11-04 16:37 UTC, brandond commented on content/k3s/latest/en/backup-restore/_index.md
> +The snapshot directory defaults to `${data-dir}/server/db/snapshots`. Note that the `/var/lib/rancher/k3s` prefix can be changed by setting the `--data-dir` flag. This prefix is currently omitted fro
If this PR adds it to both the places it was missing from, we can probably drop that bit.

2021-11-05 15:34 UTC, jtravee commented on content/k3s/latest/en/backup-restore/_index.md
> +The snapshot directory defaults to `${data-dir}/server/db/snapshots`. Note that the `/var/lib/rancher/k3s` prefix can be changed by setting the `--data-dir` flag. This prefix is currently omitted fro
Removed phrase, thanks!

2021-11-05 21:34 UTC, brandond requested changes
One last nit on the wording. Thanks for taking the time to get this straightened out!

2021-11-05 21:34 UTC, brandond commented on content/k3s/latest/en/backup-restore/_index.md
> +The snapshot directory defaults to `${data-dir}/server/db/snapshots`. Note that the `/var/lib/rancher/k3s` prefix can be changed by setting the `--data-dir` flag.
```suggestion
The snapshot directory defaults to `${data-dir}/server/db/snapshots`. The data-dir value defaults to `/var/lib/rancher/k3s`, and can be changed by setting the `--data-dir` flag.
```

2021-11-05 21:51 UTC, jtravee commented on content/k3s/latest/en/backup-restore/_index.md
> +The snapshot directory defaults to `${data-dir}/server/db/snapshots`. Note that the `/var/lib/rancher/k3s` prefix can be changed by setting the `--data-dir` flag.
Thanks as always for the feedback!

2021-11-05 22:08 UTC, brandond approved these changes

2021-11-08 13:43 UTC, merged