Provided example yaml and kubectl commands on how to configure additional monitoring roles
rancher/docs pull request #3518
Opened 2021-09-14 22:34 UTC by jtravee

Closes #3335

2021-09-14 23:20 UTC, btat requested changes

2021-09-14 23:20 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +```
The `Role` examples YAMLs don't need to be added since the Monitoring chart already creates them so the user won't need to use these examples.

2021-09-14 23:20 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +  ```
The example YAMLs are provided but the part on how to use them is missing (kubectl commands).

Also these examples use roles that aren't on the table from https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/rbac/#additional-monitoring-roles so it could be confusing for users.

We should verify that table is update and/or adjust the example accordingly.

2021-09-15 16:28 UTC, catherineluse commented
I agree with Billy that the roles shouldn't be included, only the examples of how to actually connect them with users. Here's the Slack context that originated the issue https://rancher.slack.com/archives/C6U4L2DS9/p1623697081110000

2021-09-16 18:58 UTC, btat requested changes

2021-09-16 18:58 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +kind: RoleBinding
Description says this is supposed to be a ClusterRoleBinding (in which case it's not namespaced)

2021-09-16 18:58 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +  * **ClusterRoles:** `kubectl apply -f monitoring-admin-cluster-role-binding.yaml`
In the earlier parts where you show the YAML file, it should be called out the example files are named using the names from these commands. Otherwise, there's no context as to why these filenames are being used here.

2021-09-16 18:58 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +  name: "" # user's name, e.g. u-<random-string>. This can be found via kubectl get users -A
Since actual examples values are used for other fields, an actual example value should be used here instead of leaving it blank. The `Note that you will need to...` sentence above will then need to be changed.

2021-09-16 18:58 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +### Assigning Roles and ClusterRoles to Users with kubectl
"Users and Groups" or just drop the "to Users" part

2021-09-20 22:39 UTC, merged