[Rancher2] Document Harvester integration features
rancher/docs pull request #3534
Opened 2021-09-21 21:17 UTC by jtravee

Closes #3496; waiting for Harvester List Page navigation to be finalized to document this piece. 

See https://github.com/rancher/dashboard/issues/3465- Harvester Integration- Feature Flag Support and https://github.com/rancher/dashboard/issues/3466- Harvester Integration- Harvester List Page

Reference: https://rancher.com/docs/rancher/v2.6/en/installation/resources/feature-flags/

2021-09-21 21:29 UTC, btat requested changes

2021-09-21 21:29 UTC, btat commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +- `harvester`: This feature flag is available in v2.6.1. It is used to manage access to the Harvester list page where users can navigate directly to Harvester host clusters and have the ability to im
Suggest changing "available in" to "available starting in"/ "available as of" so that/"available from" so that the  sentence will still be applicable when/if future versions are released.

2021-09-27 17:07 UTC, catherineluse commented
I don't know enough to review this PR. However @slickwarren tested it - I believe he could review when it's ready.

2021-09-27 19:03 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +- `harvester`: This feature flag is available in v2.6.1. It is used to manage access to the Harvester list page where users can navigate directly to Harvester host clusters and have the ability to im
Added rewording as suggested.

2021-09-27 22:15 UTC, slickwarren requested changes

2021-09-27 22:15 UTC, slickwarren commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +- `harvester`: This feature flag is available starting in v2.6.1. It is used to manage access to the Harvester list page where users can navigate directly to Harvester clusters and access the Harvest
I would change `harvester list page` to the name in dashboard, `Virtualization Management page`

2021-09-27 22:51 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +- `harvester`: This feature flag is available starting in v2.6.1. It is used to manage access to the Harvester list page where users can navigate directly to Harvester clusters and access the Harvest
Done, thanks!

2021-09-28 03:56 UTC, slickwarren approved these changes

2021-09-28 18:45 UTC, btat approved these changes

2021-09-28 18:46 UTC, merged