Documented updates to feature flag list and table
rancher/docs pull request #3548
Opened 2021-09-24 13:57 UTC by jtravee

Closes #3546

Not including Harvester (https://github.com/rancher/docs/pull/3534) and RKE2 (https://github.com/rancher/docs/pull/3545) for RKE2 feature flag updates.

2021-09-24 18:27 UTC, btat requested changes
Features that are no longer available should be removed from the table as well.

2021-09-24 18:27 UTC, btat commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +- `fleet`: The previous `fleet` feature flag is now required to be enabled as the fleet capabilities are leveraged within the new provisioning framework. If you had this feature flag disabled in earl
```suggestion
- `fleet`: The previous `fleet` feature flag is now required to be enabled as the Fleet capabilities are leveraged within the new provisioning framework. If you had this feature flag disabled in earlier versions, upon upgrading to Rancher v2.6, the flag will automatically be enabled. See this [page]({{<baseurl>}}/rancher/v2.6/en/deploy-across-clusters/fleet) for more information.
```

2021-09-24 18:27 UTC, btat commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +| `multi-cluster-management` | `false` | GA* | v2.x | |
v2.x is too broad of a range. We should at least list the minor version.

2021-09-24 19:33 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +- `fleet`: The previous `fleet` feature flag is now required to be enabled as the fleet capabilities are leveraged within the new provisioning framework. If you had this feature flag disabled in earl
Made edits as recommended.

2021-09-24 20:47 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/feature-flags/_index.md
> +| `multi-cluster-management` | `false` | GA* | v2.x | |
Updated to 2.5.0

2021-09-28 18:43 UTC, btat commented
@jtravee your commit https://github.com/rancher/docs/pull/3548/commits/b8cc2cb2889ca217839676a49980e5ed1f915e46 added some unrelated (azure cloud provider) content to this PR

2021-09-29 01:24 UTC, merged