Added Rancher Logging instructions for K3s
rancher/docs pull request #3586
Opened 2021-10-04 18:55 UTC by jtravee

Closes #3349

2021-10-05 23:02 UTC, btat requested changes

2021-10-05 23:02 UTC, btat commented on content/k3s/latest/en/advanced/_index.md
> +helm install --create-namespace -n cattle-logging-system rancher-logging --se tadditionalLoggingSources.k3s.enabled=true rancher-charts/rancher-logging
```suggestion
helm install --create-namespace -n cattle-logging-system rancher-logging --set additionalLoggingSources.k3s.enabled=true rancher-charts/rancher-logging
```

2021-10-05 23:02 UTC, btat commented on content/k3s/latest/en/advanced/_index.md
> +Rancher logging for K3s can be installed without using Rancher. The following instructions should be executed to do so:
A link (maybe to the Helm chart?) should so users know where to go to find out more about Rancher logging.

2021-10-06 14:12 UTC, jtravee commented on content/k3s/latest/en/advanced/_index.md
> +Rancher logging for K3s can be installed without using Rancher. The following instructions should be executed to do so:
Added link.

2021-10-06 16:10 UTC, merged