Dockershim update
rancher/docs pull request #3601
Opened 2021-10-08 16:45 UTC by btat

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2021-10-08 19:05 UTC, cloudnautique requested changes
make sure the FAQ in 2.5 and 2.6 are consistent.

2021-10-08 19:05 UTC, cloudnautique commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +
Lets call out that "going forward" means beyond the removal of in-tree in Kubernetes 1.24.

2021-10-08 19:05 UTC, cloudnautique commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +
Lets also say that it needs to be using the extrernal shim before upgrading to the release that removes it currently 1,24.

2021-10-08 19:05 UTC, cloudnautique commented on content/rancher/v2.6/en/installation/requirements/dockershim/_index.md
> +RKE clusters now support the external Dockershim to continue leveraging Docker as the CRI runtime. We now implement the upstream open source community Dockershim announced by [Mirantis and Docker](ht
Open source community external Dockershim.

2021-10-08 19:05 UTC, cloudnautique commented on content/rancher/v2.6/en/installation/requirements/dockershim/_index.md
> +This new component that replaces the old Dockershim, called `cri-dockerd`, will need to enabled using the option listed below. Note that to use this option will require at least Kubernetes 1.21.
Rephrase.

2021-10-08 19:05 UTC, cloudnautique commented on content/rancher/v2.6/en/installation/requirements/dockershim/_index.md
> +A: Rancher is exploring the possibility of an in-place upgrade path. Alternatively you can always migrate workloads from one cluster to another using kubectl.
Today, you can stand up a new cluster and migrate workloads to a new RKE2 cluster that uses containerd. Rancher is exploring the possibility of an in-place upgrade path

2021-10-08 20:54 UTC, btat commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +RKE clusters now support the external Dockershim to continue leveraging Docker as the CRI runtime. We now implement the upstream open source community Dockershim announced by [Mirantis and Docker](ht
Does this work? (To avoid potential confusion with the RKE version itself)

```suggestion
RKE clusters, starting with Kubernetes 1.21, now support the external Dockershim to continue leveraging Docker as the CRI runtime. We now implement the upstream open source community Dockershim announced by [Mirantis and Docker](https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/) to ensure RKE clusters can continue to leverage Docker.
```

2021-10-08 20:54 UTC, btat commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +This new component that replaces the old Dockershim, called `cri-dockerd`, will need to enabled using the option listed below. Note that to use this option will require at least Kubernetes 1.21.
Removed the bit about K8s 1.21 since that's now mentioned earlier on line 8.

```suggestion
To enable the external Dockershim, configure the following option.
```

2021-10-08 20:54 UTC, btat commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +A The upstream support of Dockershim begins for RKE in Kubernetes 1.21. You will need to be on a version of Rancher that supports RKE 1.21. See our support matrix for details.
How's this?

```suggestion
The upstream support of Dockershim begins for RKE in Kubernetes 1.21. You will need to be on Rancher 2.6 or above to have support for RKE with Kubernetes 1.21. See our [support matrix](https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.6.0/) for details.
```

2021-10-08 20:54 UTC, btat commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +The Dockershim is the CRI compliant layer between the Kubelet and the Docker daemon. As part of the Kubernetes 1.20 release, the [deprecation of the in-tree Dockershim was announced](https://kubernet
```suggestion
The Dockershim is the CRI compliant layer between the Kubelet and the Docker daemon. As part of the Kubernetes 1.20 release, the [deprecation of the in-tree Dockershim was announced](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/). Removal is currently scheduled for Kubernetes 1.24. For more information on the deprecation and its timelines, see the [Kubernetes Dockershim Deprecation FAQ](https://kubernetes.io/blog/2020/12/02/dockershim-faq/#when-will-dockershim-be-removed).
```

2021-10-08 20:54 UTC, btat commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +For users looking to use another container runtime, Rancher has the edge-focused K3s and datacenter-focused RKE2 Kubernetes distributions that use containerd as the default runtime. Imported RKE2 and
How's this?

```suggestion
For users looking to use another container runtime, Rancher has the edge-focused K3s and datacenter-focused RKE2 Kubernetes distributions that use containerd as the default runtime. Imported RKE2 and K3s Kubernetes clusters can then be upgraded and managed through Rancher even after the removal of in-tree Dockershim in Kubernetes 1.24.
```

2021-10-08 20:54 UTC, btat commented on content/rancher/v2.6/en/faq/dockershim/_index.md
> +A. The version of Dockershim in RKE with Kubernetes 1.20 will continue to work and it is not deprecated until a later release. For information on the timeline, see the [Kubernetes Dockershim Deprecat
How's this?

```suggestion
A. The version of Dockershim in RKE with Kubernetes 1.20 will continue to work and is not scheduled for removal upstream until Kubernetes 1.24. It will only emit a warning of its future deprecation, which Rancher has mitigated in RKE with Kubernetes 1.21. You can plan your upgrade to Kubernetes 1.21 as you would normally, but should consider enabling the external Dockershim by Kubernetes 1.22. The external Dockershim will need to be enabled before upgrading to Kubernetes 1.24, at which point the existing implementation will be removed.

For more information on the deprecation and its timeline, see the [Kubernetes Dockershim Deprecation FAQ](https://kubernetes.io/blog/2020/12/02/dockershim-faq/#when-will-dockershim-be-removed).
```

2022-02-14 23:59 UTC, btat commented on content/rancher/v2.6/en/installation/requirements/dockershim/_index.md
> +This new component that replaces the old Dockershim, called `cri-dockerd`, will need to enabled using the option listed below. Note that to use this option will require at least Kubernetes 1.21.
```suggestion
To enable the external Dockershim, configure the following option.
```

2022-02-14 23:59 UTC, btat commented on content/rancher/v2.6/en/installation/requirements/dockershim/_index.md
> +A: Rancher is exploring the possibility of an in-place upgrade path. Alternatively you can always migrate workloads from one cluster to another using kubectl.
```suggestion
A: Today, you can stand up a new cluster and migrate workloads to a new RKE2 cluster that uses containerd. Rancher is exploring the possibility of an in-place upgrade path. 
```

2022-02-15 00:00 UTC, btat commented on content/rancher/v2.6/en/installation/requirements/dockershim/_index.md
> +RKE clusters now support the external Dockershim to continue leveraging Docker as the CRI runtime. We now implement the upstream open source community Dockershim announced by [Mirantis and Docker](ht
```suggestion
RKE clusters now support the external Dockershim to continue leveraging Docker as the CRI runtime. We now implement the upstream open source community external Dockershim announced by [Mirantis and Docker](https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/) to ensure RKE clusters can continue to leverage Docker.
```

2022-02-15 00:04 UTC, merged