Added documentation for ACE support for imported RKE2/K3S clusters
rancher/docs pull request #3672
Opened 2021-11-10 23:20 UTC by jtravee

Closes #3612.

References:
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/registered-clusters/
https://rancher.com/docs/rancher/v2.6/en/overview/architecture-recommendations/#architecture-for-an-authorized-cluster-endpoint
https://rancher.com/docs/rancher/v2.6/en/overview/architecture/#4-authorized-cluster-endpoint

2021-11-12 22:15 UTC, btat requested changes

2021-11-12 22:15 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +# ACE Support for RKE2 and K3s Clusters
ACE isn't a common acronym so we should use the full form.

```suggestion
# Authorized Cluster Endpoint Support for RKE2 and K3s Clusters
```

2021-11-12 22:15 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +- [ACE Support for RKE2 and K3s Clusters](#ace-support-for-rke2-and-k3s-clusters)
ACE isn't a common acronym so we should use the full form.

```suggestion
- [Authorized Cluster Endpoint Support for RKE2 and K3s Clusters](#ace-support-for-rke2-and-k3s-clusters)
```

2021-11-12 22:15 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +> **Notice:**
Maybe stick with `Note` for consistency with the rest of the docs.

2021-11-12 22:15 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +  - `sudo systemctl start {rke2,k3s}-server`
These should be put into one code block

2021-11-12 22:15 UTC, btat commented on content/rancher/v2.6/en/overview/architecture-recommendations/_index.md
> +As of Rancher v2.6.3, ACE support is available for registered RKE2 and K3s clusters. To view the manual steps to perform on the downstream cluster to enable the ACE, click [here]({{<baseurl>}}/v2.6/e
The ACE acronym isn't defined/established on this page.

2021-11-15 14:29 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +> **Notice:**
Updated.

2021-11-15 14:29 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +  - `sudo systemctl start {rke2,k3s}-server`
Updated.

2021-11-15 14:29 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +- [ACE Support for RKE2 and K3s Clusters](#ace-support-for-rke2-and-k3s-clusters)
Updated.

2021-11-15 14:49 UTC, jtravee commented on content/rancher/v2.6/en/overview/architecture-recommendations/_index.md
> +As of Rancher v2.6.3, ACE support is available for registered RKE2 and K3s clusters. To view the manual steps to perform on the downstream cluster to enable the ACE, click [here]({{<baseurl>}}/v2.6/e
Added clarification for acronym, ty!

2021-11-15 18:39 UTC, btat approved these changes

2021-11-23 00:02 UTC, thedadams requested changes

2021-11-23 00:02 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +###### **Manual steps to be taken on the downstream cluster to enable ACE:**
These instructions should indicate that these manual steps only need to be taken on the control plane nodes of the downstream cluster. Also, the manual steps need to be taken on each control plane node.

2021-11-23 15:32 UTC, thedadams approved these changes

2021-11-25 19:05 UTC, merged