Update k3s HA install to cover changes with the token
rancher/docs pull request #3673
Opened 2021-11-11 02:00 UTC by dkeightley

In recent k3s versions, [the token must](https://github.com/k3s-io/k3s/releases/tag/v1.19.13%2Bk3s1) be used to join additional server nodes, updated to add suggests reflecting more prominent use of the token.

As additional server nodes are needed in an HA install, added a dedicated step for adding the additional nodes to avoid confusion.

2021-11-11 15:45 UTC, jtravee requested changes

2021-11-11 15:45 UTC, jtravee commented on content/k3s/latest/en/installation/ha/_index.md
> +When running the `k3s server` command on these nodes, you must set the `datastore-endpoint` parameter so that K3s knows how to connect to the external datastore. The `token` parameter can also be use
```suggestion
When running the `k3s server` command on these nodes, you must set the `datastore-endpoint` parameter so that K3s knows how to connect to the external datastore. The `token` parameter can also be used to set a deterministic token when adding nodes. When empty, this token will be generated automatically for further use.
```

2021-11-11 19:55 UTC, jtravee approved these changes

2021-11-17 15:35 UTC, dweomer approved these changes

2021-11-17 20:16 UTC, dkeightley commented
Oops, sorry! Didn't refresh before adding another reviewer, please merge if desired

2021-11-22 18:43 UTC, brandond approved these changes

2021-11-22 18:47 UTC, merged