Added option E to docker single node install for 2.6
rancher/docs pull request #3682
Opened 2021-11-15 15:59 UTC by nunix

Closes #3662

2021-11-15 17:14 UTC, jtravee requested changes

2021-11-15 17:14 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +- Use the `--no-cacerts` as argument to the container to disable the default CA certificate generated by Rancher.
Recommend deleting here and moving this (as shown in line 158) to the initial directions to give context. This way, when you say "run the Docker command below", the actual command immediately follows, rather than additional information before the command.

2021-11-15 17:14 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +Privileged access is [required.](#privileged-access-for-rancher)
Recommend deleting here and moving this (as shown in line 158) to the initial directions to give context. This way, when you say "run the Docker command below", the actual command immediately follows, rather than additional information before the command.

2021-11-15 18:28 UTC, nickgerace commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +- Use the `--no-cacerts` as argument to the container to disable the default CA certificate generated by Rancher.
+1

2021-11-15 18:28 UTC, nickgerace commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +Log into your host machine and run the Docker command below:
nit: We could possibly indicate that this doesn't have to be a local laptop or workstation. It could also be a cloud VM as well. What are your thoughts?

2021-11-15 18:28 UTC, nickgerace commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +Privileged access is [required.](#privileged-access-for-rancher)
+1

2021-11-15 18:28 UTC, nickgerace commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +- You will use `--no-cacerts` in the argument to disable the default CA certificate generated by Rancher. Note that privileged access is [required.](#privileged-access-for-rancher).
Maybe we should move the `privileged access` note to the top as a catch-all for all options?
cc @jtravee

2021-11-15 18:36 UTC, btat approved these changes

2021-11-16 07:57 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +Privileged access is [required.](#privileged-access-for-rancher)
suggestion commited

2021-11-17 08:23 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +- You will use `--no-cacerts` in the argument to disable the default CA certificate generated by Rancher. Note that privileged access is [required.](#privileged-access-for-rancher).
Suggestion implemented (5c240e8)

2021-11-17 08:23 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +Log into your host machine and run the Docker command below:
Suggestion implemented (5c240e8)

2021-11-17 15:24 UTC, jtravee requested changes

2021-11-17 15:24 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +Log into your host, and run the command below::
```suggestion
Log into your host, and run the command below:
```

2021-11-18 17:14 UTC, jtravee approved these changes

2021-11-18 17:28 UTC, merged