Change UI path to secrets and remove references to project scope
rancher/docs pull request #3683
Opened 2021-11-15 22:33 UTC by dhawton

After discussions with @jtravee in Slack, project scoped secrets are gone. This change removes the last few references in the secrets document and also provides a slightly shorter path to get to secrets in the UI (Storage > Secrets vs More Resources > Core > Secrets).

2021-11-15 22:37 UTC, vincent99 commented
Project-scoped secrets are not gone, but you must be looking at a single project (in the namespace dropdown) to see them (under Legacy->Project->Secrets).

2021-11-15 22:43 UTC, jtravee commented
Got it! I believe we can approve this as the steps to create a project-level secret have changed (so changing as shown is correct). I've created another issue to document the workaround as @vincent99 referenced.

2021-11-15 23:41 UTC, jtravee requested changes

2021-11-15 23:41 UTC, jtravee commented on content/rancher/v2.6/en/k8s-in-rancher/secrets/_index.md
> +1. Click **Storage > Secrets**.
```suggestion
1. To navigate to secrets, you may click either **Storage > Secrets** or **More Resources > Core > Secrets**. 
```

2021-11-15 23:41 UTC, jtravee commented on content/rancher/v2.6/en/k8s-in-rancher/secrets/_index.md
> +**Result:** Your secret is added to the namespace you chose. You can view the secret in the Rancher UI from the **Storage > Secrets** view.
```suggestion
**Result:** Your secret is added to the namespace you chose. You can view the secret in the Rancher UI by clicking either **Storage > Secrets** or **More Resources > Core > Secrets**. 
```

2021-11-15 23:41 UTC, jtravee commented on content/rancher/v2.6/en/k8s-in-rancher/secrets/_index.md
> +1. Click **Storage > Secrets**.
I just updated this as either path works!

2021-11-16 13:10 UTC, jtravee approved these changes

2021-11-16 13:36 UTC, merged