Documented workaround to create project-level secret
rancher/docs pull request #3686
Opened 2021-11-16 16:38 UTC by jtravee

Closes #3684

2021-11-16 18:58 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/projects-and-namespaces/_index.md
> +>**Note:** As of Rancher v2.6, projects are de-emphasized on the UI because you don't need them anymore to create secrets exclusively. However, it's still possible to create [secrets in projects]({{<
how about "As of Rancher v2.6, projects are de-emphasized on the UI because it is no longer required to create any Kubernetes resources within a project scope. However, resources such as Secrets can still be created in a project scope if the `legacy` feature flag is enabled."

2021-11-16 19:00 UTC, catherineluse commented on content/rancher/v2.6/en/k8s-in-rancher/registries/_index.md
> +1. Continue following [steps 1 - 9](#creating-a-registry-in-namespaces) above to create and save your project-level registry. Note that in Step 7 above, you will select the project rather than the na
I think the steps should be repeated here. Because even though it's redundant, it makes it so that these steps would still make sense if the other steps change

2021-11-16 20:46 UTC, jtravee commented on content/rancher/v2.6/en/cluster-admin/projects-and-namespaces/_index.md
> +>**Note:** As of Rancher v2.6, projects are de-emphasized on the UI because you don't need them anymore to create secrets exclusively. However, it's still possible to create [secrets in projects]({{<
Updated, ty!

2021-11-16 20:46 UTC, jtravee commented on content/rancher/v2.6/en/k8s-in-rancher/registries/_index.md
> +1. Continue following [steps 1 - 9](#creating-a-registry-in-namespaces) above to create and save your project-level registry. Note that in Step 7 above, you will select the project rather than the na
Updated, ty!

2021-11-17 18:13 UTC, btat requested changes

2021-11-17 18:13 UTC, btat commented on content/rancher/v2.6/en/k8s-in-rancher/registries/_index.md
> +Prior to v2.6, secrets were required to be in a project scope. Projects are no longer required, and you may use the namespace scope instead. As a result, the Rancher UI was updated to reflect this ne
```suggestion
Before v2.6, secrets were required to be in a project scope. Projects are no longer required, and you may use the namespace scope instead. As a result, the Rancher UI was updated to reflect this new functionality. However, you may still create a project-scoped registry if desired. Use the following steps to do so:
```

Based on previous [feedback](https://github.com/rancher/docs/issues/3033), `prior to` may not be understood by some audiences.

2021-11-17 18:13 UTC, btat commented on content/rancher/v2.6/en/k8s-in-rancher/secrets/_index.md
> +Prior to v2.6, secrets were required to be in a project scope. Projects are no longer required, and you may use the namespace scope instead. As a result, the Rancher UI was updated to reflect this ne
```suggestion
Before v2.6, secrets were required to be in a project scope. Projects are no longer required, and you may use the namespace scope instead. As a result, the Rancher UI was updated to reflect this new functionality. However, you may still create project-scoped secrets if desired. Note that you have to first enable the `legacy` feature flag and look at a single project to do so. Use the following steps to set up your project-level secret:
```

2021-11-17 23:27 UTC, btat approved these changes

2021-11-17 23:27 UTC, merged