Added section for Helm chart dependencies in Fleet for 2.5, 2.6
rancher/docs pull request #3707
Opened 2021-11-29 23:11 UTC by jtravee

Closes #3705; related https://github.com/rancher/fleet/issues/250.

2021-11-29 23:32 UTC, StrongMonkey approved these changes

2021-11-30 00:01 UTC, btat requested changes

2021-11-30 00:01 UTC, btat commented on content/rancher/v2.5/en/deploy-across-clusters/fleet/_index.md
> +In order for the Helm chart dependencies in Fleet to deploy successfully, you must run a manual command (as listed below) to let Fleet know where to retrieve them. If you do not do this and proceed t
```suggestion
In order for Helm charts with dependencies to deploy successfully, you must run a manual command (as listed below) to let Fleet know where to retrieve them. If you do not do this and proceed to clone your repository and run `helm install`, your installation will fail because the dependencies will be missing.
```

2021-11-30 16:40 UTC, jtravee commented on content/rancher/v2.5/en/deploy-across-clusters/fleet/_index.md
> +In order for the Helm chart dependencies in Fleet to deploy successfully, you must run a manual command (as listed below) to let Fleet know where to retrieve them. If you do not do this and proceed t
Revised per feedback.

2021-11-30 16:40 UTC, jtravee commented on content/rancher/v2.5/en/deploy-across-clusters/fleet/_index.md
> +The Helm chart in the git repository must include its dependencies in the charts subdirectory. You must either manually run `helm dependencies update` OR run `helm dependencies build` locally, then c
Revised per feedback.

2021-11-30 16:40 UTC, jtravee commented on content/rancher/v2.5/en/deploy-across-clusters/fleet/_index.md
> +# Fleet Helm Chart Dependencies
Revised per feedback.

2021-11-30 16:40 UTC, jtravee commented on content/rancher/v2.5/en/deploy-across-clusters/fleet/_index.md
> +In order for the Helm chart dependencies in Fleet to deploy successfully, you must run a manual command (as listed below) to let Fleet know where to retrieve them. If you do not do this and proceed t
Revised.

2021-11-30 17:25 UTC, nickgerace approved these changes
Approving this, but I think we all need to decide the future where we add new docs. Since Fleet docs v2 is primarily focused on Fleet in Rancher, is it redundant to add notes to the Rancher docs too? Undecided, but we can talk outside of this PR.

2021-11-30 17:33 UTC, btat approved these changes

2021-12-02 16:24 UTC, merged