Added notes about project-member ability to delete ns
rancher/docs pull request #3709
Opened 2021-11-30 19:29 UTC by jtravee

Closes #3704

2021-11-30 20:21 UTC, snasovich requested changes
Have one comment that I believe needs to be addressed.

2021-11-30 20:21 UTC, snasovich commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-Edit` role. As such, the `project-member` role is a built-in role that will allow namespace management, including the a
`project-owner` will have the ability to delete namespaces too.
In fact I believe this table is wrong as `Project Owner` inherits from `admin` k8s role and `Project Member` inherits from `edit` per https://github.com/rancher/rancher/blob/ec31e6456d4068899460bb83640b63c83eaa72c6/pkg/data/management/role_data.go#L234-L309 (see `setRoleTemplateNames` calls).

2021-11-30 21:02 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-Edit` role. As such, the `project-member` role is a built-in role that will allow namespace management, including the a
Updated table and note as per feedback.

2021-11-30 22:14 UTC, btat requested changes

2021-11-30 22:14 UTC, btat commented on content/rancher/v2.5/en/project-admin/project-members/_index.md
> +    >- Users assigned the `Owner` or `Member` role for a project automatically inherit the `namespace creation` role. However, this role is a [Kubernetes ClusterRole](https://kubernetes.io/docs/refer
This same note is used on other pages too.

2021-11-30 22:14 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-edit` role, and the `project-owner` role inherits from the `Kubernetes-admin` role. As such, both `project-member` and
I don't think the monitoring/alerting page is the appropriate page for this. Updates should be made to https://rancher.com/docs/rancher/v2.5/en/admin-settings/rbac/cluster-project-roles/ as it has tables that define the capabilities for the built-in {cluster, project}-{owner, member} roles.

2021-11-30 22:14 UTC, btat commented on content/rancher/v2.6/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-edit` role, and the `project-owner` role inherits from the `Kubernetes-admin` role. As such, both `project-member` and
See above.

2021-11-30 22:14 UTC, btat commented on content/rancher/v2.6/en/project-admin/project-members/_index.md
> +    >- Users assigned the `Owner` or `Member` role for a project automatically inherit the `namespace creation` role. However, this role is a [Kubernetes ClusterRole](https://kubernetes.io/docs/refer
See above.

2021-12-02 20:56 UTC, jtravee commented on content/rancher/v2.5/en/project-admin/project-members/_index.md
> +    >- Users assigned the `Owner` or `Member` role for a project automatically inherit the `namespace creation` role. However, this role is a [Kubernetes ClusterRole](https://kubernetes.io/docs/refer
Created a new note on this page and the other 2 pages as suggested to advise of capabilities.

2021-12-02 20:57 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-edit` role, and the `project-owner` role inherits from the `Kubernetes-admin` role. As such, both `project-member` and
Removed from rbac page, added here (and as per note, added also to the two other pages that may reference the roles/permissions).

2021-12-02 20:57 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-edit` role, and the `project-owner` role inherits from the `Kubernetes-admin` role. As such, both `project-member` and
Revised per feedback.

2021-12-02 20:58 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-edit` role, and the `project-owner` role inherits from the `Kubernetes-admin` role. As such, both `project-member` and
Removed from RBAC page, added to the 3 pages that reference these project roles/permissions to ensure the user knows the capabilities.

2021-12-02 20:59 UTC, jtravee commented on content/rancher/v2.6/en/project-admin/project-members/_index.md
> +    >- Users assigned the `Owner` or `Member` role for a project automatically inherit the `namespace creation` role. However, this role is a [Kubernetes ClusterRole](https://kubernetes.io/docs/refer
Removed from RBAC page, added to the 3 pages that reference these project roles/permissions to ensure the user knows the capabilities.

2021-12-02 20:59 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/rbac/_index.md
> +>By default, the Rancher role of `project-member` inherits from the `Kubernetes-edit` role, and the `project-owner` role inherits from the `Kubernetes-admin` role. As such, both `project-member` and
Removed from RBAC page, added to the 3 pages that reference these project roles/permissions to ensure the user knows the capabilities.

2021-12-02 20:59 UTC, jtravee commented on content/rancher/v2.5/en/project-admin/project-members/_index.md
> +    >- Users assigned the `Owner` or `Member` role for a project automatically inherit the `namespace creation` role. However, this role is a [Kubernetes ClusterRole](https://kubernetes.io/docs/refer
Removed from RBAC page, added to the 3 pages that reference these project roles/permissions to ensure the user knows the capabilities.

2021-12-08 23:47 UTC, merged