Updated Quickstart docs and Adding Ingresses page for Rancher 2.6
rancher/docs pull request #3711
Opened 2021-12-01 21:35 UTC by jtravee

Closes #3710 

References: 
https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/
https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/load-balancers-and-ingress/ingress/

2021-12-02 01:08 UTC, rak-phillip reviewed
I tried walking through the steps outlined here and I think we might need to make a few small changes.

2021-12-02 01:08 UTC, rak-phillip commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1. Click **Add Port** to enter a port mapping, which enables access to the application inside and outside of the cluster. For more information, see [Services]({{<baseurl>}}/rancher/v2.6/en/k8s-in-ran
I think the Add Port step should come before the Click Create step

2021-12-02 01:08 UTC, rak-phillip commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  From the main menu of the **Dashboard**, select **Projects**.
Should this be `Projects/Namespaces`?

2021-12-02 01:08 UTC, rak-phillip commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  Enter `80` in the **Port** field.
It looks like we also need to add a value for path, I think `/hello` should suffice for the example.

2021-12-02 23:25 UTC, btat requested changes

2021-12-02 23:25 UTC, btat commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  Enter a name, such as **hello**.
Need to add a step before this one telling users to ensure the namespace matches the one they used when creating their deployment. Otherwise their deployment won't be available when selecting the target service.

2021-12-02 23:25 UTC, btat commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  Open the **Default** project.
Both of these steps aren't needed.

2021-12-03 15:08 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1. Click **Add Port** to enter a port mapping, which enables access to the application inside and outside of the cluster. For more information, see [Services]({{<baseurl>}}/rancher/v2.6/en/k8s-in-ran
Updated per feedback.

2021-12-03 15:09 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  From the main menu of the **Dashboard**, select **Projects**.
Removed as this step is not needed.

2021-12-03 15:09 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  Enter `80` in the **Port** field.
Added per feedback.

2021-12-03 15:09 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  Enter a name, such as **hello**.
Added per feedback.

2021-12-03 15:09 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md
> +1.  Open the **Default** project.
Removed per feedback.

2021-12-07 04:52 UTC, btat requested changes

2021-12-07 18:10 UTC, merged