Add config flags that must be shared across server nodes
rancher/docs pull request #3721
Opened 2021-12-08 15:16 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2021-12-08 16:00 UTC, briandowns approved these changes

2021-12-08 17:09 UTC, btat requested changes

2021-12-08 17:09 UTC, btat commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +* Network related flags: `--cluster-dns`, `--cluster-domain`, `--cluster-cidr`, --service-cidr`
```suggestion
* Network related flags: `--cluster-dns`, `--cluster-domain`, `--cluster-cidr`, `--service-cidr`
```

2021-12-08 17:09 UTC, btat commented on content/k3s/latest/en/installation/ha/_index.md
> +* Network related flags: `--cluster-dns`, `--cluster-domain`, `--cluster-cidr`, --service-cidr`
```suggestion
* Network related flags: `--cluster-dns`, `--cluster-domain`, `--cluster-cidr`, `--service-cidr`
```

2021-12-08 17:19 UTC, dereknola requested changes

2021-12-08 17:19 UTC, dereknola commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +* Flags controlling the deployment of certain components `--disable-helm-controller`, `--disable-kube-proxy`, `--disable-network-policy` and any component passed to `--disable`
```suggestion
* Flags controlling the deployment of certain components: `--disable-helm-controller`, `--disable-kube-proxy`, `--disable-network-policy` and any component passed to `--disable`
```

2021-12-08 17:19 UTC, dereknola commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +* Flags controlling the deployment of certain components `--disable-helm-controller`, `--disable-kube-proxy`, `--disable-network-policy` and any component passed to `--disable`
Missing colon

2021-12-08 17:19 UTC, dereknola commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +
Since your here :)

2021-12-08 17:19 UTC, dereknola commented on content/k3s/latest/en/installation/ha/_index.md
> +* Flags controlling the deployment of certain components `--disable-helm-controller`, `--disable-kube-proxy`, `--disable-network-policy` and any component passed to `--disable`
```suggestion
* Flags controlling the deployment of certain components: `--disable-helm-controller`, `--disable-kube-proxy`, `--disable-network-policy` and any component passed to `--disable`
```

2021-12-08 17:20 UTC, dereknola requested changes

2021-12-08 17:20 UTC, dereknola commented on content/k3s/latest/en/installation/ha/_index.md
> +
```suggestion
* Feature related flags: `--secrets-encryption`

```

2021-12-09 18:28 UTC, manuelbuil commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +* Network related flags: `--cluster-dns`, `--cluster-domain`, `--cluster-cidr`, --service-cidr`
thanks

2021-12-09 18:29 UTC, manuelbuil commented on content/k3s/latest/en/installation/ha/_index.md
> +* Network related flags: `--cluster-dns`, `--cluster-domain`, `--cluster-cidr`, --service-cidr`
thanks!

2021-12-09 18:30 UTC, manuelbuil commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +
thanks!

2021-12-09 18:30 UTC, manuelbuil commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +* Flags controlling the deployment of certain components `--disable-helm-controller`, `--disable-kube-proxy`, `--disable-network-policy` and any component passed to `--disable`
thanks

2021-12-09 18:30 UTC, manuelbuil commented on content/k3s/latest/en/installation/ha/_index.md
> +
thanks!

2021-12-09 18:43 UTC, btat approved these changes

2021-12-13 16:57 UTC, dereknola approved these changes

2021-12-13 16:58 UTC, merged