Documented version specific upgrade issues in K3s upgrade documentation
rancher/docs pull request #3724
Opened 2021-12-08 21:31 UTC by jtravee

Closes #3723 

Reference: https://rancher.com/docs/k3s/latest/en/upgrades/

2021-12-08 22:15 UTC, btat requested changes
This PR itself look good, just an extra space.

I can't really tell based on the three items, but are the items grouped/organized in some form? This should be something to consider since this list will be growing constantly and could become difficult for users to extract necessary info that applies to their upgrade scenario.

Maybe as a start the second and third items could be swapped so the list is sorted based on the minimum affected version.

Also, the list itself could also be moved into its own section so it stands out more. As a note, it should probably relate to the immediate contents surrounding it, but this is not the case on this page.

2021-12-09 17:41 UTC, jtravee commented on content/k3s/latest/en/upgrades/_index.md
> +> - **Traefik:** If Traefik is not disabled, K3s versions 1.20 and earlier will install Traefik v1, while K3s versions 1.21 and later will install Traefik v2, if v1 is not already present.  To upgrad
Revised along with the other changes locally.

2021-12-17 22:43 UTC, btat approved these changes

2022-01-20 19:54 UTC, Jono-SUSE-Rancher commented
Hi @katran001 - can you find an appropriate resource on the k3s team to help review this docs issue for Jen?

2022-01-20 20:06 UTC, dereknola approved these changes

2022-01-20 20:26 UTC, merged