Add page about new K3s `secrets-encrypt` tool.
rancher/docs pull request #3735
Opened 2021-12-11 00:21 UTC by dereknola

Added detailed guides on how to use the new `k3s secrets-encrypt` CLI command for k3s. Moved existing info on secrets encryption into a dedicated page under the Security tab.

Also fixed typo on PostgreSQL.

2021-12-13 16:04 UTC, jtravee requested changes

2021-12-13 21:18 UTC, jtravee approved these changes

2021-12-14 21:17 UTC, jtravee requested changes

2021-12-14 21:17 UTC, jtravee commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Warning** Failure to follow proper procedure for rotating encryption keys can leave your cluster permanently corrupted. Proceed with caution.
```suggestion
>**Warning:** Failure to follow proper procedure for rotating encryption keys can leave your cluster permanently corrupted. Proceed with caution.
```

2021-12-14 21:17 UTC, jtravee commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Note** Starting K3s without encryption and enabling it at a later time is currently *not* supported.
```suggestion
>**Note:** Starting K3s without encryption and enabling it at a later time is currently **not** supported.
```

2021-12-14 21:17 UTC, jtravee commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Note** While not required, it is recommended that you pick one server node from which to run the `secrets-encrypt` commands.
```suggestion
>**Note:** While not required, it is recommended that you pick one server node from which to run the `secrets-encrypt` commands.
```

2021-12-14 21:17 UTC, jtravee commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Note** While not required, it is recommended that you pick one server node from which to run the `secrets-encrypt` commands.
```suggestion
>**Note:** While not required, it is recommended that you pick one server node from which to run the `secrets-encrypt` commands.
```

2021-12-14 21:17 UTC, jtravee commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Warning** Failure to follow proper procedure for rotating encryption keys can leave your cluster permanently corrupted. Proceed with caution.
Just a few more!

2021-12-15 17:00 UTC, dereknola commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Note** Starting K3s without encryption and enabling it at a later time is currently *not* supported.
This breaks the formatting of the Note section if I try and bold **not** as well as **Note**
Only added the colon.

2021-12-15 17:11 UTC, jtravee commented on content/k3s/latest/en/security/secrets_encryption/_index.md
> +>**Note** Starting K3s without encryption and enabling it at a later time is currently *not* supported.
Got it!

2021-12-15 17:12 UTC, jtravee approved these changes

2021-12-15 17:12 UTC, merged