More info about K3S_TOKEN and K3S_AGENT_TOKEN
rancher/docs pull request #3743
Opened 2021-12-16 09:50 UTC by manuelbuil

Add some information about the K3S_TOKEN and the K3S_AGENT_TOKEN

2021-12-16 20:02 UTC, jtravee requested changes

2021-12-16 20:02 UTC, jtravee commented on content/k3s/latest/en/advanced/_index.md
> +If no K3S_TOKEN was defined, the first k3s control-plane will generate a random one. The result is part of the content in `/var/lib/rancher/k3s/server/token`. For example `K1070878408e06a827960208f84
```suggestion
If no K3S_TOKEN is defined, the first k3s control-plane will generate a random one. The result is part of the content in `/var/lib/rancher/k3s/server/token`. For example, `K1070878408e06a827960208f84ed18b65fa10f27864e71a57d9e053c4caff8504b::server:df54383b5659b9280aa1e73e60ef78fc`, where `df54383b5659b9280aa1e73e60ef78fc` is the K3S_TOKEN.
```

2021-12-16 20:02 UTC, jtravee commented on content/k3s/latest/en/advanced/_index.md
> +- [Server and agent tokens](#Server-and-agent-tokens)
```suggestion
- [Server and agent tokens](#server-and-agent-tokens)
```

2021-12-17 19:57 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +- [Server and agent tokens](#Server-and-agent-tokens)
thanks!

2021-12-17 19:57 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +In k3s there are two types of tokens: K3S_TOKEN y K3S_AGENT_TOKEN.
Thanks!

2021-12-17 19:57 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +K3S_TOKEN: Defines the key required by the control-plane host to offer the HTTP config resources. These resources are requested by the other control-plane members before joining the k3s ha cluster. I
Thanks!

2021-12-17 19:57 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +If no K3S_TOKEN was defined, the first k3s control-plane will generate a random one. The result is part of the content in `/var/lib/rancher/k3s/server/token`. For example `K1070878408e06a827960208f84
thanks!

2021-12-17 20:05 UTC, dereknola requested changes

2021-12-17 20:05 UTC, dereknola commented on content/k3s/latest/en/advanced/_index.md
> +In k3s, there are two types of tokens: K3S_TOKEN and K3S_AGENT_TOKEN.
```suggestion
In K3s, there are two types of tokens: K3S_TOKEN and K3S_AGENT_TOKEN.
```

2021-12-17 20:05 UTC, dereknola commented on content/k3s/latest/en/advanced/_index.md
> +If no K3S_TOKEN is defined, the first k3s control-plane will generate a random one. The result is part of the content in `/var/lib/rancher/k3s/server/token`. For example, `K1070878408e06a827960208f84
```suggestion
If no K3S_TOKEN is defined, the first K3s server will generate a random one. The result is part of the content in `/var/lib/rancher/k3s/server/token`. For example, `K1070878408e06a827960208f84ed18b65fa10f27864e71a57d9e053c4caff8504b::server:df54383b5659b9280aa1e73e60ef78fc`, where `df54383b5659b9280aa1e73e60ef78fc` is the K3S_TOKEN.
```

2021-12-17 20:05 UTC, dereknola commented on content/k3s/latest/en/advanced/_index.md
> +K3S_AGENT_TOKEN: Optional. Defines the key required by the control-plane host to offer HTTP config resources to the agents. If not defined, agents will require K3S_TOKEN. Defining K3S_AGENT_TOKEN is
```suggestion
K3S_AGENT_TOKEN: Optional. Defines the key required by the server to offer HTTP config resources to the agents. If not defined, agents will require K3S_TOKEN. Defining K3S_AGENT_TOKEN is encouraged to avoid agents having to know K3S_TOKEN, which is also used to encrypt data.
```

All our documentation is center around servers and agents, we generally don't describe servers as "control-plane hosts" even though they are that.

2021-12-17 20:05 UTC, dereknola commented on content/k3s/latest/en/advanced/_index.md
> +K3S_TOKEN: Defines the key required by the control-plane host to offer the HTTP config resources. These resources are requested by the other control-plane members before joining the K3s HA cluster. I
```suggestion
K3S_TOKEN: Defines the key required by the server to offer the HTTP config resources. These resources are requested by the other servers before joining the K3s HA cluster. If the K3S_AGENT_TOKEN is not defined, the agents use this token as well to access the required HTTP resources to join the cluster. Note that this token is also used to generate the encryption key for important content in the database (e.g., bootstrap data).
```

2021-12-20 08:44 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +In k3s, there are two types of tokens: K3S_TOKEN and K3S_AGENT_TOKEN.
thanks!

2021-12-20 08:45 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +K3S_AGENT_TOKEN: Optional. Defines the key required by the control-plane host to offer HTTP config resources to the agents. If not defined, agents will require K3S_TOKEN. Defining K3S_AGENT_TOKEN is
ok, I'll change that. Thanks

2021-12-20 08:46 UTC, manuelbuil commented on content/k3s/latest/en/advanced/_index.md
> +K3S_TOKEN: Defines the key required by the control-plane host to offer the HTTP config resources. These resources are requested by the other control-plane members before joining the K3s HA cluster. I
done!

2021-12-21 16:27 UTC, jtravee approved these changes

2021-12-22 17:21 UTC, dereknola approved these changes

2021-12-22 17:38 UTC, merged