Added documentation on how to add private CA for Helm Chart Repositories in Rancher v2.5.x / v2.6.x
rancher/docs pull request #3745
Opened 2021-12-17 18:13 UTC by jtravee

Closes #3740

2021-12-17 18:43 UTC, btat requested changes

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
There are some extra whitespaces at the start of this line.

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
There are some extra whitespaces at the start of this line.

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
Could this be converted to a codeblock style example like above?

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +- **HTTP-based chart repositories**: You must add a base64 encoded copy of the CA certificate in DER format to the spec.caBundle field of the chart repo, such as `openssl x509 -outform der -in ca.pem
```suggestion
- **HTTP-based chart repositories**: You must add a base64 encoded copy of the CA certificate in DER format to the spec.caBundle field of the chart repo, such as `openssl x509 -outform der -in ca.pem | base64 -w0`. Click **Edit YAML** for the chart repo and set, as in the following example:</br>
```

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
```suggestion
- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Click **Edit YAML** for the chart repo, and add the key/value pair: `spec.insecureSkipTLSVerify: true`.
```

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
> +- **HTTP-based chart repositories**: You must add a base64 encoded copy of the CA certificate in DER format to the spec.caBundle field of the chart repo, such as `openssl x509 -outform der -in ca.pem
```suggestion
- **HTTP-based chart repositories**: You must add a base64 encoded copy of the CA certificate in DER format to the spec.caBundle field of the chart repo, such as `openssl x509 -outform der -in ca.pem | base64 -w0`. Click **Edit YAML** for the chart repo and set, as in the following example:</br>
```

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
> +    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
There are some extra whitespaces at the start of this line.

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
> +    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
There are some extra whitespaces at the start of this line.

2021-12-17 18:43 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
```suggestion
- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Click **Edit YAML** for the chart repo, and add the key/value pair: `spec.insecureSkipTLSVerify: true`.
```

2021-12-17 19:52 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
Might be a Github rendering issue

2021-12-17 19:53 UTC, btat commented on content/rancher/v2.5/en/helm-charts/_index.md
> +    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
Might be a Github rendering issue

2021-12-17 19:53 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
> +    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
Might be a Github rendering issue

2021-12-17 19:53 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
> +    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
Might be a Github rendering issue

2021-12-17 20:08 UTC, jtravee commented on content/rancher/v2.5/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
Revised as suggested.

2021-12-17 20:08 UTC, jtravee commented on content/rancher/v2.5/en/helm-charts/_index.md
> +- **HTTP-based chart repositories**: You must add a base64 encoded copy of the CA certificate in DER format to the spec.caBundle field of the chart repo, such as `openssl x509 -outform der -in ca.pem
Revised as suggested.

2021-12-17 20:09 UTC, jtravee commented on content/rancher/v2.6/en/helm-charts/_index.md
> +- **HTTP-based chart repositories**: You must add a base64 encoded copy of the CA certificate in DER format to the spec.caBundle field of the chart repo, such as `openssl x509 -outform der -in ca.pem
Revised as suggested.

2021-12-17 20:09 UTC, jtravee commented on content/rancher/v2.6/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
Revised as suggested.

2021-12-17 20:09 UTC, jtravee commented on content/rancher/v2.5/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
Revised as suggested.

2021-12-17 22:41 UTC, btat approved these changes

2022-01-20 21:33 UTC, jiaqiluo approved these changes

2022-01-20 22:01 UTC, merged