Added notes for air-gapped migration in 2.5 and 2.6
rancher/docs pull request #3774
Opened 2022-01-05 16:54 UTC by jtravee

Closes #3758

2022-01-05 19:42 UTC, btat requested changes

2022-01-05 19:42 UTC, btat commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +For an **air-gapped environment**, make sure to set the `image.repository` to pull the `rancher-restore-operator` image from your private registry. Note that you will install the rancher-backup chart
We should explicitly list the set flag and its parameter(s). E.g. `--set image.repository $REGISTRY/backup-restore-operator`

2022-01-05 19:42 UTC, btat commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +Install version 1.x.x of the rancher-backup-crd chart. The following assumes a connected environment with access to DockerHub:
I don't think this needs to be changed:
- the version requirement is applicable to both rancher-backup and rancher-backup-crd
- rancher-backup-crd is a dependency of rancher-backup
- connected/non air-gap is the default so it doesn't need to be called out

2022-01-05 20:02 UTC, jtravee commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +Install version 1.x.x of the rancher-backup-crd chart. The following assumes a connected environment with access to DockerHub:
Removed crd callout.

2022-01-05 20:02 UTC, jtravee commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +For an **air-gapped environment**, make sure to set the `image.repository` to pull the `rancher-restore-operator` image from your private registry. Note that you will install the rancher-backup chart
Updated using command.

2022-01-05 20:05 UTC, btat requested changes

2022-01-05 20:05 UTC, btat commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +--set image.repository $REGISTRY/backup-restore-operator
Sorry copy+pasted wrong thing on last comment. Should be `rancher-backup` not `backup-restore-operator`

2022-01-06 16:03 UTC, jtravee commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +--set image.repository $REGISTRY/backup-restore-operator
Updated, ty

2022-01-20 23:27 UTC, cbron commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +For an **air-gapped environment**, use the option below to pull the `rancher-restore-operator` image from your private registry when installing the rancher-backup-crd helm chart.
```suggestion
For an **air-gapped environment**, use the option below to pull the `backup-restore-operator` image from your private registry when installing the rancher-backup-crd helm chart.
```

I imagine you mean this: https://hub.docker.com/r/rancher/backup-restore-operator

2022-01-21 00:09 UTC, prachidamle commented on content/rancher/v2.6/en/backups/migrating-rancher/_index.md
> +For an **air-gapped environment**, use the option below to pull the `rancher-restore-operator` image from your private registry when installing the rancher-backup-crd helm chart.
I guess should be`backup-restore-operator` image

2022-01-21 14:53 UTC, jtravee commented on content/rancher/v2.6/en/backups/migrating-rancher/_index.md
> +For an **air-gapped environment**, use the option below to pull the `rancher-restore-operator` image from your private registry when installing the rancher-backup-crd helm chart.
Updated, thanks!

2022-01-21 14:55 UTC, jtravee commented on content/rancher/v2.5/en/backups/migrating-rancher/_index.md
> +For an **air-gapped environment**, use the option below to pull the `rancher-restore-operator` image from your private registry when installing the rancher-backup-crd helm chart.
Updated, thank you.

2022-01-21 17:14 UTC, prachidamle commented
@jtravee lgtm,  I guess it will be good to squash all commits to single commit before merging.

2022-01-21 17:15 UTC, prachidamle approved these changes

2022-01-21 17:32 UTC, jtravee commented
> @jtravee lgtm, I guess it will be good to squash all commits to single commit before merging.

Will do, thanks!

2022-01-21 20:18 UTC, cbron requested changes

2022-01-21 20:18 UTC, cbron commented on content/rancher/v2.6/en/backups/migrating-rancher/_index.md
> +--set image.repository $REGISTRY/backup-restore-operator
Thinking about this more, I suppose we can't use system_default_registry because its not part of rancher itself ? Thats what I'm assuming. Maybe @axeal knows. 

This is what we are actually changing: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-backup/2.1.0/values.yaml#L1-L2
That being said I think this should be: 

```suggestion
--set image.repository $REGISTRY/rancher/backup-restore-operator
```

2022-01-24 06:47 UTC, axeal commented on content/rancher/v2.6/en/backups/migrating-rancher/_index.md
> +--set image.repository $REGISTRY/backup-restore-operator
Agreed, and your suggested change also looks good.

2022-01-24 17:41 UTC, jtravee commented on content/rancher/v2.6/en/backups/migrating-rancher/_index.md
> +--set image.repository $REGISTRY/backup-restore-operator
Updated.

2022-01-24 18:25 UTC, cbron approved these changes

2022-01-24 18:27 UTC, btat approved these changes

2022-01-24 21:59 UTC, merged