Updated monitoringV2 architecture docs
rancher/docs pull request #3775
Opened 2022-01-06 18:48 UTC by jtravee

Closes #3688 

References:
https://confluence.suse.com/display/EN/Monitoring+V2+Architecture+-+Draft
https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/
https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/how-monitoring-works/

Note: Attaching revised diagram to also be reviewed that will go at the end of section 1, Architecture Overview.

![monitoring-V2-architecture-overview](https://user-images.githubusercontent.com/87146683/148434824-3919f889-d9cf-4111-a65d-e3f0435ff694.png)

2022-01-06 21:56 UTC, btat requested changes

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**1.** **ServiceMonitors and PodMonitors** declaratively specify targets, such as Services and Pods, that need to be monitored.
```suggestion
**1. ServiceMonitors and PodMonitors** declaratively specify targets, such as Services and Pods, that need to be monitored.
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**2.** **PrometheusRules** allow users to define rules for what metrics or time series database queries should result in alerts being fired. Rules are evaluated on an interval.
```suggestion
**2. PrometheusRules** allow users to define rules for what metrics or time series database queries should result in alerts being fired. Rules are evaluated on an interval.
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**3.** **Prometheus Operator** observes ServiceMonitors, PodMonitors, and PrometheusRules being created. When the Prometheus configuration resources are created, Prometheus Operator calls the Prometh
```suggestion
**3. Prometheus Operator** observes ServiceMonitors, PodMonitors, and PrometheusRules being created. When the Prometheus configuration resources are created, Prometheus Operator calls the Prometheus API to sync the new configuration.
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +Prometheus Operator introduces a set of [Custom Resource Definitions](https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions) that allow users to deploy and manage Prome
```suggestion
Prometheus Operator introduces a set of [Custom Resource Definitions](https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions) that allow users to deploy and manage Prometheus and Alertmanager instances by creating and modifying those custom resources on a cluster.
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +1. [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics): expose additional metrics that track the state of resources contained in the Kubernetes API (e.g. pods, workloads, etc.).
```suggestion
1. `kube-state-metrics`: expose additional metrics that track the state of resources contained in the Kubernetes API (e.g., pods, workloads, etc.). For more information on `kube-state-metrics`, refer to the [upstream documentation](https://github.com/kubernetes/kube-state-metrics/tree/master/docs).
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +1. `windows-exporter`: exposes hardware and OS metrics for Windows hosts (only deployed on Windows clusters).
Should there be a link here like the other two?

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +See [architecture](#1-architecture-overview) section for more information on recording rules, alerting rules, and Alertmanager.
```suggestion
See the [architecture](#1-architecture-overview) section for more information on recording rules, alerting rules, and Alertmanager.
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +| Receiver | Configuration block (part of Alertmanager) | Modifies information on where to send an alert (e.g. Slack, PagerDuty, etc.) and any necessary information to send the alert (e.g. TLS certs,
```suggestion
| Receiver | Configuration block (part of Alertmanager) | Modifies information on where to send an alert (e.g., Slack, PagerDuty, etc.) and any necessary information to send the alert (e.g., TLS certs, proxy URLs, etc.). Automatically updates the Alertmanager custom resource. |
```

2022-01-06 21:56 UTC, btat commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +\* You can optionally use hardenedKubelet.enabled to use a PushProx, but that is not the default.
```suggestion
\* You can optionally use `hardenedKubelet.enabled` to use a PushProx, but that is not the default.
```

2022-01-06 22:26 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**1.** **ServiceMonitors and PodMonitors** declaratively specify targets, such as Services and Pods, that need to be monitored.
Revised, ty!

2022-01-06 22:26 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**3.** **Prometheus Operator** observes ServiceMonitors, PodMonitors, and PrometheusRules being created. When the Prometheus configuration resources are created, Prometheus Operator calls the Prometh
Revised, ty!

2022-01-06 22:26 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**2.** **PrometheusRules** allow users to define rules for what metrics or time series database queries should result in alerts being fired. Rules are evaluated on an interval.
Revised, ty!

2022-01-06 22:26 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +Prometheus Operator introduces a set of [Custom Resource Definitions](https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions) that allow users to deploy and manage Prome
Removed, ty!

2022-01-06 22:26 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +1. `windows-exporter`: exposes hardware and OS metrics for Windows hosts (only deployed on Windows clusters).
Linked to upstream, ty

2022-01-06 22:27 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +See [architecture](#1-architecture-overview) section for more information on recording rules, alerting rules, and Alertmanager.
Revised, ty!

2022-01-06 22:27 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +1. [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics): expose additional metrics that track the state of resources contained in the Kubernetes API (e.g. pods, workloads, etc.).
Revised as suggested, thx

2022-01-06 22:27 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +| Receiver | Configuration block (part of Alertmanager) | Modifies information on where to send an alert (e.g. Slack, PagerDuty, etc.) and any necessary information to send the alert (e.g. TLS certs,
Revised, ty!

2022-01-06 22:27 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +\* You can optionally use hardenedKubelet.enabled to use a PushProx, but that is not the default.
Revised, ty!

2022-01-07 19:56 UTC, catherineluse requested changes
Great work! I have some feedback on the organization of the overview section that is connected to the diagram, but the other sections look good to me.

2022-01-07 19:56 UTC, catherineluse commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**1. ServiceMonitors and PodMonitors** declaratively specify targets, such as Services and Pods, that need to be monitored.
The numbers (I mean the numbers not in headings) are left over from the earlier draft where the numbers matched numbers on the diagram. Now that the numbers on the diagram have been removed, I think they should be removed from the text as well.

2022-01-07 19:56 UTC, catherineluse commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +        1. The PushProx Client establishes an outbound connection with the PushProx Proxy.
The information here looks good to me, but since there are four levels of indentation, it looks complicated to me. I think instead of different levels of indentation, there should be more and shorter sections with section titles and subsection titles.

2022-01-07 19:56 UTC, catherineluse commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**3. Prometheus Operator** observes ServiceMonitors, PodMonitors, and PrometheusRules being created. When the Prometheus configuration resources are created, Prometheus Operator calls the Prometheus
This prometheus operator section is called number 3 because in the earlier draft of the diagram, I had imagined the flow of data as being somewhat linear. That was kind of wrong. After talking to Arvind and redoing the diagram, we are basically conveying that instead of a linear flow, we have the prometheus operator in the center of the other components around it.

I think this overview section would better match the diagram if the part about the Prometheus operator came as the starting point, as the first thing in the overview section. And it can directly tie into the diagram by saying something like "As shown in the diagram below, the Prometheus Operator acts as the intermediary between Prometheus and Kubernetes, calling the Prometheus API to synchronize Prometheus with the monitoring related resources in Kubernetes." Feel free to change the wording of that

2022-01-07 22:44 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**1. ServiceMonitors and PodMonitors** declaratively specify targets, such as Services and Pods, that need to be monitored.
Removed, ty!

2022-01-07 22:45 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +        1. The PushProx Client establishes an outbound connection with the PushProx Proxy.
Agreed, created sections to break up the info, ty!

2022-01-07 22:45 UTC, jtravee commented on content/rancher/v2.5/en/monitoring-alerting/how-monitoring-works/_index.md
> +**3. Prometheus Operator** observes ServiceMonitors, PodMonitors, and PrometheusRules being created. When the Prometheus configuration resources are created, Prometheus Operator calls the Prometheus
Done, thanks!

2022-04-26 18:41 UTC, btat approved these changes

2022-04-26 18:44 UTC, merged