Documented how to apply taints to manage mixed OS clusters in RKE2
rancher/docs pull request #3778
Opened 2022-01-07 16:59 UTC by jtravee

Closes #3451

2022-01-28 19:29 UTC, btat requested changes

2022-01-28 19:29 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +>**Important:** Rancher will allow Windows workload pods to deploy on both Windows and Linux worker nodes by default. When creating mixed clusters in RKE2, you must taint the Linux node to ensure Win
On https://github.com/rancher/dashboard/issues/3921#issuecomment-905642221 it mentions the dashboard messaging was `Updated to reflect move away from taints/tolerations and instead promote NodeSelector usage` so this should reflect that too.

2022-01-31 18:19 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +>**Important:** Rancher will allow Windows workload pods to deploy on both Windows and Linux worker nodes by default. When creating mixed clusters in RKE2, you must taint the Linux node to ensure Win
Updated per feedback.

2022-01-31 19:19 UTC, btat requested changes

2022-01-31 19:19 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +>**Important:** Rancher will allow Windows workload pods to deploy on both Windows and Linux worker nodes by default. When creating mixed clusters in RKE2, you must edit the <b>NodeSelector</b> in th
Could you check if we have existing content on NodeSelector to point to in our docs? If not, adding a link to the upstream docs would be he good for users.

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector

2022-01-31 21:40 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/_index.md
> +>**Important:** Rancher will allow Windows workload pods to deploy on both Windows and Linux worker nodes by default. When creating mixed clusters in RKE2, you must edit the <b>NodeSelector</b> in th
Added upstream link as suggested.

2022-02-04 00:32 UTC, rak-phillip approved these changes
LGTM

2022-02-04 16:59 UTC, btat approved these changes

2022-02-04 17:00 UTC, merged