Added steps to edit imported RKE2/K3S clusters to enable ACE
rancher/docs pull request #3793
Opened 2022-01-14 20:27 UTC by jtravee

Closes #3787 

Reference: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/registered-clusters/#authorized-cluster-endpoint-support-for-rke2-and-k3s-clusters

2022-01-14 21:11 UTC, btat approved these changes

2022-01-24 17:37 UTC, thedadams requested changes

2022-01-24 17:37 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/registered-clusters/_index.md
> +      >**Note:** The <b>FQDN</b> field is optional, and if one is entered, it should point to the downstream cluster. Certificate information is only needed if there is a load balancer in front of th
They could enter the CA certificates if they use valid certificates, but it's not necessary. This wording expresses that.
```suggestion
      >**Note:** The <b>FQDN</b> field is optional, and if one is entered, it should point to the downstream cluster. Certificate information is only needed if there is a load balancer in front of the downstream cluster that is using an untrusted certificate. If you have a valid certificate, then nothing needs to be added to the <b>CA Certificates</b> field.
```

2022-01-24 18:02 UTC, thedadams approved these changes

2022-01-24 18:20 UTC, merged