Added note and link to AWS QS docs
rancher/docs pull request #3797
Opened 2022-01-18 17:39 UTC by jtravee

Closes #3790 

References:
https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-qs/
[SURE-3880](https://jira.suse.com/browse/SURE-3880?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)

2022-01-28 19:20 UTC, btat requested changes

2022-01-28 19:20 UTC, btat commented on content/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-qs/_index.md
> +# What's Next?
I don't think we should move the "What's Next" section after the "Destroying the Environment" section to avoid readers go through the doc linearly and removing their environment before actually using it. Destructive actions like deleting the clusters should come at the end since that's generally when no other actions can be performed.

2022-01-28 19:20 UTC, btat commented on content/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-qs/_index.md
> +# Deploying Rancher using AWS Marketplace
Looking at the quickstarts a bit more, we should just move to its own page so there's visibility.

Another bullet would then be added to the list on https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/ .

2022-01-31 17:37 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-qs/_index.md
> +# What's Next?
Revised back to original as suggested.

2022-01-31 17:37 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-qs/_index.md
> +# Deploying Rancher using AWS Marketplace
Created new page & section as suggested, add to TOC.

2022-01-31 18:24 UTC, btat commented on content/rancher/v2.6/en/quick-start-guide/deployment/_index.md
> +- [AWS Alternative](./amazon-aws-qs-alternative) (uses Amazon EKS)
Thoughts on calling it "Marketplace" instead of "Alternative"?

2022-01-31 20:16 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/deployment/_index.md
> +- [AWS Alternative](./amazon-aws-qs-alternative) (uses Amazon EKS)
Agreed! Updated.

2022-01-31 21:12 UTC, btat approved these changes

2022-02-03 21:20 UTC, wjimenez5271 approved these changes

2022-02-03 21:22 UTC, merged