Updated/added RancherD notes to reflect discontinuation
rancher/docs pull request #3826
Opened 2022-01-26 23:33 UTC by jtravee

Closes #3825

2022-01-27 22:39 UTC, btat approved these changes

2022-02-02 17:55 UTC, brandond requested changes

2022-02-02 17:55 UTC, brandond commented on content/rancher/v2.5/en/installation/_index.md
> +- **RancherD** was an experimental tool for installing Rancher, which was available as of Rancher v2.5.4 but is now deprecated. RancherD is a single binary that first launches an RKE2 Kubernetes clus
How about this:
```suggestion
- **RancherD** was an experimental tool for installing Rancher; a single binary that first launches an RKE2 Kubernetes cluster, then installs the Rancher server Helm chart on the cluster. It was available as part of Rancher v2.5.4 through v2.5.10, but is now deprecated and not available for recent releases.
```

2022-02-02 21:51 UTC, jtravee commented on content/rancher/v2.5/en/installation/_index.md
> +- **RancherD** was an experimental tool for installing Rancher, which was available as of Rancher v2.5.4 but is now deprecated. RancherD is a single binary that first launches an RKE2 Kubernetes clus
Updated notes per feedback, thanks!

2022-02-02 21:54 UTC, brandond approved these changes
💯  💯  💯

2022-02-03 14:15 UTC, merged