Added note for new Rancher behavior in EC2 security groups
rancher/docs pull request #3836
Opened 2022-02-01 16:32 UTC by jtravee

Closes #3832

Reference: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-node-template-config/#security-group

2022-02-01 21:37 UTC, btat requested changes

2022-02-01 21:37 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-node-template-config/_index.md
> +If you provide your own security group for an EC2 instance, please note that Rancher will not modify it. As such, you will be responsible for ensuring that your security group is set to allow the nec
`necessary ports for Rancher` - we should add a link to what these are

2022-02-02 16:10 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-node-template-config/_index.md
> +If you provide your own security group for an EC2 instance, please note that Rancher will not modify it. As such, you will be responsible for ensuring that your security group is set to allow the nec
Added link as suggested.

2022-02-02 21:24 UTC, btat approved these changes

2022-02-03 00:13 UTC, slickwarren approved these changes
LGTM

2022-02-05 00:43 UTC, thedadams approved these changes

2022-02-07 14:26 UTC, merged