Added proxy configuration for air-gapped local cluster behind proxy
rancher/docs pull request #3841
Opened 2022-02-01 22:56 UTC by jtravee

Closes #3830

2022-02-01 23:23 UTC, btat requested changes

2022-02-01 23:23 UTC, btat commented on content/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/launch-kubernetes/_index.md
> +#### HTTP proxy
This heading is probably not needed since the parent page is "Installing Rancher behind an HTTP Proxy" and it should be implied anything within it is related to proxies.

2022-02-01 23:23 UTC, btat commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
> +In addition to setting the default rules for a proxy server as shown above, you will need to add additional rules, shown below, to provision node driver clusters from a proxied Rancher environment. N
Since the other page mentions that the example is Ubuntu-specific, it might be good to include that here too.

2022-02-01 23:23 UTC, btat commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
> +### Air-gapped local cluster proxy configuration
We can omit the "local cluster" distinction since things under /en/installation are about the Rancher server itself.

2022-02-02 15:53 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/launch-kubernetes/_index.md
> +#### HTTP proxy
Removed header as suggested.

2022-02-02 15:53 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
> +In addition to setting the default rules for a proxy server as shown above, you will need to add additional rules, shown below, to provision node driver clusters from a proxied Rancher environment. N
Added Ubuntu-specific verbiage as suggested.

2022-02-02 15:54 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
> +### Air-gapped local cluster proxy configuration
Removed phrase as suggested.

2022-02-02 17:43 UTC, btat approved these changes

2022-02-03 18:13 UTC, jiaqiluo requested changes
Why do we need to configure the Proxy for APT? 
If I understand it right, the configuration should go to the proxy server.

2022-02-04 15:57 UTC, jiaqiluo approved these changes

2022-02-04 19:41 UTC, slickwarren approved these changes

2022-02-04 19:41 UTC, slickwarren commented on content/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/launch-kubernetes/_index.md
> +Note that you will configure `/etc/apt/apt.conf.d/proxy.conf` directly:
depending on the user's setup, this filepath could be different. Might be fine to leave it as-is but worth noting.

2022-02-04 19:41 UTC, slickwarren commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
> +You will configure `/etc/apt/apt.conf.d/proxy.conf` with the following:
filepath will vary from setup.

2022-02-04 22:22 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/launch-kubernetes/_index.md
> +Note that you will configure `/etc/apt/apt.conf.d/proxy.conf` directly:
Added note that filepath may vary per setup, thx!

2022-02-04 22:22 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/proxy/_index.md
> +You will configure `/etc/apt/apt.conf.d/proxy.conf` with the following:
Added note that filepath may vary per setup, thx!

2022-02-05 00:26 UTC, slickwarren approved these changes

2022-02-05 00:28 UTC, merged