Renamed page, added new section for updating private CA cert to non-private cert
rancher/docs pull request #3848
Opened 2022-02-03 22:27 UTC by jtravee

Closes #3680 

References: [2.5 updating CA cert docs](https://rancher.com/docs/rancher/v2.5/en/installation/resources/update-ca-cert/) and [2.6 updating CA cert docs](https://rancher.com/docs/rancher/v2.6/en/installation/resources/update-ca-cert/).

2022-02-04 17:06 UTC, btat requested changes
The installation/resources/tls-secrets/_index.md page has a link to this page that needs to be updated.

2022-02-05 00:50 UTC, thedadams requested changes

2022-02-05 00:50 UTC, thedadams commented on content/rancher/v2.5/en/installation/resources/update-rancher-cert/_index.md
> +- The `CATTLE_CA_CHECKSUM` environment variable on the downstream cluster agents **must** be updated to "" (an empty string).
In order to make the documentation consistent, I feel like these steps should be explicitly laid out like the "Updating a Private CA Certificate" steps. For example, in order to switch from a private to a trusted cert, the user will likely need to update the helm chart and go through similar steps as in "Reconfigure Rancher agents to trust the private CA" to ensure the `CATTLE_CA_CHECKSUM` is updated appropriately.

I would be happy to help lay out these steps if necessary.

2022-02-07 14:31 UTC, jtravee commented on content/rancher/v2.5/en/installation/resources/update-rancher-cert/_index.md
> +- The `CATTLE_CA_CHECKSUM` environment variable on the downstream cluster agents **must** be updated to "" (an empty string).
@thedadams, that would be great if you could!

2022-05-24 21:57 UTC, jtravee commented
Closed in favor of [#4119](https://github.com/rancher/docs/pull/4119).

2022-05-24 21:57 UTC, closed without merging