Called out that K3s drops in-tree kubernetes storage drivers
rancher/docs pull request #3861
Opened 2022-02-09 15:49 UTC by jtravee

Closes #3857 

Reference: https://rancher.com/docs/k3s/latest/en/storage/

2022-02-14 22:30 UTC, btat approved these changes
lgtm

2022-02-16 15:44 UTC, cjellick approved these changes
Looks good to me, but @brandond can you give this a super quick review to make sure it makes sense in context?

cc @cwayne18

2022-02-16 18:38 UTC, brandond requested changes

2022-02-16 18:38 UTC, brandond commented on content/k3s/latest/en/storage/_index.md
> +Additionally, upstream Kubernetes will be migrating from in-tree drivers to CSI soon. For more information on this migration, please refer [here](https://kubernetes.io/blog/2021/12/10/storage-in-tree
How about this:

```suggestion
K3s removes several optional volume plugins and all built-in (sometimes referred to as "in-tree") cloud providers. We do this in order to achieve a smaller binary size, and to avoid dependence on third-party cloud or data center technologies and services, which may not be available in many K3s use cases. We are able to do this because their removal affects neither core Kubernetes functionality nor conformance.

The following volume plugins have been removed from K3s:
* cephfs
* fc
* flocker
* git_repo
* glusterfs
* portworx
* quobyte
* rbd
* storageos

Both components have out-of-tree alternatives that can be used with K3s: The kubernetes [Container Storage Interface (CSI)](https://github.com/container-storage-interface/spec/blob/master/spec.md) and [Cloud Provider Interface (CCM)](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/).

Upstream Kubernetes is actively migrating in-tree volume plugins to CSI drivers. For more information on this migration, please refer [here](https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/).
```

2022-02-16 22:01 UTC, brandond approved these changes

2022-02-16 22:28 UTC, jtravee commented on content/k3s/latest/en/storage/_index.md
> +Additionally, upstream Kubernetes will be migrating from in-tree drivers to CSI soon. For more information on this migration, please refer [here](https://kubernetes.io/blog/2021/12/10/storage-in-tree
Revised, thank you!

2022-02-16 22:28 UTC, merged