Documented ingress behavior with Cilium CNI
rancher/docs pull request #3884
Opened 2022-02-17 20:46 UTC by jtravee

Closes #3868 

- References: [Cilium docs](https://rancher.com/docs/rancher/v2.6/en/faq/networking/cni-providers/#cilium) and [RKE2 config docs](https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/rke2-config-reference/).

- Verified that behavior is already implemented (not new in 2.6.4).

2022-02-17 23:58 UTC, paynejacob approved these changes

2022-02-18 00:55 UTC, btat requested changes

2022-02-18 00:55 UTC, btat commented on content/rancher/v2.6/en/faq/networking/cni-providers/_index.md
> +#### Ingress Routing Across Nodes in Cilium
Should this be a subsection (so h5 instead) of the Cilium section?

2022-02-18 10:45 UTC, divya-mohan0209 reviewed
I could not add comments against the individual lines and these are non-blocking nits that only improve readability for the sections not added by @jtravee 

These are non-blocking nits and are suggesting improvements to the existing document rather than the commit pushed by @jtravee 

Rephrase,
Line 11: You can configure the Kubernetes options one of two ways: 
to 
You can configure the Kubernetes options in one of  the two ways: 

Line 31: > After you launch the cluster, you cannot change your network provider. Therefore, choose which network provider you want to use carefully, as Kubernetes doesn't allow switching between network providers. Once a cluster is created with a network provider, changing network providers would require you  tear down the entire cluster and all its applications.
to
Line 31: > After you launch the cluster, you cannot change your network provider. Therefore, choose which network provider you want to use carefully, as Kubernetes doesn't allow switching between network providers. Once a cluster is created with a network provider, changing network providers would require you to tear down the entire cluster and all its applications.

Line 86: Additional Kubernetes manifests, managed as a [Add-on](https://kubernetes.io/docs/concepts/cluster-administration/addons/), to apply to the cluster on startup. Refer to the [RKE2 documentation](https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts) for details.
to
Additional Kubernetes manifests, managed as an [Add-on](https://kubernetes.io/docs/concepts/cluster-administration/addons/), to apply to the cluster on startup. Refer to the [RKE2 documentation](https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts) for details.

2022-02-18 18:24 UTC, btat approved these changes

2022-02-22 14:58 UTC, merged