Add comment about disabling netpol when flannel-backend=none
rancher/docs pull request #3927
Opened 2022-03-04 15:19 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

Issue: https://github.com/k3s-io/k3s/issues/5188

2022-03-04 16:05 UTC, jtravee requested changes

2022-03-04 16:05 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +Run K3s with `--flannel-backend=none` and install your CNI of choice. Most CNI plugins come with their own network policy engine, so it is recommended to apply `disable-network-policy=true` as well t
```suggestion
Run K3s with `--flannel-backend=none` and install your CNI of choice. Most CNI plugins come with their own network policy engine, so it is recommended to apply `disable-network-policy=true` as well to avoid conflicts. IP Forwarding should be enabled for Canal and Calico. Please reference the steps below.
```

2022-03-04 20:17 UTC, jtravee approved these changes

2022-03-07 21:07 UTC, brandond requested changes

2022-03-07 21:07 UTC, brandond commented on content/k3s/latest/en/installation/network-options/_index.md
> +Run K3s with `--flannel-backend=none` and install your CNI of choice. Most CNI plugins come with their own network policy engine, so it is recommended to apply `disable-network-policy=true` as well t
nit
```suggestion
Run K3s with `--flannel-backend=none` and install your CNI of choice. Most CNI plugins come with their own network policy engine, so it is recommended to set `--disable-network-policy` as well to avoid conflicts. IP Forwarding should be enabled for Canal and Calico. Please reference the steps below.
```

2022-03-08 13:57 UTC, manuelbuil commented on content/k3s/latest/en/installation/network-options/_index.md
> +Run K3s with `--flannel-backend=none` and install your CNI of choice. Most CNI plugins come with their own network policy engine, so it is recommended to apply `disable-network-policy=true` as well t
thanks Brad

2022-03-08 18:40 UTC, brandond approved these changes

2022-03-08 22:30 UTC, merged