Update documentation on resource quota limits
rancher/docs pull request #3932
Opened 2022-03-07 22:33 UTC by maxsokolovsky

Related to https://github.com/rancher/rancher/issues/35647

2022-03-07 22:58 UTC, catherineluse approved these changes
LGTM

2022-03-07 23:10 UTC, catherineluse commented
@jtravee There's some more information about this in https://github.com/rancher/dashboard/issues/5016 but it's complicated. To summarize the background context of these changes, I would say:

- Currently in the Rancher UI, if you edit project quota limits or namespace default limits, it will update existing namespaces in the project. This is not desired behavior and the UI is going to change so that only new namespaces are affected by editing resource quotas at the project level, not existing namespaces.
- Currently in the Rancher UI, if you make a project resource quota, then you have namespaces within the project that have quotas adding up to the project quota, there's no resource capacity remaining in the project, so if you try to create a new namespace in the project, you see resource limits set to zero or negative values in the namespace. Because to set the default resource limits for new namespaces in the project, the UI first adds up all the limits for namespaces within the project, then compares that with the project resource quota. If there's any resources left in the project, then the default limit is that remainder or the default namespace quota, whichever is smaller. There are several UI tickets open to try to improve the user experience around this in the UI. https://github.com/rancher/dashboard/issues/5016#issuecomment-1048383086
- The user can create a namespace within a project by using kubectl, only if they add annotations about what project they want to put the namespace in. They can also use annotations to ask for resources to be allocated for the namespace. There is currently an open UI ticket where we want to stop using those annotations to calculate how many resources are left in a project, because those annotations only represent what was requested, not what was actually received. https://github.com/rancher/dashboard/issues/5188

I hope that is enough context. These docs changes are basically capturing how the UI is supposed to work when the bugs are fixed, in an effort to keep the UI and the docs in sync.

2022-03-08 17:12 UTC, btat requested changes
Other than the typo, LGTM.

2022-03-08 17:12 UTC, btat commented on content/rancher/v2.6/en/project-admin/resource-quotas/quotas-for-projects/_index.md
> +However, this is not the case with namespaces created outside of Rancher's UI. To namespaces created via `kubectl`, Rancher
```suggestion
However, this is not the case with namespaces created outside of Rancher's UI. For namespaces created via `kubectl`, Rancher
```

2022-03-08 17:19 UTC, btat approved these changes

2022-03-08 18:29 UTC, catherineluse commented on content/rancher/v2.6/en/project-admin/resource-quotas/quotas-for-projects/_index.md
> +If a new namespace, for any one resource, will exceed the remaining quota for it,
Can we change this sentence to "If the requested resources exceed the remaining capacity in the project for those resources, Rancher will assign the namespace the remaining capacity for that resource."

2022-03-08 18:35 UTC, catherineluse commented on content/rancher/v2.6/en/project-admin/resource-quotas/quotas-for-projects/_index.md
>  Let's highlight some more nuanced functionality. If a quota is deleted at the project level, it will also be removed from all namespaces contained within that project, despite any overrides that may
@jtravee this part about

> Further, updating an existing namespace default limit for a quota at the project level will not result in that value being propagated to existing namespaces in the project;

This is the part I was thinking of that is not going to be technically true until this issue is fixed: https://github.com/rancher/dashboard/issues/5188

Can you please open another docs issue that just says this paragraph about the nuanced functionality should be updated for v2.6.5? There are a number of UI issues related to project quotas with most being targeted for v2.6.5. https://github.com/rancher/dashboard/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fproject-quota

2022-03-08 19:16 UTC, catherineluse commented
@btat I updated one little thing - i would say it's good to merge now.

2022-03-08 19:17 UTC, merged

2022-03-08 23:35 UTC, cbron commented on content/rancher/v2.6/en/project-admin/resource-quotas/quotas-for-projects/_index.md
> +If the requested resources exceed the remaining capacity in the project for those resources, Rancher will assign the namespace the remaining capacity for that resource.
The paragraph above should start with the fact that this is how UI acts. Having that only on line 40 below is somewhat confusing. Reading just lines 37 and 38 we say "rancher" which intuitively means everything (or from a technical POV its the controllers).