Discourage Docker install, encourage Helm CLI install
rancher/docs pull request #3934
Opened 2022-03-08 02:24 UTC by catherineluse

I have completely replaced the "manual quick start" guide with this file here. The commands are for mac but obviously we could put up windows and linux versions too. https://github.com/rancher/docs/blob/d712d91d6eeb0690709c61de122918c18d8a9314/content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md I'm really trying to decrease friction for the Helm CLI install by explaining it in a way that beginners can understand.

This PR addresses https://github.com/rancher/docs/issues/3933 and partly addresses https://github.com/rancher/docs/issues/3922. 

This separate PR to the `rancherlabs/website` removes the "2 Easy Steps" in rancher.com that encourage people to do the Docker install. https://github.com/rancherlabs/website/pull/2657

This separate PR to the `rancherlabs/website-theme` repo is required to change the footer in rancher.com that drives too many people to the docker install. https://github.com/rancherlabs/website-theme/pull/234

2022-03-08 14:39 UTC, nunix reviewed
Few rephrasing, which is totally optional.

2022-03-08 14:39 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. these instructions are provided for testing and development purposes.
```suggestion
The Docker install is not recommended for production. these instructions are provided for testing and development purposes only.
```

2022-03-08 14:39 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. These instructions are provided for testing and development purposes.
```suggestion
The Docker install is not recommended for production. These instructions are provided for testing and development purposes only.
```

2022-03-08 14:39 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. these instructions are provided for testing and development purposes.
The `only` at the end is to be consistent with the same phrase in the `single-node-docker/single-node-upgrades` page.

2022-03-08 14:39 UTC, nunix commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. These instructions are provided for testing and development purposes.
The `only` at the end is to be consistent with the same phrase in the `single-node-docker/single-node-upgrades` page.

2022-03-08 14:39 UTC, nunix commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +Your Linux machine can be anywhere. It could be an Amazon EC2 instance, a Digital Ocean droplet, or an Azure virtual machine, to name a few examples. (Other Rancher docs often use 'node' as a generic
I guess the parentheses for the second phrase can be dropped. The phrase placement is "in-between" (instead of follow-up) and brings concrete information.

2022-03-08 20:32 UTC, jtravee requested changes

2022-03-08 20:32 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. these instructions are provided for testing and development purposes.
```suggestion
The Docker install is not recommended for production. These instructions are provided for testing and development purposes.
```

2022-03-08 20:32 UTC, jtravee commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +> **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof of concept, you c
```suggestion
> **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof-of-concept, you can use a fake domain name when passing the `hostname` option. An example of a fake domain name would be `<IP_OF_LINUX_NODE>.sslip.io`, which would expose Rancher on an IP where Rancher would be running. Production installs would require a real domain name.
```

2022-03-08 20:32 UTC, jtravee commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +> **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof of concept, you c
Added hyphens to keep the phrase consistent throughout.

2022-03-08 20:32 UTC, jtravee commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +The final command to install Rancher is below. The command requires a domain name that forwards traffic to the Linux machine. For the sake of simplicity in this tutorial, you can use a fake domain na
```suggestion
The final command to install Rancher is below. The command requires a domain name that forwards traffic to the Linux machine. For the sake of simplicity in this tutorial, you can use a fake domain name to create your proof-of-concept. An example of a fake domain name would be `<IP_OF_LINUX_NODE>.sslip.io`.
```

2022-03-14 06:48 UTC, divya-mohan0209 requested changes
Mostly grammatical nits

2022-03-14 06:48 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +> **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof of concept, you c
Adding on to suggestion by @jtravee above. Rancher is repeated multiple times in the third sentence, I think phrasing it this way would be better.

```suggestion
> > **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof-of-concept, you can use a fake domain name when passing the `hostname` option. An example of a fake domain name would be `<IP_OF_LINUX_NODE>.sslip.io`, which would expose Rancher on an IP where it is running. Production installs would require a real domain name.
```

2022-03-14 06:48 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/_index.md
> +> **Docker installs are not supported in production.** We don't support upgrading Docker installs in production environments, and these instructions are provided for testing and development purposes
Redundant line eliminated.

```suggestion
> **Docker installs are not supported in production environments.** These instructions are provided for testing and development purposes only. If you have already deployed a Docker install in production and need to upgrade to a new Rancher version, we recommend [migrating to the Helm chart install]({{<baseurl>}}/rancher/v2.6/en/backups/migrating-rancher/) before upgrading.
```

2022-03-14 06:48 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +These instructions assume you have a Linux virtual machine that you will communicate with from your local workstation. Rancher will be installed on the Linux machine. You will need to retrieve the IP
Nit

```suggestion
These instructions assume you have a Linux virtual machine that you will communicate with from your local workstation. Rancher will be installed on the Linux machine. You will need to retrieve the IP address of that machine so that you can access Rancher from your local workstation. Rancher is designed to manage Kubernetes clusters remotely, so any Kubernetes cluster that Rancher manages in the future will also need to be able to reach this IP address.
```

2022-03-21 19:39 UTC, catherineluse commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +> **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof of concept, you c
added hyphens

2022-03-21 19:39 UTC, catherineluse commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +> **Tip for testing and development:** This final command to install Rancher requires a domain name that forwards traffic to Rancher. If you are using the Helm CLI to set up a proof of concept, you c
updated

2022-03-21 19:41 UTC, catherineluse commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. these instructions are provided for testing and development purposes.
updated

2022-03-21 19:41 UTC, catherineluse commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. these instructions are provided for testing and development purposes.
Updated

2022-03-21 19:42 UTC, catherineluse commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/_index.md
> +The Docker install is not recommended for production. These instructions are provided for testing and development purposes.
updated

2022-03-21 19:43 UTC, catherineluse commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/_index.md
> +> **Docker installs are not supported in production.** We don't support upgrading Docker installs in production environments, and these instructions are provided for testing and development purposes
updated

2022-03-21 19:44 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +These instructions assume you have a Linux virtual machine that you will communicate with from your local workstation. Rancher will be installed on the Linux machine. You will need to retrieve the IP
updated

2022-03-21 19:45 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +Your Linux machine can be anywhere. It could be an Amazon EC2 instance, a Digital Ocean droplet, or an Azure virtual machine, to name a few examples. (Other Rancher docs often use 'node' as a generic
removed parentheses

2022-03-21 19:53 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +```
created two tabs, one for mac/linux and one for windows

2022-03-21 19:54 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +Press `i` to put Vim in insert mode. To save your work, press `Esc`. Then press `:wq` and press `enter`.
updated

2022-03-21 20:00 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +```
since it's the same I'll leave it as is

2022-03-21 20:01 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +```
since it's the same I'll leave it as is

2022-03-21 20:04 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +The final command to install Rancher is below. The command requires a domain name that forwards traffic to the Linux machine. For the sake of simplicity in this tutorial, you can use a fake domain na
updated

2022-03-21 20:09 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
created two tabs, one for Mac and Linux and one for Windows

2022-03-21 20:09 UTC, catherineluse commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +```
added tabs

2022-03-21 20:15 UTC, catherineluse commented
@jtravee I've responded to the feedback on this PR. Can you please re-review?

2022-03-21 20:34 UTC, jtravee approved these changes

2022-03-24 06:52 UTC, divya-mohan0209 requested changes
Minor grammatical nits & rephrasing

2022-03-24 06:52 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/_index.md
> +- **Review the [known upgrade issues]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/#known-upgrade-issues)** in the Rancher documentation for the most noteworthy issues t
I feel this reads better. Non-blocking nit, though.

```suggestion
- **Review the [known upgrade issues]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/#known-upgrade-issues)** section in the Rancher documentation for the most noteworthy issues to consider when upgrading Rancher. A more complete list of known issues for each Rancher version can be found in the release notes on [GitHub](https://github.com/rancher/rancher/releases) and on the [Rancher forums](https://forums.rancher.com/c/announcements/12). Note that upgrades to or from any chart in the [rancher-alpha repository]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/chart-options/#helm-chart-repositories/) aren’t supported.
```

2022-03-24 06:52 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +Your Linux machine can be anywhere. It could be an Amazon EC2 instance, a Digital Ocean droplet, or an Azure virtual machine, to name a few examples. Other Rancher docs often use 'node' as a generic
```suggestion
Your Linux machine can be anywhere. It could be an Amazon EC2 instance, a Digital Ocean droplet, or an Azure virtual machine, to name a few examples. Other Rancher docs often use 'node' as a generic term for all of these. One possible way to deploy a Linux machine is by setting up an Amazon EC2 instance as shown in [this tutorial]({{<baseurl>}}/rancher/v2.6/en/installation/resources/k8s-tutorials/infrastructure-tutorials/ec2-node/).
```

2022-03-24 06:52 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +The full installation requirements are [here.]({{<baseurl>}}/rancher/v2.6/en/installation/requirements/)
```suggestion
The full installation requirements are [here]({{<baseurl>}}/rancher/v2.6/en/installation/requirements/).
```

2022-03-24 06:52 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +Install a K3s Kubernetes cluster by running this command on the Linux machine:
K3s, by default, is a certified Kubernetes distribution. I don’t think we need to mention K3s Kubernetes cluster in this statement.

```suggestion
Install a K3s cluster by running this command on the Linux machine:
```

2022-03-24 06:52 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +In the kubeconfig file, the server directive is defined as `localhost`. You will need to change the server directive from `localhost` to `<IP_OF_LINUX_NODE>:6443`. (The Kubernetes API server will be
The brackets, in my opinion, are unnecessary. Please feel free to retain them, if you feel they add value to the statement. Non-blocking nit.

```suggestion
In the kubeconfig file, the server directive is defined as `localhost`. You will need to change the server directive from `localhost` to `<IP_OF_LINUX_NODE>:6443`. The Kubernetes API server will be reached at port 6443, while the Rancher server will be reached at ports 80 and 443. This edit is needed so that when you run Helm or kubectl commands from your local workstation, you will be able to communicate with the Kubernetes cluster that Rancher will be installed on.
```

2022-03-24 06:52 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/_index.md
> +Then from your local workstation, run the following commands. You will need to have installed [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl) and [helm.](https://helm.sh/docs/intro/install
Minor nit.

```suggestion
Then from your local workstation, run the following commands. You will need to have [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl) and [helm.](https://helm.sh/docs/intro/install/) installed.
```

2022-04-01 05:18 UTC, divya-mohan0209 approved these changes

2022-04-01 15:47 UTC, merged