Created new section for RKE1 v. RKE2 difference highlights
rancher/docs pull request #3947
Opened 2022-03-11 22:52 UTC by jtravee

Closes #3925 and adds an overview section to highlight the diffs between RKE1/RKE2 in a conceptual way.

2022-03-14 23:15 UTC, catherineluse requested changes

2022-03-14 23:15 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +RKE1 uses Docker for deploying and managing control plane components and the container runtime for Kubernetes. By contrast, RKE2 launches control plane components such as static pods that are managed
This paragraph isn't clear to me.

> RKE1 uses Docker for deploying and managing control plane components and the container runtime for Kubernetes.

The thing is, Docker is a container runtime. (both docker and containerd are container runtime) And the controlplane is part of Kubernetes. (https://kubernetes.io/docs/concepts/overview/components/) Did it mean to say "RKE1 uses Docker for deploying and managing controlplane components and containerd for other Kubernetes components"?

> By contrast, RKE2 launches control plane components such as static pods that are managed by the kubelet.

This doesn't make sense to me - was it meant to say "By contrast, RKE2 launches controlplane components with containerd"?

2022-03-14 23:15 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +- When nodes are being provisioned and a scale down operation is performed, rather than scaling down directly, nodes are deleted and new nodes are provisioned to reach the desired node count.
what is scaling down directly? does that mean it would just delete one node from the node pool? I would expect node(s) to be deleted during scale down in any case so I don't understand how the behavior changed.

2022-03-15 17:14 UTC, thedadams requested changes

2022-03-15 17:14 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +- When nodes are being provisioned and a scale down operation is performed, rather than scaling down directly, nodes are deleted and new nodes are provisioned to reach the desired node count.
```suggestion
- When nodes are being provisioned and a scale down operation is performed, rather than scaling down the desired number of nodes, it is possible that the currently provisioning nodes are deleted and new nodes are provisioned to reach the desired node count.
```

For what is it worth, the cluster API folks have deemed this a bug and will be fixed in the future.

2022-03-15 17:14 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +You will notice that some terms have changed or gone away going from RKE1 to RKE2. For example, in RKE2, **node templates** have been deprecated, and you can configure your cluster nodes directly. An
I don't think it is correct to call node templates deprecated. RKE1 provisioning will always use them, as far as I understand.

2022-03-15 17:25 UTC, brandond commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +RKE1 uses Docker for deploying and managing control plane components and the container runtime for Kubernetes. By contrast, RKE2 launches control plane components such as static pods that are managed
No, I think it's correct to say that we use the kubelet. RKE2 writes static pod manifests, which are picked up by the kubelet. The kubelet in turn creates containers in the container runtime (which is containerd by default). RKE2 does not directly create containers in containerd in the same way that RKE1 creates containers in Docker.

2022-03-17 22:14 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +RKE1 uses Docker for deploying and managing control plane components and the container runtime for Kubernetes. By contrast, RKE2 launches control plane components such as static pods that are managed
Updated, thanks!

2022-03-17 22:15 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +You will notice that some terms have changed or gone away going from RKE1 to RKE2. For example, in RKE2, **node templates** have been deprecated, and you can configure your cluster nodes directly. An
Reworded, thanks!

2022-03-17 22:32 UTC, brandond approved these changes

2022-03-18 20:37 UTC, btat approved these changes

2022-03-18 20:51 UTC, thedadams approved these changes
Looks good. Definitely don't have to go with my suggestion. I don't know if we usually call these things out as bugs, but it may be worth noting that this is out of our control at the moment.

2022-03-18 20:51 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +- When nodes are being provisioned and a scale down operation is performed, rather than scaling down the desired number of nodes, it is possible that the currently provisioning nodes get deleted and
Would it be worth it to add: "This is a bug in Cluster API and they plan to fix it in an upcoming release. Once they do, Rancher will include these changes."

2022-03-18 20:53 UTC, catherineluse requested changes

2022-03-18 20:53 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +RKE1 uses Docker for deploying and managing control plane components, and it also uses Docker as the container runtime for Kubernetes. By contrast, RKE2 launches control plane components such as stat
sorry for this nitpick. but can we change 'such as' to 'as'?

> RKE2 launches control plane components as static pods

2022-03-18 20:53 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +You will notice that some terms have changed or gone away going from RKE1 to RKE2. For example, in RKE1 provisioning, you use **node templates**; in RKE2 provisioning, you can configure your cluster
> configure your cluster nodes directly.

can we be more specific about how to edit them? can we say

> you can configure your cluster node pools when creating or editing the cluster.

2022-03-18 21:08 UTC, catherineluse approved these changes
LGTM

2022-03-18 21:10 UTC, thedadams approved these changes

2022-03-18 21:11 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +RKE1 uses Docker for deploying and managing control plane components, and it also uses Docker as the container runtime for Kubernetes. By contrast, RKE2 launches control plane components such as stat
Updated, thanks!

2022-03-18 21:11 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +You will notice that some terms have changed or gone away going from RKE1 to RKE2. For example, in RKE1 provisioning, you use **node templates**; in RKE2 provisioning, you can configure your cluster
Updated, thanks!

2022-03-18 21:12 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/_index.md
> +- When nodes are being provisioned and a scale down operation is performed, rather than scaling down the desired number of nodes, it is possible that the currently provisioning nodes get deleted and
Updated, thank you!

2022-03-18 21:12 UTC, merged