Update rancher-webhook cert expiry
rancher/docs pull request #3951
Opened 2022-03-15 02:59 UTC by dkeightley

Based on the fix, update wording similar to https://github.com/rancher/rancher/issues/35068#issuecomment-1013501897

Please feel fee to adjust wording.

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-03-18 20:42 UTC, thedadams requested changes

2022-03-18 20:42 UTC, thedadams commented on content/rancher/v2.6/en/troubleshooting/expired-webhook-certificates/_index.md
> +New and existing rancher-webhook deployments will automatically renew its TLS certificate when it is 30 or fewer days within expiration date. If an older version is in use, there are two methods to w
"New and existing" is a little confusing. Is there a certain version of `rancher-webhook` that has this update functionality?

2022-07-26 23:37 UTC, dkeightley commented on content/rancher/v2.6/en/troubleshooting/expired-webhook-certificates/_index.md
> +New and existing rancher-webhook deployments will automatically renew its TLS certificate when it is 30 or fewer days within expiration date. If an older version is in use, there are two methods to w
Just a note, this should be `Rancher v2.5.12 and up` and `v2.5.11 or below`. I'll add the change now.

Ref: [v2.5.12 release notes](https://github.com/rancher/rancher/releases/tag/v2.5.12)
> New and existing rancher-webhook deployments will automatically renew their TLS certificates when the expiration date is 30 days or less. See https://github.com/rancher/rancher/issues/35068.

2022-07-28 13:26 UTC, jtravee approved these changes

2022-07-28 15:15 UTC, btat approved these changes

2022-07-28 15:15 UTC, merged