Improve restoration process requirements
rancher/docs pull request #3959
Opened 2022-03-16 08:32 UTC by Wykiki

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-03-16 14:21 UTC, jtravee commented
@jiaqiluo could you give a technical review of the above?

See also [#3530](https://github.com/rancher/docs/issues/3530).

2022-03-16 17:09 UTC, jiaqiluo requested changes

2022-03-16 17:09 UTC, jiaqiluo commented on content/rancher/v2.6/en/backups/migrating-rancher/_index.md
> +Once the Restore resource has the status `Completed`, you can continue the Rancher installation.
```suggestion
Watch the Restore status:
    ```
    kubectl get restore
    ```
Watch the restoration logs:
    ```
    kubectl logs -n cattle-resources-system --tail 100 -f rancher-backup-xxx-xxx
    ```

Once the Restore resource has the status `Completed`, you can continue the Rancher installation.
```

Those two steps are applicable for all scenarios, not only when using encryption. So I would suggest moving them to one level higher than the encryption block.

2022-03-17 09:32 UTC, Wykiki commented
I think I've updated the Markdown the correct way, but won't have time to test it locally until week-end.

2022-03-17 15:59 UTC, jiaqiluo approved these changes
LGTM.

2022-03-17 18:20 UTC, btat commented
Thank you for the contribution. The code blocks weren't rendering so I went ahead and fixed that.

2022-03-17 18:20 UTC, merged