Revert "Updating section for git-based chart repositories"
rancher/docs pull request #3968
Opened 2022-03-22 04:36 UTC by divya-mohan0209

Reverts rancher/docs#3892 per [this issue](https://github.com/rancher/rancher/pull/36983)

2022-03-22 04:38 UTC, divya-mohan0209 commented
@PennyScissors : Reverted the documentation change per request on [this issue](https://github.com/rancher/docs/issues/3864)

2022-03-22 14:12 UTC, jtravee requested changes

2022-03-22 14:12 UTC, jtravee commented on content/rancher/v2.6/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
```suggestion
- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Click **Edit YAML** for the chart repo and add the key/value pair as follows: 
```

2022-03-22 14:12 UTC, jtravee commented on content/rancher/v2.6/en/helm-charts/_index.md
> +- **Git-based chart repositories**: It is not currently possible to add a private CA. For git-based chart repositories with a certificate signed by a private CA, you must disable TLS verification. Cl
Minor nit.

2022-03-22 20:27 UTC, PennyScissors approved these changes

2022-03-23 04:50 UTC, divya-mohan0209 commented
Addressed the review by @jtravee + taking the approval from @PennyScissors, closing this PR.

2022-03-23 04:50 UTC, merged