Adding content to certificate rotation sections in v2.5 and v2.6
rancher/docs pull request #3969
Opened 2022-03-22 05:42 UTC by divya-mohan0209

Fixes #3960 

Content in the v2.0-2.4 docs has been copied as-is to v2.5 and 2.6.

Since this is not novel content, pushing it to master branch.

2022-03-22 17:10 UTC, catherineluse commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.2.x
The heading should just be Certificate Rotation.

2022-03-22 17:15 UTC, catherineluse requested changes

2022-03-22 17:15 UTC, catherineluse commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.1.x and v2.0.x
Delete this section because it doesn't apply to v2.5

2022-03-22 17:15 UTC, catherineluse commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +### Rotating Expired Certificates After Upgrading Older Rancher Versions
delete this section because we don't support skipping minor versions when upgrading Rancher

2022-03-22 17:15 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.2.x
should be just Certificate Rotation

2022-03-22 17:15 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +_Available as of v2.2.0_
delete this line

2022-03-22 17:15 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.1.x and v2.0.x
delete section

2022-03-22 17:15 UTC, catherineluse commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +### Rotating Expired Certificates After Upgrading Older Rancher Versions
delete section

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +### Rotating Expired Certificates After Upgrading Older Rancher Versions
Addressed in latest commit.

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.1.x and v2.0.x
Addressed in latest commit.

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +_Available as of v2.2.0_
Addressed in latest commit.

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.6/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.2.x
Addressed in latest commit.

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +### Rotating Expired Certificates After Upgrading Older Rancher Versions
Addressed in latest commit.

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.1.x and v2.0.x
Addressed in latest commit.

2022-03-23 05:00 UTC, divya-mohan0209 commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +_Available as of v2.2.0_
Addressed in latest commit.

2022-03-23 05:01 UTC, divya-mohan0209 commented on content/rancher/v2.5/en/cluster-admin/certificate-rotation/_index.md
> +### Certificate Rotation in Rancher v2.2.x
Addressed in latest commit.

2022-03-23 18:47 UTC, jtravee approved these changes

2022-03-28 08:55 UTC, divya-mohan0209 commented
@catherineluse / @watarumohawk : Please can you sign off so that I can merge these changes?

2022-03-28 08:59 UTC, watarumohawk approved these changes

2022-03-28 09:11 UTC, divya-mohan0209 commented
Merging the pull request, since requested changes have been addressed.

2022-03-28 09:11 UTC, merged