Extend airgapped Rancher installation tutorial for RKE2
rancher/docs pull request #3986
Opened 2022-03-28 16:15 UTC by bashofmann

The Rancher installation docs have a nice tutorial about installing Rancher in airgapped environments: https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/.

One part of this is how to install the Kubernetes cluster that Rancher runs in, in an airgapped way. This is currently only documented for RKE1 and K3s: https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/launch-kubernetes/.

RKE2 can also be installed airgapped: https://docs.rke2.io/install/airgap/.

Fixes https://github.com/rancher/docs/issues/3985

2022-06-14 22:59 UTC, brandond approved these changes

2022-06-16 13:40 UTC, jtravee requested changes
Please also update line 12 with `The steps to set up an air-gapped Kubernetes cluster on RKE, RKE2, or K3s are shown below.`

2022-06-16 13:40 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/air-gap/launch-kubernetes/_index.md
> +In this guide, we are assuming you have created your nodes in your air gapped environment and have a secure Docker private registry on your bastion server.
```suggestion
In this guide, we are assuming you have created your nodes in your air-gapped environment and have a secure Docker private registry on your bastion server.
```

2022-06-16 13:40 UTC, jtravee commented on content/rancher/v2.6/en/installation/other-installation-methods/air-gap/launch-kubernetes/_index.md
> +1. Download the new air-gap artefacts and install script from the [releases](https://github.com/rancher/rke2/releases) page for the version of RKE2 you will be upgrading to.
```suggestion
1. Download the new air-gap artifacts and install script from the [releases](https://github.com/rancher/rke2/releases) page for the version of RKE2 you will be upgrading to.
```

2022-06-17 14:15 UTC, bashofmann commented
Done. I added the missing RKE2 reference.

2022-06-17 15:03 UTC, jtravee approved these changes

2022-06-17 15:03 UTC, merged