Make amendments to the installation netowrking requirements
rancher/docs pull request #3994
Opened 2022-03-30 05:01 UTC by divya-mohan0209

Fixes #3991

2022-03-30 11:48 UTC, jordojordo requested changes
One small change from what I wrote in the issue, I think the property should be written as: 
`X-Frame-Options: DENY` 
[For reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#syntax)
Otherwise LGTM

2022-04-04 10:52 UTC, jordojordo approved these changes

2022-04-04 17:54 UTC, catherineluse requested changes
I think most Rancher users wouldn't know what the Ember UI is because it's in implementation detail. Can we say something like:

> If a server containing Rancher has the `X-Frame-Options: DENY` header, some pages in the new Rancher UI will not be able to render after upgrading from the legacy UI. This is because some legacy pages are embedded as iFrames in the new UI.

2022-04-05 09:32 UTC, divya-mohan0209 commented
> I think most Rancher users wouldn't know what the Ember UI is because it's in implementation detail. Can we say something like:
> 
> > If a server containing Rancher has the `X-Frame-Options: DENY` header, some pages in the new Rancher UI will not be able to render after upgrading from the legacy UI. This is because some legacy pages are embedded as iFrames in the new UI.

Addressed in the latest commit.

2022-04-06 20:53 UTC, catherineluse approved these changes

2022-04-07 04:14 UTC, merged