k3s: Update information about dual-stack
rancher/docs pull request #4010
Opened 2022-04-07 09:57 UTC by vadorovsky

Starting from k3s-io/k3s#5387, dual-stack and IPv6-only don't require
disabling network policy controller anymore - they can be used
regardless of IP family.

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-04-07 10:04 UTC, manuelbuil approved these changes

2022-04-18 17:26 UTC, dereknola approved these changes

2022-04-18 17:40 UTC, manuelbuil commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
You should remove the network policy enforcement part. I think it was referring to network policies in general

2022-04-18 17:40 UTC, manuelbuil requested changes
I missed one thing ;)

2022-04-18 17:51 UTC, manuelbuil commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
Actually, I would remove the whole `Node address auto-detection and network policy enforcement are not supported on dual-stack clusters when using the default flannel CNI`. Node address auto-detection does not work because kubelet just fetches the first IP that it finds, it has nothing to do with flannel CNI

2022-04-18 18:29 UTC, brandond commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
I would leave in the bit about node address auto-detection not being supported, but take out the language about flannel. That is an intentional limitation of the upstream Kubelet.

2022-04-19 13:32 UTC, vadorovsky commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
Fixed

2022-04-19 13:35 UTC, jtravee requested changes

2022-04-19 13:35 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
```suggestion
To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node address auto-detection is not supported on dual-stack clusters because kubelet fetches only the first IP address that it finds. Additionally, only vxlan backend is supported currently. This is an example of a valid configuration:
```

2022-04-19 15:23 UTC, vadorovsky commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
Fixed, thanks!

2022-04-19 16:24 UTC, brandond commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
> because kubelet fetches only the first IP address that it finds

Is this accurate? My understanding is that the Kubelet simply will not auto-detect IPv6 addresses, even in single-stack IPv6 configurations.  What about something like this:

```suggestion
To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes, and use the `vxlan` flannel backend. Node address auto-detection is not supported for IPv6 addresses; both servers and agents must provide valid dual-stack `node-ip` settings. This is an example of a valid configuration:
```

2022-04-20 09:44 UTC, manuelbuil commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
Michal is correct. Kubelet is able to auto-detect ipv6 addresses. When using this config in a ipv6-only env:
```
write-kubeconfig-mode: 644
token: "secret"
cluster-cidr: 2001:cafe:42:0::/56
service-cidr: 2001:cafe:42:1::/112
disable-network-policy: true
```
Things work and the node autodetects the ipv6 address correctly:
```
Addresses:
  InternalIP:  2a05:d012:c6f:4657:6c48:e448:971d:7487
  Hostname:    i-0dcde0f867f13a6e1
```

2022-04-21 17:16 UTC, brandond commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node ad
Oh, that's great. When I looked at it a couple releases back I thought upstream said they wouldn't detect ipv6 node IPs at all.

2022-04-21 17:16 UTC, brandond approved these changes

2022-04-21 17:35 UTC, jtravee approved these changes

2022-04-21 18:26 UTC, manuelbuil approved these changes

2022-04-21 18:40 UTC, merged