Add CIS Hardening Guide for 2.6x for RKE2 provisioned clusters
rancher/docs pull request #4016
Opened 2022-04-08 12:57 UTC by macedogm

This PR add a hardening guide for RKE2 provisioned clusters in Rancher. It must be merged to master when RKE2 provision is GA.

Release notes is needed.

Close https://github.com/rancher/rancher/issues/36629.

2022-04-08 13:27 UTC, macedogm commented
PR is ready, but marked as draft until QA can review it (CC @anupama2501).

2022-04-29 13:00 UTC, macedogm commented
Release note comment:

**Synopsis:** Add RKE2 hardening guide for Rancher provisioned RKE2 clusters.
**Resolved (or not):** It will be resolved in 2.6.5 with GA of Rancher provisioned RKE2 clusters.
**Status:** PR is in draft waiting from QA validation in https://github.com/rancher/rancher/issues/36629
**Versions:** 2.6.5

2022-05-11 02:30 UTC, btat commented on scripts/converters/headers/header-2.6-rke2.md
> +
@macedogm Is there supposed to be content in this section?

2022-05-11 09:23 UTC, macedogm commented on scripts/converters/headers/header-2.6-rke2.md
> +
@btat Yes, but this is used as a template when we create the assessment pages, like this one for example - https://rancher.com/docs/rancher/v2.6/en/security/hardening-guides/1.6-benchmark-2.6/ .

2022-05-11 14:59 UTC, btat commented on scripts/converters/headers/header-2.6-rke2.md
> +
Gotcha 👍

2022-05-11 20:58 UTC, anupama2501 commented on content/rancher/v2.6/en/cis-scans/_index.md
>  - EKS
@macedogm we haven't validated k3s completely as we have 1 more issue open. I think we should not include k3s here. Thoughts?

2022-05-11 22:28 UTC, anupama2501 requested changes

2022-05-11 22:39 UTC, anupama2501 requested changes

2022-05-11 22:39 UTC, anupama2501 commented on scripts/converters/headers/header-2.6-rke2.md
> +Where control audits differ from the original CIS benchmark, the audit commands specific to Rancher are provided for testing. When performing the tests, you will need access to the Docker command lin
`you will need access to the Docker command line` would this be `command line`?

2022-05-11 22:39 UTC, anupama2501 commented on scripts/converters/headers/header-2.6-rke2.md
> +Rancher and RKE2 install Kubernetes services via Docker containers. Configuration is defined by arguments passed to the container at the time of initialization, not via configuration files.
RKE2 uses containerd runtime

2022-05-11 22:39 UTC, anupama2501 commented on content/rancher/v2.6/en/security/hardening-guides/rke-1.6-hardening-2.6/_index.md
> +This document provides prescriptive guidance for hardening a RKE cluster to be used for installing Rancher v2.6 with Kubernetes v1.18 up to v1.21 or provisioning a RKE cluster with Kubernetes v1.18 u
k8s up to 1.23

2022-05-12 13:40 UTC, macedogm commented on content/rancher/v2.6/en/cis-scans/_index.md
>  - EKS
Agree. I'll remove the K3s reference and we update it with the other issue.

2022-05-12 13:44 UTC, macedogm commented on scripts/converters/headers/header-2.6-rke2.md
> +| Hardening Guide CIS v1.6 Benchmark | Rancher v2.6.5 | CIS v1.6 | Kubernetes v1.21 and v1.22 |
Fixed.

2022-05-12 13:47 UTC, macedogm commented on scripts/converters/headers/header-2.6-rke2.md
> +Where control audits differ from the original CIS benchmark, the audit commands specific to Rancher are provided for testing. When performing the tests, you will need access to the Docker command lin
Yes, we can mention only `command line` here.

2022-05-12 13:52 UTC, macedogm commented on scripts/converters/headers/header-2.6-rke2.md
> +Rancher and RKE2 install Kubernetes services via Docker containers. Configuration is defined by arguments passed to the container at the time of initialization, not via configuration files.
Fixed.

2022-05-12 15:10 UTC, macedogm commented
@anupama2501 I updated the PR with your comments.

2022-05-12 15:21 UTC, macedogm commented
PR https://github.com/rancherlabs/eio/issues/1016 to upload the hardening docs PDFs to Rancher's site.

2022-05-12 20:49 UTC, anupama2501 requested changes

2022-05-12 20:49 UTC, anupama2501 commented on content/rancher/v2.6/en/security/hardening-guides/_index.md
CIS scans should be applicable to v1.23 for standalone RKE2 as well here.

2022-05-13 13:40 UTC, anupama2501 approved these changes
lgtm

2022-05-13 16:18 UTC, btat commented
@macedogm should I wait for the EIO ticket for file uploads to be done first before merging this PR?

2022-05-13 18:09 UTC, macedogm commented
@btat the EIO issue is done now.

2022-05-13 18:11 UTC, merged