Amending Encryption Configuration Section
rancher/docs pull request #4018
Opened 2022-04-11 06:05 UTC by divya-mohan0209

Fixes #4008

2022-04-12 06:15 UTC, brandond requested changes
LGTM; one typo nit

2022-04-12 06:15 UTC, brandond commented on content/rancher/v2.6/en/backups/examples/_index.md
> +The snippet below demonstrates two different types of secrets and their relevance with respect to Backup and Restore of custom resources.s
```suggestion
The snippet below demonstrates two different types of secrets and their relevance with respect to Backup and Restore of custom resources.
```

2022-04-12 08:42 UTC, brandond approved these changes

2022-04-18 19:45 UTC, jtravee commented on content/rancher/v2.6/en/backups/examples/_index.md
> +The second example is that of a Kubernetes secrets encryption config file that is used to encrypt secrets when stored in etcd. It is important to note that while backing up your etcd config ensure yo
```suggestion
The second example is that of a Kubernetes secrets encryption config file that is used to encrypt secrets when stored in etcd. **While backing up your etcd config, be sure to also backup your EncryptionConfiguration.** Failing to do so might result in you not being able to use the restored data. 
```

2022-04-18 19:45 UTC, jtravee commented on content/rancher/v2.6/en/backups/examples/_index.md
> +The second example is that of a Kubernetes secrets encryption config file that is used to encrypt secrets when stored in etcd. It is important to note that while backing up your etcd config ensure yo
Suggestion to add emphasis to this warning.

2022-04-19 06:41 UTC, brandond commented on content/rancher/v2.6/en/backups/examples/_index.md
> +The second example is that of a Kubernetes secrets encryption config file that is used to encrypt secrets when stored in etcd. **While backing up your etcd config, be sure to also backup your Encrypt
```suggestion
The second example is that of a Kubernetes secrets encryption config file that is used to encrypt secrets when stored in etcd. **When backing up the etcd datastore, be sure to also back up the EncryptionConfiguration.** Failure to do so will result in an inability to use the restored data if secrets encryption was in use at the time the data was backed up.
```

2022-05-01 11:34 UTC, divya-mohan0209 commented
Since all typos & suggestions have been addressed, merging the PR. Please feel free to reopen if any concerns/if there's a need to revert.

2022-05-01 11:34 UTC, merged