Creating docs for creating VMware vSphere VM templates.
rancher/docs pull request #4029
Opened 2022-04-14 16:02 UTC by phillipsj

2022-04-21 20:44 UTC, jtravee requested changes

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +There a few different approaches that can be pursued at this step. You can manually create your VM by following [these instructions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.v
```suggestion

You may either manually create your VM or you can utilize [other alternatives](#alternatives-to-manual-creation) to create your VM.

## Manual Creation

 1. Manually create your VM by following [these instructions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-AE8AFBF1-75D1-4172-988C-378C35C9FAF2.html) from VMware. Once you have a VM running, you can manually install the dependency listed above to configure the VM correctly for the vSphere node driver.
 2. Customize as needed based on your specific environment and requirements. 
 3. Proceed with the final preparation before creating your template. 
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +## Alternatives to manual creation
```suggestion
## Alternatives to Manual Creation
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Alternatives to manual creation do exist and below is a list of tools that can assist.
```suggestion
Other alternative options to create VMs are listed below:
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Packer is often used and here is a good [reference](https://github.com/vmware-samples/packer-examples-for-vsphere) for usage with vSphere.
```suggestion
Packer is a frequently-used alternative. Refer to this [reference](https://github.com/vmware-samples/packer-examples-for-vsphere) for examples of its usage with vSphere. 
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Once you have a VM created with all the dependencies listed above and any additional items that are required, the most critical step is next. That step is preparing the VM to be turned into a templat
```suggestion
After creating a VM with all the required dependencies (and any additional required items), you must perform the most critical step next: preparing the VM to be turned into a template. This preparation will reset critical data such as the VM hostname, IPs, etc., to prevent that information from being brought into a new VM. If you fail to perform this step, you could create a VM with the same hostname, IP address, etc. 

Note that these preparatory steps differ between Linux and Windows.
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Here is how to achieve the different items that need reset.
```suggestion
The commands below will reset your VM in Linux:
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Windows has a utility called [sysprep](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation) that is used to generalize an image and reset
```suggestion
Windows has a utility called [sysprep](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation) that is used to generalize an image and reset the same items listed above for Linux. The command is as follows:
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +- [Template Creation](#template-creation)
```suggestion
- [Creating a Template](#creating-a-template)
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +- [Preparation](#preparation)
```suggestion
- [Preparing Your VM](#preparing-your-vm)
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +# Template Creation
```suggestion
# Creating a Template
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +# Preparation
```suggestion
# Preparing Your VM
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +To convert a VM to a template the first step is to shut down and stop the VM. Once it has been stopped, right-click on the VM in the inventory list and select Template. Then click on `Convert to Temp
```suggestion
1. Shut down and stop the VM.
2. Right-click on the VM in the inventory list and select **Template**. 
3. Click on **Convert to Template**. 

**Result:** Once the process has completed, a template will be available for use. 
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +* [VMware guide](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-5B3737CC-28DB-4334-BD18-6E12011CDC9F.html)
```suggestion
For additional information on converting a VM to a template, see the [VMware guide](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-5B3737CC-28DB-4334-BD18-6E12011CDC9F.html).
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +# Moving to a content library
```suggestion
# Moving to a Content Library
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Rancher has the ability to consume templates provided by a content library. Content libraries store and manage content within vSphere. Content libraries offer the ability to publish and share that co
```suggestion
Rancher has the ability to use templates provided by a content library. Content libraries store and manage content within vSphere, and they also offer the ability to publish and share that content. 
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +Here is a list of additional resources that may be useful.
```suggestion
Here is a list of additional resources that may be useful:
```

2022-04-21 20:44 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +
Below are some helpful links on content libraries:

2022-04-21 23:15 UTC, phillipsj commented
@jtravee thanks, I will get this turned around tomorrow.

2022-04-22 12:46 UTC, phillipsj commented
@jtravee changes have been implemented.

2022-04-26 15:55 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +There a few different approaches that can be pursued at this step. You can manually create your VM by following [these instructions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.v
`manually install the dependency listed` -> `dependencies`

2022-04-26 18:11 UTC, phillipsj commented
@btat @jtravee I guessed I missed a few updates. I have them all resolved now.

2022-04-26 20:14 UTC, jtravee requested changes

2022-04-26 20:14 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +1. Manually create your VM by following [these instructions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-AE8AFBF1-75D1-4172-988C-378C35C9FAF2.html) from VMware.
```suggestion
1. Manually create your VM by following [these instructions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-AE8AFBF1-75D1-4172-988C-378C35C9FAF2.html) from VMware. Once you have a VM running, you can manually install the dependencies listed above to configure the VM correctly for the vSphere node driver.
```

2022-04-26 20:14 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/_index.md
> +1. Manually create your VM by following [these instructions](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-AE8AFBF1-75D1-4172-988C-378C35C9FAF2.html) from VMware.
Just one more, thanks!

2022-04-26 20:25 UTC, phillipsj commented
@btat @jtravee Thanks for the reviews, I fixed the last one above.

2022-04-26 20:29 UTC, jtravee approved these changes

2022-04-26 20:29 UTC, merged