Make users aware of traefik problems
rancher/docs pull request #4036
Opened 2022-04-18 18:03 UTC by manuelbuil

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-04-18 21:14 UTC, jtravee requested changes

2022-04-18 21:14 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Note th
```suggestion
To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. 

Note that Traefik does not correctly handle ingress resources on a dual-stack cluster. As such, we recommend that users disable Traefik on K3s if they want dual-stack and instead use ingress-nginx. In addition, only vxlan backend is supported currently. The following is an example of a valid configuration:
```

2022-04-18 21:14 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Note th
We try not to reference GH issues as such in the docs; rather, we try and describe the ongoing issue and workaround for the users. We can add such issues to existing or upcoming release notes if desired/applicable.

2022-04-18 21:14 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
>  Dual-stack is supported on k3s v1.21 or above.
```suggestion
Dual-stack is supported on K3s v1.21 or above.
```

2022-04-18 21:14 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
>  IPv6 only setup is supported on k3s v1.22 or above. As in dual-stack operation, IPv6 node addresses cannot be auto-detected; all nodes must have an explicitly configured IPv6 `node-ip`. This is an ex
```suggestion
IPv6 only setup is supported on K3s v1.22 or above. As in dual-stack operation, IPv6 node addresses cannot be auto-detected; all nodes must have an explicitly configured IPv6 `node-ip`. This is an example of a valid configuration:
```

2022-05-05 06:08 UTC, manuelbuil commented
This is fixed with https://github.com/k3s-io/k3s/pull/5535. It was a code problem on our side

2022-05-05 06:08 UTC, closed without merging