Wireguard backend
rancher/docs pull request #4038
Opened 2022-04-19 10:19 UTC by rbrtbnfgl

Added new wireguard-native backend

2022-04-19 10:28 UTC, manuelbuil approved these changes

2022-04-19 13:32 UTC, jtravee requested changes

2022-04-19 13:32 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +The `wireguard` backend will be removed from v1.26 in favour of `wireguard-native` backend natively from flannel.
```suggestion
The `wireguard` backend will be removed from v1.26 in favor of `wireguard-native` backend natively from flannel.
```

2022-04-19 13:32 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +The `wireguard` backend will be removed from v1.26 in favour of `wireguard-native` backend natively from flannel.
Style choice on this!

2022-04-19 13:32 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +We recommend users to migrate to the new backend as soon as possible. The migration requires a short period of down-time while nodes come up with the new configuration. You should follow the followin
```suggestion
We recommend that users migrate to the new backend as soon as possible. The migration requires a short period of downtime while nodes come up with the new configuration. You should follow these two steps:
```

2022-04-19 13:32 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +1 - Update the k3s config in all control-plane nodes. The config file `/etc/rancher/k3s/config.yaml` should include `flannel-backend: wireguard-native` instead of `flannel-backend: wireguard`
```suggestion
1 - Update the K3s config in all control-plane nodes. The config file `/etc/rancher/k3s/config.yaml` should include `flannel-backend: wireguard-native` instead of `flannel-backend: wireguard`
```

2022-04-19 13:32 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> + <span style="white-space: nowrap">`--flannel-backend=wireguard`</span> | Uses the WireGuard backend which encrypts network traffic. May require additional kernel modules and configuration. [Deprecat
```suggestion
 <span style="white-space: nowrap">`--flannel-backend=wireguard`</span> | Uses the WireGuard backend which encrypts network traffic. May require additional kernel modules and configuration. (Deprecated and will be removed from version 1.26)|
```

2022-04-19 13:32 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> +To enable dual-stack in k3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr`, and set `disable-network-policy` on all server nodes. Both servers and agents must provide valid dual
```suggestion
To enable dual-stack in K3s, you must provide valid dual-stack `cluster-cidr` and `service-cidr`, and set `disable-network-policy` on all server nodes. Both servers and agents must provide valid dual-stack `node-ip` settings. Node address auto-detection and network policy enforcement are not supported on dual-stack clusters when using the default flannel CNI. Additionally, only vxlan and wireguard-native backends are supported currently. This is an example of a valid configuration:
```

2022-04-19 16:15 UTC, rancher-max commented
Before merging this, I'd like to have us finish validations on https://github.com/k3s-io/k3s/issues/5101 just to be sure. 
cc @VestigeJ to validate the scenario mentioned in these docs when validating the issue so that we can be sure it is correct.

2022-08-25 13:51 UTC, jtravee commented
Hi @rbrtbnfgl, please close this PR and transfer it over to https://github.com/k3s-io/docs instead.

2022-08-25 13:54 UTC, rbrtbnfgl commented
Ok I'll close. I already created a new PR here https://github.com/k3s-io/docs/pull/17

2022-08-25 13:54 UTC, closed without merging