Add ipv6-masq flag in docs
rancher/docs pull request #4040
Opened 2022-04-19 14:49 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-04-20 13:40 UTC, jtravee requested changes

2022-04-20 13:40 UTC, jtravee commented on content/k3s/latest/en/installation/network-options/_index.md
> + <span style="white-space: nowrap">`--flannel-ipv6-masq`</span> | Apply masquerading rules to IPv6 traffic (default for IPv4). Only applies on dual-stack or ipv6-only clusters |
```suggestion
 <span style="white-space: nowrap">`--flannel-ipv6-masq`</span> | Apply masquerading rules to IPv6 traffic (default for IPv4). Only applies on dual-stack or IPv6-only clusters |
```

2022-04-20 13:49 UTC, manuelbuil commented on content/k3s/latest/en/installation/network-options/_index.md
> + <span style="white-space: nowrap">`--flannel-ipv6-masq`</span> | Apply masquerading rules to IPv6 traffic (default for IPv4). Only applies on dual-stack or ipv6-only clusters |
thanks!

2022-04-21 17:33 UTC, jtravee approved these changes

2022-04-21 18:12 UTC, merged