Added NeuVector page, linked to Security page
rancher/docs pull request #4058
Opened 2022-04-27 14:45 UTC by jtravee

Closes #4046 

References: [NeuVector page](https://rancher.com/docs/rancher/v2.6/en/neuvector-integration/, [security docs](https://rancher.com/docs/rancher/v2.6/en/security)

2022-04-28 12:58 UTC, macedogm requested changes

2022-04-28 12:58 UTC, macedogm commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. In the Target section, select **Git repository containing Helm chart or cluster template definitions**. Then enter the index URL of https://github.com/selvamt94/charts.git and the branch **neuvect
Is this link correct? Should it be https://github.com/rancher/charts.git instead?

2022-04-28 13:18 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. In the Target section, select **Git repository containing Helm chart or cluster template definitions**. Then enter the index URL of https://github.com/selvamt94/charts.git and the branch **neuvect
Updated, ty!

2022-04-28 15:27 UTC, macedogm commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. In the Target section, select **Git repository containing Helm chart or cluster template definitions**. Then enter the index URL of https://github.com/rancher/charts.git and the branch **neuvector
@jtravee Were this instructions validated by QA? Just asking, because I couldn't find  branch `neuvector` in https://github.com/rancher/charts.git, but the chart is in https://github.com/rancher/charts/tree/dev-v2.6/charts/neuvector/100.0.0%2Bup2.2.0-b1.

2022-04-28 21:24 UTC, anupama2501 requested changes

2022-04-28 21:24 UTC, anupama2501 commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +
In addition we can also add the spec requirements for nuevctor chart installation. Default deployment (resources limit is not set)
Controller - 3 (1GB 1vCPUS needed per controller)
Enforcers - on all nodes (500MB .5vCPU)
Manager - 1 (500MB .5vCPU)
Scanner - 3 (100MB .5vCPU)

2022-04-29 18:09 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. In the Target section, select **Git repository containing Helm chart or cluster template definitions**. Then enter the index URL of https://github.com/rancher/charts.git and the branch **neuvector
Per QA, we can remove this line, so no need to specify!

2022-04-29 18:09 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. Go to the cluster where NeuVector is installed. In the left navigation bar, click **NeuVector**.
Revised as suggested.

2022-04-29 18:10 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +##### _Tech Preview_
Revised as suggested.

2022-04-29 18:10 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. In the Target section, select **Git repository containing Helm chart or cluster template definitions**. Then enter the index URL of https://github.com/rancher/charts.git and the branch **neuvector
Removed step as suggested.

2022-04-29 18:10 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +
Updated per feedback.

2022-04-29 18:10 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +
Added step.

2022-04-29 18:10 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +1. In the left navigation bar, click **NeuVector**.
Revised per feedback.

2022-04-29 18:10 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +
Added section.

2022-05-02 08:54 UTC, macedogm approved these changes

2022-05-02 22:58 UTC, anupama2501 reviewed
Added 1 comment lgtm otherwise.

2022-05-02 22:58 UTC, anupama2501 commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +
1 small change. Lets suggest the provided runtime engines as examples and can we also add the below runtime engines:
EKS runtime from 1.23+ - containerd and 1.22 and below - docker
GKE container runtime - containerd https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd
AKS container runtime - containerd for 1.19 and greater.

2022-05-03 15:32 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +
Updated as suggested, thanks!

2022-05-03 16:07 UTC, btat approved these changes

2022-05-03 16:16 UTC, anupama2501 approved these changes

2022-05-03 20:22 UTC, merged