Launch RKE2 + Azure
rancher/docs pull request #4066
Opened 2022-05-03 02:10 UTC by btat

Adds new tabs containing instructions sets (manual and cluster template) to launch RKE2 clusters on Azure.

2022-05-04 20:19 UTC, slickwarren requested changes

2022-05-04 20:40 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/azure/_index.md
> +1. Follow these [instructions]({{<baseurl>}}/rancher/v2.6/en/admin-settings/cluster-templates/#adding-a-cluster-template-to-rancher) to add a cluster template to Rancher.
The content in the rke2 cluster template section seems to only link/reference the repository containing the example templates whereas this section (and the content from the current link) is about making the template available for use in Rancher. If you could provide a bit more context that'd be great.

2022-05-05 23:05 UTC, slickwarren approved these changes

2022-05-05 23:05 UTC, slickwarren commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/azure/_index.md
> +1. Follow these [instructions]({{<baseurl>}}/rancher/v2.6/en/admin-settings/cluster-templates/#adding-a-cluster-template-to-rancher) to add a cluster template to Rancher.
Oh, you're right. I think I'd not copied the path completely and it just took me to the top of the page. What you have is good

2022-05-09 18:31 UTC, markusewalker approved these changes
LGTM.

2022-05-09 23:00 UTC, merged