Update language around scaling cases
rancher/docs pull request #4068
Opened 2022-05-03 13:45 UTC by cbron

2022-05-09 23:48 UTC, rmweir approved these changes

2022-05-11 16:22 UTC, jtravee requested changes

2022-05-11 16:22 UTC, jtravee commented on content/rancher/v2.0-v2.4/en/installation/requirements/_index.md
> +Every use case and environment is different, please [contact Rancher](https://rancher.com/contact/) to review yours.
```suggestion
Every use case and environment is different. Please [contact Rancher](https://rancher.com/contact/) to review yours.
```

2022-05-11 16:22 UTC, jtravee commented on content/rancher/v2.0-v2.4/en/installation/requirements/_index.md
> +Every use case and environment is different, please [contact Rancher](https://rancher.com/contact/) to review yours.
```suggestion
Every use case and environment is different. Please [contact Rancher](https://rancher.com/contact/) to review yours.
```

2022-05-11 16:22 UTC, jtravee commented on content/rancher/v2.5/en/installation/requirements/_index.md
> +Every use case and environment is different, please [contact Rancher](https://rancher.com/contact/) to review yours.
```suggestion
Every use case and environment is different. Please [contact Rancher](https://rancher.com/contact/) to review yours.
```

2022-05-11 16:22 UTC, jtravee commented on content/rancher/v2.5/en/installation/requirements/_index.md
> +Every use case and environment is different, please [contact Rancher](https://rancher.com/contact/) to review yours.
```suggestion
Every use case and environment is different. Please [contact Rancher](https://rancher.com/contact/) to review yours.
```

2022-05-11 16:22 UTC, jtravee commented on content/rancher/v2.6/en/installation/requirements/_index.md
> +Every use case and environment is different, please [contact Rancher](https://rancher.com/contact/) to review yours.
```suggestion
Every use case and environment is different. Please [contact Rancher](https://rancher.com/contact/) to review yours.
```

2022-05-11 16:22 UTC, jtravee commented on content/rancher/v2.6/en/installation/requirements/_index.md
> +Every use case and environment is different, please [contact Rancher](https://rancher.com/contact/) to review yours.
```suggestion
Every use case and environment is different. Please [contact Rancher](https://rancher.com/contact/) to review yours.
```

2022-05-11 22:15 UTC, jtravee approved these changes

2022-05-11 22:23 UTC, merged