Cluster Provisioning: added RKE2 section
rancher/docs pull request #4075
Opened 2022-05-05 14:28 UTC by nunix

Fixes #3752

Split the Cluster Provisioning between RKE and RKE2 documentation.

To keep a "reading standardization", both sections have the same sub-topics.

Once the structure is agreed, RKE2 content needs to be updated.

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-05-06 02:08 UTC, btat requested changes
The "Programmatically Creating RKE Clusters" section
- Needs to have a corresponding link for RKE2 (https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2)
-  This section should be moved to the bottom (so the RKE and RKE2 sections are sequential) OR this should be made into a subsection within each of the RKE and RKE2 sections

2022-05-06 02:08 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +If you use RKE to set up a cluster, your nodes must meet the [requirements](https://docs.rke2.io/install/requirements/) for nodes in downstream user clusters.
```suggestion
If you use RKE2 to set up a cluster, your nodes must meet the [requirements](https://docs.rke2.io/install/requirements/) for nodes in downstream user clusters.
```

2022-05-06 13:11 UTC, jtravee requested changes
Just a few nits on the original docs :)

2022-05-06 13:11 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- Calico CNI for Windows RKE2 custom clusters.
```suggestion
- Calico CNI for Windows RKE2 custom clusters
```

2022-05-06 13:11 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- SAC releases of Windows Server (2004 and 20H2) are included in the technical preview.
```suggestion
- SAC releases of Windows Server (2004 and 20H2) are included in the technical preview
```

2022-05-06 13:11 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- Calico CNI for Windows RKE2 custom clusters.
Just for consistency in the bullet points.

2022-05-06 14:08 UTC, nunix commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- Calico CNI for Windows RKE2 custom clusters.
Applied suggestion.

2022-05-06 14:08 UTC, nunix commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- SAC releases of Windows Server (2004 and 20H2) are included in the technical preview.
Applied suggestion.

2022-05-06 15:24 UTC, jtravee approved these changes

2022-05-09 20:33 UTC, anupama2501 requested changes

2022-05-11 12:37 UTC, nunix commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +RKE/RKE2 clusters include clusters that Rancher launched on Windows nodes or other existing custom nodes, as well as clusters that Rancher launched with new nodes on Azure, Digital Ocean, EC2, or vSp
Applied suggestion.

2022-05-11 12:42 UTC, nunix commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +
Applied suggestion.

2022-05-11 12:46 UTC, nunix commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- Provision RKE2 clusters on Digital Ocean, AWS EC2, Azure, and vSphere
Applied suggestion.

2022-05-11 20:10 UTC, btat approved these changes

2022-05-11 20:45 UTC, anupama2501 commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +
Rather than `Windows cluster` we can say `Cluster with windows nodes`

2022-05-12 11:34 UTC, nunix commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +
Applied suggestion.

2022-05-12 16:58 UTC, thedadams requested changes

2022-05-12 16:58 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +You can have Rancher launch a Kubernetes cluster using any nodes you want. When Rancher deploys Kubernetes onto these nodes, you can choose between [Rancher Kubernetes Engine]({{<baseurl>}}/rke/lates
The wording of this seems to imply that RKE2 is not a Rancher Kubernetes distribution. Can this be updated?

2022-05-12 16:58 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +The RKE2 provisioning also includes installing RKE2 on clusters with Windows nodes. Windows features for RKE2 include:
Windows nodes are currently only supported on custom clusters. Should this be moved to the "Existing Custom Nodes" section?

2022-05-12 16:58 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/_index.md
> +- At least two nodes with the role `control plane` for master component high availability
This section now has "control plane" in three different ways:
- `control plane`
- `controlplane`
- `control-plane`

Can these made uniform for this section?

2022-05-12 17:16 UTC, snasovich requested changes

2022-05-12 17:16 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +For more information, refer to the section on [custom nodes.]({{<baseurl>}}/rancher/v2.6/en/cluster-provisioning/rke-clusters/custom-nodes/)
`/rancher/v2.6/en/cluster-provisioning/rke-clusters/custom-nodes/` seems to be RKE1-specific yet we're referencing it from RKE2 section. Need to create new page for RKE2 or modify the referenced one to cover RKE2 case. Apologies if there is already a PR that addresses it and I have not seen it.

2022-05-12 17:16 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +If you want to reuse a node from a previous custom cluster, [clean the node]({{<baseurl>}}/rancher/v2.6/en/cluster-admin/cleaning-cluster-nodes/) before using it in a cluster again. If you reuse a no
The linked page is RKE1-specific as well. For example, https://rancher.com/docs/rancher/v2.6/en/cluster-admin/cleaning-cluster-nodes/#removing-a-node-from-a-cluster-by-rancher-ui explains automatic cleanup which is not yet happening in RKE2 case.

Technically one could use node previously used for RKE1 cluster for new RKE2 cluster in which case the linked section would apply.

But if we want to reuse node previously used for RKE2 cluster, that won't work. We're working on creating script to uninstall system-agent (https://github.com/rancher/system-agent/pull/82/files#diff-794e65e0ee6053d90c158cf942f93caee8a9fb1473830f1ccd660cf865c90828) plus one needs to also uninstall RKE2.

Given this is largely incomplete, I would recommend:
1. Removing the link and be intentionally vague with "clean the node"
1. Logging docs enhancement to expand this section on how to cleanup nodes previously used by RKE1/RKE2 (after we have the approach finalized for the latter).

```suggestion
If you want to reuse a node from a previous custom cluster, clean the node before using it in a cluster again. If you reuse a node that hasn't been cleaned, cluster provisioning may fail.
```

2022-05-12 17:16 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/_index.md
>  The implementation of the three node roles in Rancher means that Rancher managed RKE2 clusters are able to easily leverage all of the same architectural best practices that are recommended for RKE cl
Recommend moving this line right before the paragraph on "recommended cluster architecture" as it seems to flow  with the reasoning around RKE2 CLI vs. RKE2 in Rancher roles differences.

2022-05-12 19:11 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +You can have Rancher launch a Kubernetes cluster using any nodes you want. When Rancher deploys Kubernetes onto these nodes, you can choose between [Rancher Kubernetes Engine]({{<baseurl>}}/rke/lates
Updated to clarify as suggested.

2022-05-12 19:12 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +The RKE2 provisioning also includes installing RKE2 on clusters with Windows nodes. Windows features for RKE2 include:
Added a note to this note's existing placement to clarify the above. Ty!

2022-05-12 19:12 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/_index.md
> +- At least two nodes with the role `control plane` for master component high availability
Changed all to `controlplane` for consistency.

2022-05-12 19:12 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +You can have Rancher launch a Kubernetes cluster using any nodes you want. When Rancher deploys Kubernetes onto these nodes, you can choose between [Rancher Kubernetes Engine]({{<baseurl>}}/rke/lates
Removed phrase as suggested.

2022-05-12 19:13 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +Rancher v2.6 introduces provisioning for [RKE2](https://docs.rke2.io/) clusters directly from the Rancher UI. RKE2, also known as RKE Government, is a fully conformant Kubernetes distribution that fo
Added a note to clarify as suggested.

2022-05-12 19:13 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- Provision RKE2 clusters on Digital Ocean, AWS EC2, Azure, and vSphere
Revised note to reflect your suggestion.

2022-05-12 19:14 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +- SAC releases of Windows Server (2004 and 20H2) are included in the technical preview
Removed line entirely as per @sirredbeard 2004 has been dropped and 20H2 is about to be EOL.

2022-05-12 19:17 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +If you want to reuse a node from a previous custom cluster, [clean the node]({{<baseurl>}}/rancher/v2.6/en/cluster-admin/cleaning-cluster-nodes/) before using it in a cluster again. If you reuse a no
Removed link as suggested.

2022-05-12 19:17 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/_index.md
>  The implementation of the three node roles in Rancher means that Rancher managed RKE2 clusters are able to easily leverage all of the same architectural best practices that are recommended for RKE cl
Moved sentence as suggested.

2022-05-12 19:18 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +RKE/RKE2 clusters include clusters that Rancher launched on Windows nodes or other existing custom nodes, as well as clusters that Rancher launched with new nodes on Azure, Digital Ocean, EC2, vSpher
Removed paragraph.

2022-05-12 19:23 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +For more information, refer to the section on [custom nodes.]({{<baseurl>}}/rancher/v2.6/en/cluster-provisioning/rke-clusters/custom-nodes/)
Removed note entirely for the time being until a new page may be created to address this.

2022-05-12 20:36 UTC, anupama2501 approved these changes
lgtm

2022-05-12 23:21 UTC, thedadams commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +The RKE2 provisioning also includes installing RKE2 on clusters with Windows nodes. Windows features for RKE2 include:
I'm sorry, but I made a mistake. Windows nodes are supported outside of custom clusters. You can remove the note you created.

I am sorry for my mistake.

2022-05-12 23:28 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +The RKE2 provisioning also includes installing RKE2 on clusters with Windows nodes. Windows features for RKE2 include:
Removed, no problem!

2022-05-13 00:54 UTC, thedadams approved these changes

2022-05-13 15:44 UTC, snasovich approved these changes

2022-05-13 16:18 UTC, phillipsj commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +Windows Support for RKE2 Custom Clusters requires choosing Calico as the CNI.
Windows supports the vsphere node driver too.

2022-05-13 16:24 UTC, phillipsj submitted a review, later dismissed
Can we add that the vSphere node driver supports Windows? That is a key feature.

2022-05-13 17:34 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +Windows Support for RKE2 Custom Clusters requires choosing Calico as the CNI.
Added this new feature.

2022-05-13 17:35 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/_index.md
> +Windows features for RKE2 include:
Added vSphere node driver, PNI, and Terraform items as per Slack exchange.

2022-05-13 17:55 UTC, rosskirkpat approved these changes

2022-05-13 20:21 UTC, merged