Show example using installer
rancher/docs pull request #4076
Opened 2022-05-06 10:48 UTC by cawoodm

The current doc assumes that k3s is already installed.
As most users use the installer to initiate a cluster it is confusing not having an example with the installer.

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-05-19 14:51 UTC, dereknola requested changes
This is the correct way to use `--cluster-int` from the installer.

2022-05-19 14:51 UTC, dereknola commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +export INSTALL_K3S_VERSION=v1.23.6+k3s1
```suggestion
```
Including the version is unnecessary and confusing in this example.

2022-05-19 17:59 UTC, cawoodm commented on content/k3s/latest/en/installation/ha-embedded/_index.md
> +export INSTALL_K3S_VERSION=v1.23.6+k3s1
> This is the correct way to use `--cluster-int` from the installer.
Are you saying it's correct that `--cluster-init` is passed to the installer and embedded in the systemd config? So k3s is run with `--cluster-init` on one of my nodes each time that node starts??

2022-06-07 22:10 UTC, btat commented
Hi @dereknola , does this look good to merge now?

2022-06-07 22:42 UTC, dereknola approved these changes

2022-06-07 23:12 UTC, merged