Launch RKE2 + EC2
rancher/docs pull request #4084
Opened 2022-05-09 22:52 UTC by btat

Adds new tabs containing instructions sets (manual and cluster template) to launch RKE2 clusters on EC2.

2022-05-10 16:36 UTC, markusewalker approved these changes

2022-05-10 16:36 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/_index.md
> +1. Use the **Cluster Configuration** to choose the version of Kubernetes that will be installed, what network provider will be used and if you want to enable project network isolation.  For help conf
Removed. Thanks!

2022-05-11 20:28 UTC, sowmyav27 approved these changes

2022-05-11 20:33 UTC, sowmyav27 requested changes

2022-05-11 20:33 UTC, sowmyav27 commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-machine-config/_index.md
> +Add metadata using [tags](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html) to categorize resources.
There are a few more fields after this
- Auto Replace
- Drain before Delete
- Kubernetes Node labels
- Taints

2022-05-11 21:15 UTC, snasovich requested changes

2022-05-11 21:15 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-machine-config/_index.md
> +Add metadata using [tags](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html) to categorize resources.
@sowmyav27 , these would be general RKE2 features and not specific to infrastructure provider like EC2. So I think they should be specified in more generic RKE2 provisioning documentation.

2022-05-11 21:15 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/_index.md
> +{{% tab "RKE2 - Cluster Template" %}}
I would recommend not splitting out "RKE2 - Cluster Template" case for each individual node provider as it's largely the same approach regardless of specific provider and is (at least at high level) is covered under https://rancher.com/docs/rancher/v2.6/en/admin-settings/cluster-templates/

2022-05-11 21:15 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/_index.md
> +1. Configure your nodepools. For help with configurations, refer to the [EC2 Node Template Configuration](./ec2-node-template-config).
Node Templates are not applicable to RKE2 provisioning case, so we don't want to reference this doc. This is likely a moot point anyway as we probably want to remove this whole section as per previous comment.

2022-05-11 21:15 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-machine-config/_index.md
> +For more details about EC2, nodes, refer to the official documentation for the [EC2 Management Console](https://aws.amazon.com/ec2).
```suggestion
For more details about EC2 nodes, refer to the official documentation for the [EC2 Management Console](https://aws.amazon.com/ec2).
```

2022-05-11 21:15 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-machine-config/_index.md
> +The [Amazon Machine Image](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html) used to provision your cluster.
```suggestion
The [Amazon Machine Image](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html) used for the nodes in your cluster.
```

2022-05-11 21:17 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/_index.md
> +{{% tab "RKE2 - Cluster Template" %}}
If we proceed with this, will need to update it for https://github.com/rancher/docs/pull/4066 (already merged), https://github.com/rancher/docs/pull/4085, and any other cloud providers docs we do.

2022-05-11 21:36 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/_index.md
> +{{% tab "RKE2 - Cluster Template" %}}
Section removed. Will do the same for the other infra sections.

2022-05-11 23:13 UTC, anupama2501 commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-machine-config/_index.md
> +
`to your resources to.` we can remove the to at the end or do we want to add anything after to?

2022-05-11 23:16 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/ec2/ec2-machine-config/_index.md
> +
Typo fixed

2022-05-13 18:15 UTC, snasovich approved these changes

2022-05-13 18:36 UTC, merged