Launch RKE2 + DigitalOcean
rancher/docs pull request #4085
Opened 2022-05-09 22:52 UTC by btat

Adds new tabs containing instructions sets (manual and cluster template) to launch RKE2 clusters on DigitalOcean.

2022-05-11 20:35 UTC, sowmyav27 submitted a review, later dismissed

2022-05-11 20:35 UTC, sowmyav27 commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/do-machine-config/_index.md
> +### Droplet Tags
A few more params after this under `Advanced` section:
- Auto Replace
- Drain before delete
- Kubernetes Node Labels
- Taints

2022-05-11 21:23 UTC, snasovich requested changes

2022-05-11 21:23 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/_index.md
> +### 1. Create your cloud credentials
This is optional if DO credentials are not created yet, so probably a good idea is to mention this.

2022-05-11 21:23 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/_index.md
> +1. Enter a **Cluster Name**.
The UI prompts to select a Cloud Credential if there is more than one. Suggesting adding something like:
`1. Select "Cloud Credential" (if more than one exits; otherwise it's preselected`

This would apply to PRs for other infra providers.

2022-05-11 21:23 UTC, snasovich commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/_index.md
> +{{% tab "RKE2 - Cluster Template" %}}
Same as https://github.com/rancher/docs/pull/4084#discussion_r870758429

2022-05-11 21:42 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/_index.md
> +### 1. Create your cloud credentials
Mention added. Will add to other infra updates too.

2022-05-11 21:42 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/_index.md
> +1. Enter a **Cluster Name**.
Added

2022-05-11 21:43 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/do-machine-config/_index.md
> +### Droplet Tags
Omitting these additions per https://github.com/rancher/docs/pull/4084/files#r870754787

2022-05-11 21:43 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/digital-ocean/_index.md
> +{{% tab "RKE2 - Cluster Template" %}}
Section removed

2022-05-13 16:08 UTC, snasovich approved these changes

2022-05-13 16:22 UTC, merged