Rancher CLI not compatible with feature charts
rancher/docs pull request #4090
Opened 2022-05-11 01:37 UTC by btat

Closes https://github.com/rancher/docs/issues/4044

2022-05-11 16:18 UTC, jtravee approved these changes

2022-05-12 20:50 UTC, anupama2501 requested changes

2022-05-12 21:03 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
Add Neuvector and updated versions to the table

2022-05-12 21:15 UTC, anupama2501 commented on content/rancher/v2.6/en/helm-charts/_index.md
Following are the supported min versions of apps supported on rancher.
`rancher-alerting-drivers`: `100.0.2`
`rancher-backup`: `2.0.1`
`rancher-cis-benchmark`: `2.0.1`
`rancher-gatekeeper`: `100.0.1+up3.6.0`
`rancher-vsphere-cpi` no min version, only version available `100.3.0+up1.2.1`
`rancher-vsphere-csi` no min version, only version available `100.3.0+up2.5.1-rancher1`
`rancher-wins-upgrader` : `0.0.100`

2022-05-12 21:25 UTC, btat commented on content/rancher/v2.6/en/helm-charts/_index.md
Minimum versions updated

2022-05-12 21:27 UTC, anupama2501 approved these changes
LGTM :rocket:

2022-05-12 21:29 UTC, merged