Updating Private CA cert to Non-Private cert directions
rancher/docs pull request #4119
Opened 2022-05-24 21:56 UTC by jtravee

Closes #3680

Updated all versions.

2022-05-25 21:25 UTC, btat commented on content/rancher/v2.0-v2.4/en/installation/resources/update-rancher-cert/_index.md
> +>**CHANGE:** Delete the `tls-ca` secret as it is no longer needed. Note that you may optionally save a copy of the `tls-ca` secret if desired.
Is the `CHANGE` step a replacement to the `To create the initial secret/To update an existing tls-ca secret` steps or is it the next sequential step after those?

2022-05-25 21:25 UTC, btat commented on content/rancher/v2.0-v2.4/en/installation/resources/update-rancher-cert/_index.md
> +If the certificate was signed by a private CA, add the `set privateCA=true` argument as well. Also make sure to read the documentation describing the initial installation using custom certificates.
Shouldn't this part about adding `set privateCA=true` be removed since the new addition on line 253 says it should be omitted or set to false.

2022-05-26 22:21 UTC, btat requested changes

2022-05-26 22:21 UTC, btat commented on content/rancher/v2.0-v2.4/en/installation/resources/update-rancher-cert/_index.md
> +> Before proceeding, generate an API token in the Rancher UI (<b>User > API & Keys</b>) and save the Bearer Token which you might need in step 4.
We could link to the page with instructions at https://rancher.com/docs/rancher/v2.6/en/user-settings/api-keys/#creating-an-api-key

2022-05-26 22:21 UTC, btat commented on content/rancher/v2.0-v2.4/en/installation/resources/update-rancher-cert/_index.md
> +After upgrade is completed, the `privateCA` parameter <b>must</b> be either removed or set to `false` because the CA is valid:
This was "On upgrade" in an earlier commit, is this change intended?

2022-05-31 16:58 UTC, btat commented on content/rancher/v2.0-v2.4/en/installation/resources/update-rancher-cert/_index.md
> +After upgrade is completed, the `privateCA` parameter <b>must</b> be either removed or set to `false` because the CA is valid:
I would say so because the info about setting `set privateCA=false`/omitting `privateCA` are relevant when running `helm upgrade`.

2022-05-31 21:56 UTC, jtravee commented on content/rancher/v2.0-v2.4/en/installation/resources/update-rancher-cert/_index.md
> +> Before proceeding, generate an API token in the Rancher UI (<b>User > API & Keys</b>) and save the Bearer Token which you might need in step 4.
Updated with links.

2022-05-31 23:52 UTC, btat approved these changes

2022-05-31 23:52 UTC, merged