[Rancher] Restructure ingress controller docs on Rancher installation page
rancher/docs pull request #4133
Opened 2022-06-03 14:11 UTC by bashofmann

* Make it clearer in which cases you need to install an additional ingress controller and in which you don't
* Move Ingress Controller docs closer to the cluster provisioning docs
* Move hosted kubernetes cluster docs to k8s-tutorial so that they are next to the RKE, RKE2 and K3s docs in the menu
* Clearly distinguish between ingress and ingress controller

Fixes https://github.com/rancher/docs/issues/4109

2022-06-03 14:12 UTC, bashofmann commented
@jtravee here is the promised PR to address the feedback from https://github.com/rancher/docs/issues/4109. It would be great, if you could have a look.

Somehow related to this is also this PR that still needs attention: https://github.com/rancher/docs/pull/4065

2022-06-06 13:35 UTC, jtravee requested changes

2022-06-06 13:35 UTC, jtravee commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +For RKE, RKE2 and K3s installations, you don't have to install the Ingress controller manually because one is installed by default.
```suggestion
For RKE, RKE2, and K3s installations, you don't have to install the Ingress controller manually because one is installed by default.
```

2022-06-06 13:35 UTC, jtravee commented on content/rancher/v2.6/en/installation/install-rancher-on-k8s/_index.md
> +Examples are included in the **Amazon EKS**, **AKS** and **GKE** tutorials above.
```suggestion
Examples are included in the **Amazon EKS**, **AKS**, and **GKE** tutorials above.
```

2022-06-10 13:41 UTC, jtravee approved these changes

2022-06-10 13:41 UTC, merged