Update K3s Agent Configuration Reference CLI
rancher/docs pull request #4134
Opened 2022-06-03 16:15 UTC by carlocorradini

Some (new) CLI options were missing in K3S Agent configuraion reference CLI.

Moreover, I think that configuration via file (`--config`) needs a dedicated section since neither the server nor the agent have it.

2022-06-03 18:45 UTC, brandond approved these changes
We do have some documentation available on the config file at https://rancher.com/docs/k3s/latest/en/installation/install-options/#configuration-file

..but since it's just a yaml-ification of the CLI options it's pretty minimal. There have been some enhancements to it (tricks you can play with key suffixes, conf.d directory support) that aren't currently documented: 
* https://github.com/k3s-io/k3s/pull/3229
* https://github.com/k3s-io/k3s/pull/3162

2022-06-04 08:24 UTC, carlocorradini commented
@brandond 

I said that badly, for section I meant something like this (but for configuration):
![immagine_2022-06-04_102348734](https://user-images.githubusercontent.com/21266147/171991254-40cb3f0d-7a27-49e4-90e5-ef62a6c66155.png)

2022-06-07 21:17 UTC, btat requested changes
@carlocorradini Thanks for your contribution. The corresponding "sections" will also need to be updated to remain in sync with the removals/additions made to the CLI section in this PR. 

It also looks like some options that are now available (e.g., the various `(agent/node)` ones) have not been included while others that still exist (e.g., the `cluster` ones) have been removed.

2022-06-08 08:05 UTC, carlocorradini commented on content/k3s/latest/en/installation/install-options/agent-config/_index.md
> -   --server value, -s value            (cluster) Server to connect to [$K3S_URL]
K3s `v1.23.6+k3s1 (418c3fa8)` agent flags (`k3s agent --help`):
![agent_cli_flags](https://user-images.githubusercontent.com/21266147/172564747-741304b7-06c8-432e-931c-c0a8e473f737.png)

2022-06-08 08:05 UTC, carlocorradini commented on content/k3s/latest/en/installation/install-options/agent-config/_index.md
> -   --server value, -s value            (cluster) Server to connect to [$K3S_URL]
@btat What is missing?

2022-06-08 23:37 UTC, btat approved these changes

2022-06-08 23:37 UTC, merged