Update API tokens page to explain new rancher settings.
rancher/docs pull request #4140
Opened 2022-06-07 19:04 UTC by KevinJoiner

Related to #4139 & rancher/rancher#37703

2022-06-07 20:10 UTC, btat submitted a review, later dismissed

2022-06-07 20:10 UTC, btat commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +_**Note:**_ This setting is used by all kubeconfig tokens except those created by the CLI to [generate kubeconfig tokens](#disable-token-generation-for-downloaded-kubeconfigs).
```suggestion
> **Note:** This setting is used by all kubeconfig tokens except those created by the CLI to [generate kubeconfig tokens](#disable-token-generation-for-downloaded-kubeconfigs). 
```

2022-06-07 20:10 UTC, btat commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +### Disable Token Generation for Downloaded Kubeconfigs.
```suggestion
### Disable Token Generation for Downloaded Kubeconfigs
```

2022-06-07 20:10 UTC, btat commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +These global settings affect rancher token behavior.
```suggestion
These global settings affect Rancher token behavior.
```

2022-06-07 20:10 UTC, btat commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +| [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes) |Default TTL applied to all kubeconfig tokens.|
```suggestion
| [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes) | Default TTL applied to all kubeconfig tokens.|
```

2022-06-08 23:13 UTC, cbron requested changes

2022-06-08 23:13 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +Admins can set a global TTL on Kubeconfig tokens. Once the token expires, the kubectl command will require the user to authenticate to Rancher. Changing the default kubeconfig TTL can be done by navi
On this part `the kubectl command will require the user to authenticate to Rancher`, they would just have generic kubeconfigs with a token that is expired, so nothing would necessarily suggest the user re-authenticates to rancher, it just wouldn't work right ? If so I would just remove that whole line. 

```suggestion
Admins can set a global TTL on Kubeconfig tokens. Changing the default kubeconfig TTL can be done by navigating to global settings and setting [`kubeconfig-default-token-ttl-minutes`](#kubeconfig-default-token-ttl-minutes) to the desired duration in minutes. The default value of [`kubeconfig-default-token-ttl-minutes`](#kubeconfig-default-token-ttl-minutes) is 0, which means tokens never expire.
```

2022-06-08 23:13 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +### Disable Token Generation for Downloaded Kubeconfigs.
```suggestion
### Disable Tokens in Generated Kubeconfigs
```

2022-06-08 23:13 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +_**Note:**_ CLI authentication is currently only valid for the following authProviders: Local, KeyCloak, Ping, ADFS, Okta, Shibboleth, FreeIPA, OpenLDAP, ActiveDirectory
If I remember, this is actually about SAML vs not SAML, right ? We should leave it at that instead. Some of these, such as keycloak, also support other auth methods like OIDC which would not allow CLI login.

2022-06-08 23:13 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +While true kubeconfigs requested through the UI will contain a valid token, if this setting is false, the kubeconfig will execute the CLI to prompt the user to log-in and retrieve a kubeconfig with a
```suggestion
When true, kubeconfigs requested through the UI will contain a valid token. When false, the kubeconfig will execute the CLI to prompt the user to log-in and retrieve a kubeconfig with a token. **Currently only valid for the following authProviders: Local, KeyCloak, ping, adfs, okta, shibboleth, freeIPA, openLDAP, activeDirectory**
```

2022-06-08 23:14 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +### Token Settings
This is great though, thanks for adding, I will personally be using this docs page a lot in the future 😄

2022-06-09 02:12 UTC, KevinJoiner commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +### Token Settings
Thanks!

2022-06-13 21:20 UTC, rmweir requested changes

2022-06-13 21:20 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +1. Set the `kubeconfig-generate-token` setting to `false`. This setting instructs Rancher to no longer automatically generate a token when a user clicks on download a kubeconfig file. The kubeconfig
I think `The kubeconfig file will now provide a command to log in to Rancher.` and `Once this setting is deactivated, a generated kubeconfig will reference the [Rancher CLI]({{<baseurl>}}/rancher/v2.6/en/cli) to retrieve a short-lived token for the cluster.` are somewhat redundant. The first sentence is probably unnecessary since the following sentences explain the use of the CLI instead and that the user will need to log in.

2022-06-13 21:20 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +| [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes) | Default TTL applied to all kubeconfig tokens. |
```suggestion
| [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes) | Default TTL applied to all kubeconfig tokens except those generate by Rancher CLI. |
```

2022-06-13 21:20 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +| [`auth-token-max-ttl-minutes`](#auth-token-max-ttl-minutes) | Max TTL for all authentication tokens. |
Do we explain somewhere the difference between auth user sessions tokens, auth tokens, and regular tokens or which ones overlap?

2022-06-13 21:20 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +**Deprecated: This setting will be replaced with the value of [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes).**
Include when this will take place.

2022-06-13 21:20 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +When true, kubeconfigs requested through the UI will contain a valid token. When false, the kubeconfig will execute the CLI to prompt the user to log-in and retrieve a kubeconfig with a token. **Curr
The CLI caches the token but the kubeconfig doesn't change to having the token embedded. It still just has the command:
```suggestion
When true, kubeconfigs requested through the UI will contain a valid token. When false, the kubeconfig will contain a command that uses the Rancher CLI to prompt the user to log-in. The CLI then will retrieve and cache a token for the user. **Currently only valid for the following protocols: LDAP, SAML, and Local.**
```

2022-06-14 14:54 UTC, KevinJoiner commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +| [`auth-token-max-ttl-minutes`](#auth-token-max-ttl-minutes) | Max TTL for all authentication tokens. |
We do not have that explanation. Maybe because tokens are not handled differently by Rancher authentication. The differences only appear in how the tokens are created. I can add to setting descriptions to highlight these differences.

2022-06-15 20:13 UTC, rmweir requested changes

2022-06-15 20:13 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +| [`auth-token-max-ttl-minutes`](#auth-token-max-ttl-minutes) | Max TTL for all authentication tokens. |
For example, `auth-user-session-ttl-minutes` only effects tokens for UI sessions right? I think that along with the alternation between saying `tokens` and `authentication tokens` can be confusing.

2022-06-15 20:13 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +**Deprecated: This setting will be replaced with the value of [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes).**
Still need to address.

2022-06-15 20:13 UTC, rmweir commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +| [`kubeconfig-token-ttl-minutes`](#kubeconfig-token-ttl-minutes) | TTL used for tokens generated via the CLI.  **Deprecated** This setting will be removed, and `kubeconfig-default-token-TTL-minutes`
Still need to address.

2022-06-24 19:42 UTC, rmweir requested changes
For the deprecated comments I meant to include the version in which the settings will be removed or no longer functional. Not the deprecation version, my bad.

2022-07-27 23:17 UTC, cbron reviewed
Almost there!

2022-07-27 23:17 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +> **Note:** CLI authentication is currently only valid for the following protocols: LDAP, SAML, and Local.
Is that accurate ? I thought it was only SAML. Our docs should already specify this. One line below to adjust too.

2022-07-27 23:17 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +> **Note:** CLI authentication is currently only valid for the following protocols: LDAP, SAML, and Local.
I would actually link out to the section that specifies which are supported to avoid updating in lots of places as time goes on: https://rancher.com/docs/rancher/v2.5/en/cli/#authentication-with-kubectl-and-kubeconfig-tokens-with-ttl

2022-08-01 17:24 UTC, rmweir approved these changes
LGTM!

2022-08-01 19:15 UTC, cbron commented on content/rancher/v2.6/en/api/api-tokens/_index.md
> +> **Note:** CLI authentication is currently only valid for the following protocols: LDAP, SAML, and Local.
Looks like this was removed.

2022-08-01 19:17 UTC, cbron approved these changes

2022-08-09 15:39 UTC, btat approved these changes
lgtm

2022-08-10 18:42 UTC, merged