added basic instructions on BYOC
rancher/docs pull request #4153
Opened 2022-06-13 03:51 UTC by mxplusb

Added basic instructions for how to generate your own root or intermediate CAs based off information in k3s#1868

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-06-21 01:39 UTC, btat submitted a review, later dismissed

2022-06-23 00:13 UTC, mxplusb commented
@btat updated!

2022-06-27 23:47 UTC, brandond requested changes
Thank you for the contribution! 

I suggested a couple changes to the wording to highlight the fact that these steps should only be done before bringing up the cluster.

An additional two CAs are required for use with embedded etcd; would you care to include those in this as well?

2022-06-27 23:47 UTC, brandond commented on content/k3s/latest/en/advanced/_index.md
> +export ROOT_DOMAIN="you-domain-here.com"
Use a RFC 2606 reserved domain for documentation:
```suggestion
export ROOT_DOMAIN="example.com"
```

2022-06-27 23:47 UTC, brandond commented on content/k3s/latest/en/advanced/_index.md
> +If you want to handle your own TLS chains, you can provide your own root or intermediate CA certificates to replace the default CAs which K3s generates on installation. You can find more discussions
```suggestion

> It is important to perform these steps on the first server in the cluster before starting K3s for the first time. Making changes to cluster Root Certificate Authority certificates after the cluster has been brought up may render it unusable.

If you want to use custom Certificate Authority data, you can provide your own root or intermediate CA certificates in place of the default CAs which K3s generates on installation. You can find more discussions and references in [k3s#1868](https://github.com/k3s-io/k3s/issues/1868). 
```

2022-06-28 15:27 UTC, mxplusb commented
> Thank you for the contribution!
> 
> I suggested a couple changes to the wording to highlight the fact that these steps should only be done before bringing up the cluster.
> 
> An additional two CAs are required for use with embedded etcd; would you care to include those in this as well?

I included those, thanks!

2022-06-28 18:10 UTC, brandond commented
>>An additional two CAs are required for use with embedded etcd; would you care to include those in this as well?
> I included those, thanks!

I'm not seeing the etcd CAs mentioned, did those changes get pushed?

2022-08-25 16:07 UTC, jtravee commented
Hi @mxplusb, please close this PR and create a new one at https://github.com/k3s-io/docs instead. Thanks!

2022-09-06 05:35 UTC, mxplusb commented
I wont be making further improvements to the PR as I've run out of time

2022-09-06 05:35 UTC, closed without merging