Called out lack of additional logic around default Kubernetes service extra_args
rancher/docs pull request #4165
Opened 2022-06-22 15:58 UTC by jtravee

Closes #4142 

Reference: [`extra_args` section](https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-args)

2022-06-23 19:21 UTC, btat requested changes

2022-06-23 19:21 UTC, btat commented on content/rke/latest/en/config-options/services/services-extras/_index.md
> +#### Defining Additional Arguments Manually
The header should be about (the lack of) additional logic.

2022-06-23 19:21 UTC, btat commented on content/rke/latest/en/config-options/services/services-extras/_index.md
> +- It is possible for users to add additional arguments on the default Kubernetes services in the RKE cluster configuation YAML. RKE will add these arguments to the components **without** any addition
The first sentence is not needed since it's describing what extra_args does, which is already done in the intro sentence of the `### Extra Args` parent section.

2022-06-23 20:12 UTC, jtravee commented on content/rke/latest/en/config-options/services/services-extras/_index.md
> +#### Defining Additional Arguments Manually
Rephrased header.

2022-06-23 20:12 UTC, jtravee commented on content/rke/latest/en/config-options/services/services-extras/_index.md
> +- It is possible for users to add additional arguments on the default Kubernetes services in the RKE cluster configuation YAML. RKE will add these arguments to the components **without** any addition
Removed.

2022-06-30 13:58 UTC, axeal approved these changes

2022-06-30 15:58 UTC, btat approved these changes

2022-06-30 15:59 UTC, merged