Created new doc for MS Graph API; updated new install steps; added migration and reversion steps
rancher/docs pull request #4211
Opened 2022-07-20 17:04 UTC by jtravee

Closes #4047

Reference: [Configuring Azure AD docs](https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/)

2022-07-20 19:13 UTC, btat requested changes

2022-07-20 19:13 UTC, btat commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +> New users (and existing users who wish to migrate) should refer to the new flow instructions on the <a href="https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/#microso
We also need a blurb about using a different authentication provider for cases where an upgrade to 2.6.7 is not wanted.

2022-07-20 19:13 UTC, btat commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +>**Important to Note:** It can take up to five minutes for this change to take affect, so don't be alarmed if you can't authenticate immediately after Azure AD configuration.
```suggestion
>**Important:** It can take up to five minutes for this change to take affect, so don't be alarmed if you can't authenticate immediately after Azure AD configuration.
```

2022-07-20 21:24 UTC, jtravee commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +>**Important to Note:** It can take up to five minutes for this change to take affect, so don't be alarmed if you can't authenticate immediately after Azure AD configuration.
Updated as suggested.

2022-07-20 21:25 UTC, jtravee commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +> New users (and existing users who wish to migrate) should refer to the new flow instructions on the <a href="https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/#microso
Added as suggested.

2022-07-20 22:37 UTC, btat approved these changes

2022-07-22 15:53 UTC, maxsokolovsky commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +#### 5. Configure Azure AD in Rancher
I think we shouldn't say that users must manually enter Graph, Auth, Token endpoints.
Instead, we should emphasize the two choices - Standard and China (in the radio button). With those, users just enter the Tenant ID, Application ID, Application Secret. Rancher takes care of the rest. This is the UI flow through which most users will go.

Specifying Graph, Auth, Token endpoints (in addition to Tenant ID, Application ID, Application Secret) is for Custom endpoints, which are not fully tested by Rancher.

Most users use Standard (aka Global) and China clouds, and Rancher knows what values should be set for Graph, Auth, Token endpoints, users hardly need to know about them.

2022-07-25 22:38 UTC, maxsokolovsky commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
>  1. Complete the **Configure Azure AD Account** form using the information you copied while completing [Copy Azure Application Data](#4-copy-azure-application-data).
Could we have a screenshot here from the Rancher UI where there are three input fields?

2022-07-26 18:30 UTC, maxsokolovsky commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +#### Reverting the Migration
We should say that "Reverting this migration is not recommended, and should only be attempted in extenuating circumstances. Directions must be followed exactly to avoid service interruptions".

2022-07-27 13:25 UTC, jtravee commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +#### 5. Configure Azure AD in Rancher
Rephrased such that the standard endpoints are made distinct from the custom endpoints; added caveat that custom endpoints aren't supported/fully tested.

2022-07-27 13:25 UTC, jtravee commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +#### Reverting the Migration
Added as suggested.

2022-07-27 17:28 UTC, btat approved these changes

2022-07-27 21:05 UTC, maxsokolovsky commented on content/rancher/v2.5/en/admin-settings/authentication/azure-ad/_index.md
> +1. When you receive the popup message, click **Update**.
This step and the next need to be reversed. Admins will first see the Update Endpoint button, then the popup with the Update button.

2022-07-27 21:06 UTC, maxsokolovsky commented on content/rancher/v2.5/en/admin-settings/authentication/azure-ad/_index.md
> +-----------------| -------------------------------------------------------------
Nit: for some reason, the widths of the first column (indicated by the vertical line) in all four tables are different.

2022-07-28 19:28 UTC, jtravee commented on content/rancher/v2.5/en/admin-settings/authentication/azure-ad/_index.md
> +1. When you receive the popup message, click **Update**.
Corrected, thanks!

2022-07-28 19:28 UTC, jtravee commented on content/rancher/v2.5/en/admin-settings/authentication/azure-ad/_index.md
> +-----------------| -------------------------------------------------------------
I updated the MD, but the tables still render a bit uneven...

2022-07-28 19:29 UTC, jtravee commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
>  1. Complete the **Configure Azure AD Account** form using the information you copied while completing [Copy Azure Application Data](#4-copy-azure-application-data).
Added as requested.

2022-07-28 20:52 UTC, maxsokolovsky commented on content/rancher/v2.5/en/admin-settings/authentication/azure-ad/_index.md
> +    ![Rancher UI Banner]({{<baseurl>}}/img/rancher/rancher-ui-azure-update.png)
This screenshot is from v2.6, but should be the v2.5 one.

2022-07-28 20:57 UTC, maxsokolovsky commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +    ![Application ID]({{<baseurl>}}/img/rancher/application-id.png)
This screenshots highlights in red the `Application ID URI` field, which is not what the user would need. Instead, it should highlight the `Application (client) ID` field just to the left and above. The same happens in the v2.5 version of the docs.

2022-08-01 15:37 UTC, jtravee commented on content/rancher/v2.5/en/admin-settings/authentication/azure-ad/_index.md
> +    ![Rancher UI Banner]({{<baseurl>}}/img/rancher/rancher-ui-azure-update.png)
Updated with the 2.5 banner.

2022-08-01 15:37 UTC, jtravee commented on content/rancher/v2.6/en/admin-settings/authentication/azure-ad/_index.md
> +    ![Application ID]({{<baseurl>}}/img/rancher/application-id.png)
Updated as suggested.

2022-08-12 19:03 UTC, maxsokolovsky approved these changes

2022-08-12 19:10 UTC, merged