add windows workload migration guidance doc
rancher/docs pull request #4217
Opened 2022-07-21 01:52 UTC by rosskirkpat

https://github.com/rancher/windows/issues/110
https://github.com/rancher/windows/issues/17

SURE-4703
SURE-4546
SURE-4616

2022-07-21 15:08 UTC, jtravee requested changes

2022-07-21 15:08 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +Pre-Migration RKE1 Windows Deployment
```suggestion
Pre-migration RKE1 Windows deployment
```

2022-07-21 15:08 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +Migrated RKE2 Windows Deployment Using `NodeAffinity`
```suggestion
Migrated RKE2 Windows deployment using `NodeAffinity`
```

2022-07-21 15:08 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +Referencing the tables in [Rancher 2.5 vs. Rancher 2.6 Support Matrix for Windows Clusters](#rancher-25-vs-rancher-26-support-matrix-for-windows-clusters) and [Rancher 2.5 vs Rancher 2.6 Supported Ku
```suggestion
Referencing the tables in [Rancher 2.5 vs. Rancher 2.6 Support Matrix for Windows Clusters](#rancher-25-vs-rancher-26-support-matrix-for-windows-clusters) and [Rancher 2.5 vs. Rancher 2.6 Supported Kubernetes Versions for Provisioning RKE1 and RKE2 Windows Clusters](#rancher-25-vs-rancher-26-supported-kubernetes-versions-for-provisioning-rke1-and-rke2-windows-clusters), you will find the overlap in Kubernetes versions between RKE1 and RKE2 occurs in 1.22. This will be the base version required to migrate RKE1 Windows workloads when following the Rancher recommended approach.
```

2022-07-21 15:08 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +    - [1.4.2. Rancher 2.5 vs Rancher 2.6 Supported Kubernetes Versions for Provisioning RKE1 and RKE2 Windows Clusters](#142-rancher-25-vs-rancher-26-supported-kubernetes-versions-for-provisioning-rk
```suggestion
    - [1.4.2. Rancher 2.5 vs. Rancher 2.6 Supported Kubernetes Versions for Provisioning RKE1 and RKE2 Windows Clusters](#142-rancher-25-vs-rancher-26-supported-kubernetes-versions-for-provisioning-rke1-and-rke2-windows-clusters)
```

2022-07-21 15:08 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +      - [2.1.2.1. Use matching Kubernetes patch versions for RKE and RKE2](#2121-use-matching-kubernetes-patch-versions-for-rke-and-rke2)
```suggestion
      - [2.1.2.1. Use matching Kubernetes patch versions for RKE1 and RKE2](#2121-use-matching-kubernetes-patch-versions-for-rke-and-rke2)
```

2022-07-21 15:08 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +      - [2.1.2.1. Use matching Kubernetes patch versions for RKE and RKE2](#2121-use-matching-kubernetes-patch-versions-for-rke-and-rke2)
Keeping consistency as everywhere else, RKE1 is used...

2022-07-21 16:03 UTC, jtravee requested changes
Just comments on the alignment of a few sections...

2022-07-21 16:03 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +      - [1.2.1. RKE1 to RKE2 Windows Workload](#121-rke1-to-rke2-windows-workload)
This goes with the above; it should just be brought in to align under the `1.1.1.` header level if it's under a new section, or if it's a subheader of `1.1.3.`, then it would be `1.1.3.1`.

2022-07-21 18:48 UTC, btat requested changes
I did a test build and it seems some of these are not supported with our Hugo setup and appear as plain test.

- `:heavy_check_mark:`
  - Possible replacement: `&checkmark;`, `&#9989;` (white checkmark with green background box), `&#10004;` (the green doesn't render)
- `:heavy_exclamation_mark:`
  - Possible replacement: `&excl;`
- `:x:`
  - Possible replacement: `&cross;`, `&#10060;` (red X), `&#10062;` (white X with green background box, matches style of `&#9989`)

2022-07-21 18:48 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +- Windows Server 20H2 SAC :heavy_exclamation_mark: Will reach EOL on Aug 9, 2022
```suggestion
- Windows Server 20H2 SAC &excl; Will reach EOL on Aug 9, 2022
```

2022-08-01 16:11 UTC, jtravee commented
Hi @rosskirkpat, please also update your PR to be from staging rather than master as it will apply to an upcoming release. Thanks!

2022-08-19 22:06 UTC, jtravee commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +- Windows Server 20H2 SAC :heavy_exclamation_mark: Will reach EOL on Aug 9, 2022
Revised as suggested.

2022-08-19 22:17 UTC, jtravee approved these changes

2022-08-26 18:06 UTC, btat requested changes

2022-08-26 18:06 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +>- If you specify multiple matchExpressions associated with a single nodeSelectorTerms, then the Pod can be scheduled onto a node only if all the matchExpressions are satisfied.
```suggestion
>- If you specify multiple `matchExpressions` associated with a single `nodeSelectorTerms`, then the `Pod` can be scheduled onto a node only if all the `matchExpressions` are satisfied.
```

2022-08-26 18:06 UTC, btat commented on content/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/workload-migration-guidance/_index.md
> +### Migrating Windows Workloads to a new Rancher environment
```suggestion
### Migrating Windows Workloads to a New Rancher Environment
```

2022-08-26 18:07 UTC, btat approved these changes

2022-08-26 18:11 UTC, merged

2022-08-31 15:55 UTC, rosskirkpat commented
Thank you @btat and @jtravee for fixing this up and getting it merged!