Added Project Monitoring V2 page for 2.6.7
rancher/docs pull request #4222
Opened 2022-07-25 18:18 UTC by jtravee

Closes #4206 

- Added [Project Monitoring V2 page](https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/project-monitoring-v2) to document process of adding project monitors on to monitoring in the UI.

2022-08-02 16:42 UTC, btat requested changes

2022-08-05 15:04 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/_index.md
> +
Updated as suggested above.

2022-08-05 17:19 UTC, btat approved these changes

2022-08-10 16:04 UTC, aiyengar2 commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +1. Open the `system` project to check your namespaces:
```suggestion
1. Open the `System` project to check your namespaces:
```

2022-08-10 16:04 UTC, aiyengar2 commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +1. If you have an existing monitoring V2 installation in which `cattle-monitoring-system` is not in the `system` project, you may move the `cattle-monitoring-system` namespace into the `system` proje
```suggestion
1. If you have an existing Monitoring V2 installation within the `cattle-monitoring-system` namespace but that namespace is not in the `System` project, you may move the `cattle-monitoring-system` namespace into the `System` project or into another project of limited access. To do so, you may either:
```

2022-08-10 16:04 UTC, aiyengar2 commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +    Click **Cluster > Projects/Namespaces** in the Rancher UI. This will display all of the namespaces in the `system` project:
```suggestion
    Click **Cluster > Projects/Namespaces** in the Rancher UI. This will display all of the namespaces in the `System` project:
```

2022-08-10 16:04 UTC, aiyengar2 commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +    - Drag and drop the namespace into the `system` project or
```suggestion
    - Drag and drop the namespace into the `System` project or
```

2022-08-10 16:04 UTC, aiyengar2 commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +    - Select **⋮** to the right of the namespace, click **Move**, then choose `System` from the **Target Project** dropdown
is the `**:**` intentional?

2022-08-10 17:08 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +    - Select **⋮** to the right of the namespace, click **Move**, then choose `System` from the **Target Project** dropdown
Yes, I was bolding out the vertical ellipses: **⋮**.

2022-08-10 17:10 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +1. Open the `system` project to check your namespaces:
Updated as suggested.

2022-08-10 17:10 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +    Click **Cluster > Projects/Namespaces** in the Rancher UI. This will display all of the namespaces in the `system` project:
Updated as suggested.

2022-08-10 17:10 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +    - Drag and drop the namespace into the `system` project or
Updated as suggested.

2022-08-10 17:11 UTC, jtravee commented on content/rancher/v2.6/en/monitoring-alerting/prometheus-federator/guides/enable-prom-fed/_index.md
> +1. If you have an existing monitoring V2 installation in which `cattle-monitoring-system` is not in the `system` project, you may move the `cattle-monitoring-system` namespace into the `system` proje
Updated as suggested.

2022-08-15 17:28 UTC, aiyengar2 approved these changes
LGTM

2022-08-15 19:21 UTC, merged