Updated nginx versions and added note on new `-set ingress.ingressClassName=nginx` value
rancher/docs pull request #4227
Opened 2022-07-27 20:58 UTC by jtravee

Closes #4221 

- Updated nginx versions and added note on new value for GKE, AKS, and Amazon EKS
- For the K8s versions, we updated GKE, AKS, and EKS with a placeholder in this [PR](https://github.com/rancher/docs/pull/4218).

2022-08-02 16:30 UTC, btat requested changes

2022-08-02 16:30 UTC, btat commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/aks/_index.md
> +When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher helm install command in order to set the name of the ingress controller to be used with Ranch
```suggestion
When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher Helm install command in order to set the name of the ingress controller to be used with Rancher's ingress resource:
```

2022-08-02 16:30 UTC, btat commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/aks/_index.md
> +Refer [here for your cert options]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option).
```suggestion
Refer [here for the Helm install command]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option) for your chosen certificate option.
```

2022-08-02 16:30 UTC, btat commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/amazon-eks/_index.md
> +When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher helm install command in order to set the name of the ingress controller to be used with Ranch
```suggestion
When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher Helm install command in order to set the name of the ingress controller to be used with Rancher's ingress resource:
```

2022-08-02 16:30 UTC, btat commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/amazon-eks/_index.md
> +Refer [here for your cert options]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option).
```suggestion
Refer [here for the Helm install command]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option) for your chosen certificate option.
```

2022-08-02 16:30 UTC, btat commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/gke/_index.md
> +Refer [here for your cert options]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option).
```suggestion
Refer [here for the Helm install command]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option) for your chosen certificate option.
```

2022-08-02 16:30 UTC, btat commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/gke/_index.md
> +When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher helm install command in order to set the name of the ingress controller to be used with Ranch
```suggestion
When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher Helm install command in order to set the name of the ingress controller to be used with Rancher's ingress resource:
```

2022-08-03 20:12 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/gke/_index.md
> +When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher helm install command in order to set the name of the ingress controller to be used with Ranch
Updated as suggested.

2022-08-03 20:12 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/gke/_index.md
> +Refer [here for your cert options]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option).
Updated as suggested.

2022-08-03 20:12 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/amazon-eks/_index.md
> +Refer [here for your cert options]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option).
Updated as suggested.

2022-08-03 20:12 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/amazon-eks/_index.md
> +When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher helm install command in order to set the name of the ingress controller to be used with Ranch
Updated as suggested.

2022-08-03 20:12 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/aks/_index.md
> +Refer [here for your cert options]({{<baseurl>}}/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-rancher-with-helm-and-your-chosen-certificate-option).
Updated as suggested.

2022-08-03 20:13 UTC, jtravee commented on content/rancher/v2.6/en/installation/resources/k8s-tutorials/aks/_index.md
> +When installing Rancher on top of this setup, you will also need to pass the value below into the Rancher helm install command in order to set the name of the ingress controller to be used with Ranch
Updated as suggested.

2022-08-03 21:06 UTC, brudnak approved these changes

2022-08-03 21:09 UTC, btat approved these changes

2022-08-03 21:09 UTC, merged