Fix broken links and format errors
rancher/docs pull request #4229
Opened 2022-08-01 04:12 UTC by vickyhella

2022-08-05 17:49 UTC, btat requested changes

2022-08-05 17:49 UTC, btat commented on content/rancher/v2.6/en/k8s-in-rancher/load-balancers-and-ingress/ingress/_index.md
> +1. Create ingress forwarding **Rules**. For help configuring the rules, refer to [this section.](../ingress-config/_index.md#ingress-rule-configuration) If any of your ingress rules handle requests f
```suggestion
1. Create ingress forwarding **Rules**. For help configuring the rules, refer to [this section.](../ingress-config#ingress-rule-configuration) If any of your ingress rules handle requests for encrypted ports, add a certificate to encrypt/decrypt communications.
```

2022-08-05 17:49 UTC, btat commented on content/rancher/v2.6/en/k8s-in-rancher/load-balancers-and-ingress/ingress/_index.md
> +1. Create ingress forwarding **Rules**. For help configuring the rules, refer to [this section.](../ingress-config/_index.md#ingress-rule-configuration) If any of your ingress rules handle requests f
File path links don't seem to work with Hugo so a URL path needs to be used instead.

2022-08-07 17:12 UTC, vickyhella commented
Already updated per comments. PTAL. Thanks~ @btat

2022-08-08 16:10 UTC, btat approved these changes

2022-08-08 16:10 UTC, merged