Updated NV page for new 2.6.7 config for hardened clusters
rancher/docs pull request #4244
Opened 2022-08-08 20:43 UTC by jtravee

Closes #4242

2022-08-10 12:48 UTC, anupama2501 commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +     ![Enable PSP for RKE1 Hardened Cluster]({{<baseurl>}}/img/rancher/psp-nv-rke2.png)
this should be Enable PSP for **RKE2** Hardened Cluster

2022-08-10 12:59 UTC, anupama2501 commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +**_New in v2.6.7_**
This is the case for both k3s and RKE2 clusters. We should add k3s too

2022-08-10 20:49 UTC, btat requested changes
I may be missing something, but it looks like the screenshots are identical. If that is the case, then you can just reuse the same image instead.

2022-08-10 20:49 UTC, btat commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +   - Under **Edit Options** > **Other Configuration**, enable **Pod Security Policy** by checking the box. Note that  you must also enter a value greater than `zero` for `Manager runAsUser ID`, `Scan
```suggestion
   - Under **Edit Options** > **Other Configuration**, enable **Pod Security Policy** by checking the box. Note that you must also enter a value greater than `zero` for `Manager runAsUser ID`, `Scanner runAsUser ID`, and `Updater runAsUser ID`:
```

2022-08-11 13:24 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +     ![Enable PSP for RKE1 Hardened Cluster]({{<baseurl>}}/img/rancher/psp-nv-rke2.png)
Thanks for catching this! I updated as both RKE2 and K3s.

2022-08-11 13:24 UTC, jtravee commented on content/rancher/v2.6/en/neuvector-integration/_index.md
> +**_New in v2.6.7_**
Updated to indicate applicability to K3s as well.

2022-08-11 15:00 UTC, btat commented
> I may be missing something, but it looks like the screenshots are identical. If that is the case, then you can just reuse the same image instead.

Per discussion, the red box around the elements to select is the difference between the two. Please disregard previous comment.

2022-08-11 15:01 UTC, btat approved these changes

2022-08-12 07:46 UTC, anupama2501 approved these changes
lgtm

2022-08-12 11:58 UTC, merged