Adding a link to backup config page, added placeholder to MinIO config
rancher/docs pull request #4246
Opened 2022-08-09 18:47 UTC by jtravee

Closes #4245

2022-08-10 19:54 UTC, btat requested changes

2022-08-10 19:54 UTC, btat commented on content/rancher/v2.6/en/backups/examples/_index.md
> +>**Note:** Refer to the [backup config reference page]({{<baseurl>}}/rancher/v2.6/en/backups/configuration/backup-config/) for more information on configuring the options below.
This same update (with the appropriate text and link) needs to be applied to the corresponding area in the restore section as well.

2022-08-10 19:54 UTC, btat commented on content/rancher/v2.6/en/backups/examples/_index.md
> +      endpointCA: <base64-encoded-cert>
This same update needs to be applied to the corresponding area in the restore section as well.

2022-08-11 13:45 UTC, jtravee commented on content/rancher/v2.6/en/backups/examples/_index.md
> +      endpointCA: <base64-encoded-cert>
Updated, ty!

2022-08-11 13:46 UTC, jtravee commented on content/rancher/v2.6/en/backups/examples/_index.md
> +>**Note:** Refer to the [backup config reference page]({{<baseurl>}}/rancher/v2.6/en/backups/configuration/backup-config/) for more information on configuring the options below.
Updated, ty!

2022-08-11 15:16 UTC, btat approved these changes

2022-08-11 15:16 UTC, merged