Rancher 2.5.9 - backup / restore causes two default-tokens in each namespace
rancher/docs pull request #4253
Opened 2022-08-11 12:09 UTC by DevOpsNewbie

### For Rancher (product) docs only
When contributing to docs, please update the versioned docs. For example, the docs in the v2.6 folder of the `rancher` folder.

Doc versions older than the latest minor version should only be updated to fix inaccuracies or make minor updates as necessary. The majority of new content should be added to the folder for the latest minor version.

2022-08-11 15:39 UTC, jtravee requested changes

2022-08-11 15:39 UTC, jtravee commented on content/rancher/v2.5/en/backups/restoring-rancher/_index.md
> +In Rancher 2.5, under certain circumstances after restoring the backup, Rancher creates two default-tokens in each namespace:
```suggestion
Under certain circumstances after restoring the backup, Rancher creates two default-tokens in each namespace:
```

2022-08-11 15:39 UTC, jtravee commented on content/rancher/v2.5/en/backups/restoring-rancher/_index.md
> +In Rancher 2.5, under certain circumstances after restoring the backup, Rancher creates two default-tokens in each namespace:
Since the observation is in 2.5 versioned docs, you can omit mentioning the version.

2022-08-11 15:39 UTC, jtravee commented on content/rancher/v2.5/en/backups/restoring-rancher/_index.md
> +As a workound, you can use the following script, which removes the redundant restored default-token- secrets from restored Namespaces.
```suggestion
As a workaround, use the following script which removes the redundant restored default-token- secrets from restored Namespaces:
```

2022-08-11 15:39 UTC, jtravee commented on content/rancher/v2.5/en/backups/restoring-rancher/_index.md
> +This has been fixed in Rancher 2.6.4. See more information [here]
```suggestion
```

2022-08-11 15:39 UTC, jtravee commented on content/rancher/v2.5/en/backups/restoring-rancher/_index.md
> +(https://github.com/rancher/backup-restore-operator/issues/165#issuecomment-1079475984)
```suggestion
```

2022-09-06 07:26 UTC, DevOpsNewbie commented
PR canceled, as the docs won't be updated for Rancher 2.5 which is going to be EOL in October 2022.

2022-09-06 07:26 UTC, closed without merging