Adding instructions for eu listing
rancher/docs pull request #4259
Opened 2022-08-16 21:33 UTC by MbolotSuse

Updating the csp adapter docs with a new note for EU marketplace listings.

2022-08-16 23:47 UTC, brudnak approved these changes

2022-08-17 14:28 UTC, jtravee requested changes

2022-08-17 14:28 UTC, jtravee commented on content/rancher/v2.6/en/installation/cloud-marketplace/aws/adapter-install/_index.md
> +> **Note:** When installing the adapter, accounts using the marketplace listing for EMEA regions will need to specify an additional `--set image.repository=rancher/rancher-csp-adapter-eu` option. To
```suggestion
> **Note:** Accounts using the AWS Marketplace listing for Europe, the Middle East, and Africa (EMEA) regions will need to specify an additional `--set image.repository=rancher/rancher-csp-adapter-eu` option. To see if your account needs this option when installing the adapter, refer to the usage instructions of the marketplace listing. 
```

2022-08-17 15:55 UTC, MbolotSuse commented on content/rancher/v2.6/en/installation/cloud-marketplace/aws/adapter-install/_index.md
> +> **Note:** When installing the adapter, accounts using the marketplace listing for EMEA regions will need to specify an additional `--set image.repository=rancher/rancher-csp-adapter-eu` option. To
I've changed this section, though I did remove the word "regions" as well (felt awkward in the new suggested text).

2022-08-17 16:45 UTC, jtravee approved these changes

2022-08-17 16:54 UTC, btat approved these changes

2022-08-17 18:37 UTC, merged