Adding docs/RN for all versions
rancher/docs pull request #4286
Opened 2022-08-30 22:36 UTC by jtravee

2022-08-30 23:36 UTC, btat requested changes
The stable/unmaintained labels should be removed because of how our versions are structured. E.g. For 2.6.x the docs are either all maintained or all unmaintained, but it wouldn't be the case we maintain 2.6.8, but not earlier because our setup doesn't differentiate.

I've added examples of showing the how the known portions of the URLs will be formatted. Those will need to be updated for each entry.

Another column we could link to is the Support Matrix. Thoughts on adding that?

2022-08-30 23:36 UTC, btat commented on src/pages/versions.md
> +### Past versions (no longer maintained)
```suggestion
### Past versions
```

2022-08-30 23:36 UTC, btat commented on src/pages/versions.md
> +### Current versions (stable)
```suggestion
### Current versions
```

2022-08-30 23:36 UTC, btat commented on src/pages/versions.md
> +    <td><a href="https://rancher.com/docs/rancher/v2.5/en/">Documentation</a></td>
```suggestion
    <td><a href="https://URL_PLACEHOLDER/v2.5/rancher-manager">Documentation</a></td>
```

2022-08-30 23:36 UTC, btat commented on src/pages/versions.md
> +    <td><a href="https://rancher.com/docs/rancher/v2.0-v2.4/en/">Documentation</a></td>
```suggestion
    <td><a href="https://URL_PLACEHOLDER/v2.5/rancher-manager">Documentation</a></td>
```

2022-08-30 23:36 UTC, btat commented on src/pages/versions.md
> +    <td><a href="https://rancher.com/docs/rancher/v2.6/en/">Documentation</a></td>
```suggestion
    <td><a href="https://URL_PLACEHOLDER/">Documentation</a></td>
```

2022-08-31 14:33 UTC, jtravee commented on src/pages/versions.md
> +### Past versions (no longer maintained)
Updated.

2022-08-31 14:34 UTC, jtravee commented on src/pages/versions.md
> +### Current versions (stable)
Updated.

2022-08-31 14:34 UTC, jtravee commented on src/pages/versions.md
> +    <td><a href="https://rancher.com/docs/rancher/v2.5/en/">Documentation</a></td>
Updated.

2022-08-31 14:34 UTC, jtravee commented on src/pages/versions.md
> +    <td><a href="https://rancher.com/docs/rancher/v2.6/en/">Documentation</a></td>
Updated.

2022-08-31 14:34 UTC, jtravee commented
> The stable/unmaintained labels should be removed because of how our versions are structured. E.g. For 2.6.x, the docs are either all maintained or all unmaintained, but it wouldn't be the case we maintain 2.6.8, but not earlier because our setup doesn't differentiate. So it doesn't make sense to use the stable/maintained labels.
> 
> I've added examples of showing the how the known portions of the URLs will be formatted. Those will need to be updated for each entry.
> 
> Another column we could link to is the Support Matrix. Thoughts on adding that?

Great idea on the support matrix; I'll add those.

2022-08-31 17:30 UTC, btat requested changes
Now that we have a confirmed URL, could you update the placeholders.

2022-09-02 18:34 UTC, btat requested changes
The wrong URL was added. Should be `http://docs.ranchermanager.rancher.io/`.

Also, looks like parts of the URL got left off for the older versions.
E.g. /v2.5/ and /v2.0-v2.4/

2022-09-02 21:31 UTC, btat approved these changes

2022-09-02 21:31 UTC, merged