Add notation for `kubectl logs` command
rancher/docs pull request #4287
Opened 2022-08-31 02:55 UTC by masap

### For Rancher (product) docs only

Add notation for `kubectl logs` command to warn users that the logs will be truncated.

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

2022-08-31 13:48 UTC, jtravee requested changes

2022-08-31 13:48 UTC, jtravee commented on content/rancher/v2.6/en/troubleshooting/kubernetes-resources/_index.md
> +This command can show logs of all the pods labeled "app=ingress-nginx", but it shows only 10 lines of log because of restriction of `kubectl logs` command. Refer `--tail` of `kubectl logs -h`.
```suggestion
The below command will show the logs of all the pods labeled "app=ingress-nginx". However, you may limit the number of logs by appending `--tail` to `kubectl logs -h`. For example, to limit the logs to 10 lines, specify `--tail=10`.
```

2022-08-31 13:48 UTC, jtravee commented on content/rancher/v2.6/en/troubleshooting/kubernetes-resources/_index.md
> +If full log is needed specify pod name like trailing command.
```suggestion
If the full log is needed, specify the pod name in the trailing command:
```

2022-08-31 23:41 UTC, masap commented on content/rancher/v2.6/en/troubleshooting/kubernetes-resources/_index.md
> +This command can show logs of all the pods labeled "app=ingress-nginx", but it shows only 10 lines of log because of restriction of `kubectl logs` command. Refer `--tail` of `kubectl logs -h`.
@jtravee Thanks for comment?

I mean `-l` option has a side effect.

Assume we have a pod labeled "app=ingress-nginx".
```
$ kubectl -n ingress-nginx get po -l app=ingress-nginx
NAME                             READY   STATUS    RESTARTS       AGE
nginx-ingress-controller-b45ls   1/1     Running   1 (161m ago)   4h3m
```

When we display the log of pod with `-l` option, we could only see last 10 lines.
```
$ kubectl -n ingress-nginx logs -l app=ingress-nginx | wc -l
10
```

Even though it has more lines actually.
```
$ kubectl -n ingress-nginx logs nginx-ingress-controller-b45ls | wc -l
462
```

This is a part of `kubectl logs -h` command. At `--tail` it says "Defaults to -1 with no selector, showing all log lines otherwise 10, if a selector is provided.". The selector is specified with `-l` option.
```
    --tail=-1:
	Lines of recent log file to display. Defaults to -1 with no selector,
	showing all log lines otherwise 10, if a selector is provided.
...
    -l, --selector='':
	Selector (label query) to filter on, supports '=', '==', and
	'!='.(e.g. -l key1=value1,key2=value2). Matching objects must satisfy
	all of the specified label constraints.

```

2022-09-01 07:17 UTC, bashofmann approved these changes

2022-09-01 16:53 UTC, btat approved these changes

2022-09-01 16:54 UTC, jtravee approved these changes

2022-09-01 16:54 UTC, merged