Adding banners to Rancher docs, K3s docs, RKE1 docs
rancher/docs pull request #4288
Opened 2022-09-01 13:49 UTC by jtravee

Adding banners to Rancher, K3s, and RKE1 docs in Hugo in prep for the transition to Docusaurus sites.

2022-09-01 21:48 UTC, btat requested changes

2022-09-01 21:48 UTC, btat commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. Rancher Manager docs are in the process of migrating to a new website as we transition from Hugo to the Docusaurus framework.
```suggestion
          <strong>Rancher Manager docs are in the process of migrating to a new website. We will update the community with the new site information after it is launched.</strong>
```

Let's save the `You are viewing the documentation in our older website.` part till we update the banner after launch. As of now this is still our only website for RM docs.

Moving from Hugo to Docusaurus is technical implementation detail which is not really a user concern. However, the content structure change will affect users so that should probably be mentioned.

2022-09-01 21:48 UTC, btat commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. The K3s docs have moved from the Rancher docs website to a separate website. We will update the community with the new site i
```suggestion
          <strong>The K3s docs will be moving from the Rancher docs website to a separate website. We will update the community with the new site information after it is launched.</strong>
```

2022-09-01 21:48 UTC, btat commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. The K3s docs have moved from the Rancher docs website to a separate website. We will update the community with the new site i
The first and second sentence seem to conflict right now. If we're saying it has already moved, users will expect to know where to find the new docs.

2022-09-01 21:48 UTC, btat commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. The RKE1 docs have moved from the Rancher docs website to a separate website. We will update the community with the new site
```suggestion
          <strong>The RKE1 docs will be moving from the Rancher docs website to a separate website. We will update the community with the new site information after it is launched.</strong>
```

2022-09-02 19:39 UTC, jtravee commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. Rancher Manager docs are in the process of migrating to a new website as we transition from Hugo to the Docusaurus framework.
Updated with suggestions.

2022-09-02 19:41 UTC, jtravee commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. The RKE1 docs have moved from the Rancher docs website to a separate website. We will update the community with the new site
Updated.

2022-09-02 19:41 UTC, jtravee commented on layouts/_default/list.html
> +          <strong>You are viewing the documentation in our older website. The K3s docs have moved from the Rancher docs website to a separate website. We will update the community with the new site i
Updated.

2022-09-02 19:57 UTC, btat approved these changes

2022-09-02 19:57 UTC, merged